- src/Microsoft.Framework.CodeGeneration/Program.cs
Removing current directory symbol '.' from ```dnx gen``` command
/cc @Eilon
> Remove '.' from dnx gen command

- src/Microsoft.Extensions.CodeGeneration.EntityFramework/Templates/DbContext/NewLocalDbContext.cshtml
- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/ApiControllerWithContext.cshtml
- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
Addressing below issues identified by @rowanmiller  
•	Null check after using Single is not needed as Single will throw if no entity is found. We probably want to swap to SingleOrDefault (rather than removing the null check) so that we return a Not Found status code.
•	We already discussed, but we should remove the EnsureCreated call to create the database. It’s not thread safe, and blocks you from using migrations in the future. We could look at scaffolding the corresponding migration for the user when we change the model for a given context.
•	Remove empty override of OnConfiguring, folks should use Startup.cs rather than this hook in ASP.NET 5 apps.
•	I would remove the empty override of OnModelCreating too – it doesn’t add much value.
cc @abpiskunov, @sayedihashimi, @barrytang
> DB context related changes

- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Common/CommonCommandLineModel.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Controller/ControllerGeneratorBase.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Controller/ControllerWithContextGenerator.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Controller/MvcController.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/MessageStrings.Designer.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/MessageStrings.resx
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/NameSpaceUtilities.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/RoslynUtilities.cs
- test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test/ControllerGeneratorBaseTests.cs
- test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test/MockControllerGenerator.cs
- test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test/NamespaceUtilitiesTest.cs
- test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test/RoslynUtilitiesTest.cs
Fixes #229 by accepting a namespace parameter from user instead of always using `<appName>.Controllers` as the namespace. 
If the param is not provided, it falls back to old behavior, but checks if the `<appName>.Controllers` is valid or not. If not just uses `Controllers` as the namespace. 
cc @abpiskunov, @sayedihashimi
> Add controllerNamespace parameter to Controller generator

- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/NavigationMetadata.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/NavigationMetadataTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/TestModels/Models.cs
Fixes #232 
The `Displayname` property is used in the [MvcControllerWithContext.cshtml](https://github.com/aspnet/Scaffolding/blob/dev/src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml#L106) to create a `SelectList`
In MVC5 the behavior was if the `Navigation.TargetType` has a string property it would use it as the display property. 
If there is no string property it would use the primary key from the navigation. 
Here we do the same thing, except we also check if the string column is nullable or not. 
If it is nullable, we fall back to using the navigation's primary key.  
cc @natemcmaster
> Compute the display property for the navigation metadata.

- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Templating/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration/project.json
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/project.json
Fixes #237 
Haven't finished validating that no pre-core naming is used anywhere, but wanted to review the package metadata and tags earlier. 
cc @sayedihashimi, @Eilon, @barrytang
> Update package Metadata for Code Generation packages

- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Controller/ControllerWithContextGenerator.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/ModelMetadataUtilities.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ViewGenerator/Empty.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ViewGenerator/_ValidationScriptsPartial.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/View/EmptyViewScaffolder.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/View/ModelBasedViewScaffolder.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/View/RequiredFileEntity.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/View/ViewGenerator.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/View/ViewGeneratorModel.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/View/ViewScaffolderBase.cs
- test/E2E_Test/Baseline/CarViews/Create.cshtml
- test/E2E_Test/Baseline/SharedViews/_ValidationScriptsPartial.cshtml
- test/E2E_Test/Baseline/Views/CarCreate.txt
- test/E2E_Test/Baseline/Views/CarDetails.txt
- test/E2E_Test/Baseline/Views/EmptyView.txt
- test/E2E_Test/MvcControllerTest.cs
- test/E2E_Test/ViewGeneratorTests.cs
- test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test/ModelMetadataUtilitiesTest.cs
Changes:
- Add required files based on view generator model. Fixes #257
- Remove duplicated code between View Generator and ControllerWithContextGenerator
- Add support for adding empty view
- Split ViewGenerator into the command line entrypoint and the actual scaffolders so we have a consistent pattern for Controller and View Generation. 
- E2E tests for View Generation. 
TODO: 
- Rename the ControllerGenerators to Scaffolders to better distinguish between the commandline entry point and the actual scaffolders.
> Use view generator to generate views while generating controller with context.

- build.ps1
- build.sh
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/DotNetBuildCommandHelper.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/project.json
- test/Microsoft.Extensions.ProjectModel.Tests/project.json
- Now that CLI has merged the *3 verbs, no longer need to use `build3` for building msbuild projects.
- Remove MsBuild and NuGet dependency overrides from .Tools package.
Note: The same changes need to flow to feature/msbuild-1.1.0 branch as well. 
@natemcmaster @NTaylorMullen
> Remove usage of build3 for msbuild projects.

- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/EntityFrameworkServices.cs
- test/E2E_Test/MvcControllerTest.cs
- test/E2E_Test/ViewGeneratorTests.cs
Trying to fix the test issue on CI, where E2E tests fail while trying to load project dependencies. 
cc @natemcmaster
> Load project dependencies by name instead of path in EFServices.

- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/project.json
The _inside man_ needs to be able to run on x86 machines when user is on x86 machine. 
This is being repacked already as part of https://github.com/aspnet/Scaffolding/blob/pb/fixArchitecture/makefile.shade#L26-L83
cc @natemcmaster
> Fix configuration for x86 net451 build for CodeGeneration.Design

- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/EntityFrameworkServices.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/ReflectedTypesProvider.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/project.json
- test/E2E_Test/MvcControllerTest.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/ReflectedTypesProviderTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/TestAssemblyLoadContext.cs
- test/Shared/MsBuildProjectSetupHelper.cs
- test/Shared/MsBuildProjectStrings.cs
Instead of trying to host user's app to get the DbContext, while scaffolding, let EF run its magic.
Fixes #339 
cc @mlorbetske, @bricelam
> Use EF Design APIs to get DbContext instance from user code.

- src/Shared/DotNetDispatcher/DotnetToolDispatcher.cs
Fix the DotNetDispatcher to check only the framework name and not the version for `netcoreapp`
cc @pranavkm 
_This fix needs to flow to 1.1.0-msbuild3 branch as well_
> Fix dispatcher's check for netcoreapp to ignore version of netcore app

- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ControllerGenerator/ControllerWithActions.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
- test/E2E_Test/Compiler/Resources/CarsController.txt
- test/E2E_Test/Compiler/Resources/CarsWithViewController.txt
- test/E2E_Test/Compiler/Resources/ProductsController.txt
- test/E2E_Test/Compiler/Resources/ReadWriteController.txt
Use the C# 6 `nameof` expression in the MVC controller action method `RedirectToAction` calls. This makes the scaffolded controllers consistent with the `RedirectToAction` calls used in the project templates (in the aspnet/Templates repo).
> Use nameof expression in controller RedirectToAction calls

- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ViewGenerator/Edit.cshtml
- test/E2E_Test/Compiler/Resources/CarViews/Edit.cshtml
- test/E2E_Test/Compiler/Resources/ProductViews/Edit.cshtml
The generated `Edit.cshtml` Razor view was missing a tab before the hidden input field. See the affected line in the screenshot below.
@prafullbhosale
> Add indentation before hidden input field

- src/Microsoft.VisualStudio.Web.CodeGeneration/CodeGenCommand.cs
This will prevent the stack trace from showing up on Visual Studio error dialogs, but will be available in the output window. 
**Before**: 
**After**:
> Print stack trace for exceptions on stdout instead of stderr

- NuGetPackageVerifier.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild.csproj
These binaries are shipped in the .Tools package. We don't need the .MSbuild package.
> Stop producing Microsoft.VisualStudio.Web.CodeGeneration.Msbuild

- build/dependencies.props
- src/Microsoft.VisualStudio.Web.CodeGeneration.Contracts/Microsoft.VisualStudio.Web.CodeGeneration.Contracts.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/Microsoft.VisualStudio.Web.CodeGeneration.Core.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Templating/Microsoft.VisualStudio.Web.CodeGeneration.Templating.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Microsoft.VisualStudio.Web.CodeGeneration.Tools.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/Microsoft.VisualStudio.Web.CodeGeneration.Utils.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration/Microsoft.VisualStudio.Web.CodeGeneration.csproj
Moving all versions of dependencies to `dependencies.props` to make it easier to update them.
cc @natemcmaster
> Refactor versions to dependencies.props

- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.csproj
It was removed from Microsoft.EntityFrameworkCore.Design.
> [2.0.0-preview1] Re-add a reference to System.Reflection.TypeExtensions

- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Microsoft.VisualStudio.Web.CodeGeneration.Tools.csproj
Fixes #474 
cc @Eilon @mlorbetske
> Mark CommandLineUtils.Sources as private dependency

- test/E2E_Test/AreaScaffolderTests.cs
- test/E2E_Test/E2ETestBase.cs
- test/E2E_Test/MvcControllerTest.cs
- test/E2E_Test/SimulationModeTests.cs
- test/E2E_Test/ViewGeneratorTests.cs
- test/Shared/MsBuildProjectSetupHelper.cs
Fixes #479 
Scaffolding accepts the configuration parameter and assumes it to be debug by default. 
On CI's since `env.Configuration` is set to `Release`, it causes the build to output stuff into to `bin/release/...` folders. 
A recent change in E2E test project setup caused the builds to be done in the set configuration and scaffolding to be invoked in 'Debug' configuration with `--no-build` flag.
> Fix tests for Release configuration.

- src/Microsoft.VisualStudio.Web.CodeGeneration.Templating/RazorTemplating.cs
- src/Shared/Cli.Utils/Command.cs
The razor engine had a feature that had built in default `using`s for
System and `System.Threading.Tasks`. We're removing that API. You can
either define your own global `using`s and other directives like I did
in this workaround, or just add the necessary namespaces where they are
used.
I also fixed the console output for tests. I'm not sure if was
intentionally not working, but this makes the tests much easier to
diagnose.
> Unbreak failing tests

- test/Shared/MsBuildProjectSetupHelper.cs
- test/Shared/MsBuildProjectStrings.cs
CodeGenerationPackage version is based on the package version created in
this build.
AspNetCorePackage version is based on the version of
'Microsoft.Extensions.FileProviders.Physical' used to build the test
projects.
cc @mlorbetske
> Pin packageversions during test project creation.

- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/ParamDefinition.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Program.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Resources.Designer.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Resources.resx
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/ScaffoldingApp.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/ToolCommandLineHelper.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.csproj
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/ParameterDefinitions/area.json
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/ParameterDefinitions/controller.json
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/ParameterDefinitions/view.json
- src/Shared/General/ConsoleLogger.cs
The Package `Microsoft.VisualStudio.Web.CodeGenerators.Mvc` carries the `ParameterDefinition` files for each of the code generators.
The CLI tool `dotnet-aspnet-codegenerator` scans the NuGet dependencies of the project to find out which ones have these files and displays help based on that. 
This allows showing help and discovering generators in the CLI tool without having to dispatch to the inside man.
```
>dotnet aspnet-codegenerator -h
Usage: aspnet-codegenerator [arguments] [options]
Arguments:
generator  Name of the generator. Check available generators below.
Options:
-p|--project             Path to .csproj file in the project.
-n|--nuget-package-dir
-c|--configuration       Configuration for the project (Possible values: Debug/ Release)
-tfm|--target-framework  Target Framework …
```
> Show Help based on parameterDefinition files.

- test/Microsoft.Extensions.ProjectModel.Tests/Microsoft.Extensions.ProjectModel.Tests.csproj
This is to prevent the `warning MSB3277`'s we've been seeing in Universe.
> Add explicit dependency to prevent conflict

- build/dependencies.props
- Microsoft.DotNet.ProjectModel is only used by tests, so we should float the version to automatically test the latest version published to nuget.org
> Float version of Microsoft.DotNet.ProjectModel

- src/VS.Web.CG.EFCore/CodeModelMetadata.cs
- src/VS.Web.CG.EFCore/IModelMetadata.cs
- src/VS.Web.CG.EFCore/IPropertyMetadata.cs
- src/VS.Web.CG.EFCore/ModelMetadata.cs
- src/VS.Web.CG.EFCore/PropertyMetadata.cs
Fixes #544 
This will help people trying to access `CustomAttributes` on their model and model properties and use them in their own razor templates for scaffolding.
> Expose Type and Property information with metadata

- test/Shared/MsBuildProjectStrings.cs
- All package downgrade warnings should be currently fixed, and we want tests to fail for any new downgrade warnings.
- Resolves https://github.com/aspnet/Scaffolding/issues/533
> Enable package downgrade warnings

- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/CodeGenCommandExecutor.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/Program.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/Resources.Designer.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/Resources.resx
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Program.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Resources.Designer.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Resources.resx
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/ScaffoldingApp.cs
- src/Shared/General/ConsoleLogger.cs
- version.props
Fixes #588 
cc @mlorbetske @Eilon
> Show help when no args are passed

- NuGet.config
I was seeing some test failures in 2.0.1:
```
[13:52:49] :	 [Step 2/2]      Restoring packages for /home/aspnetagent/buildAgent/temp/buildTmp/tmpfiles/c46165e7-3a80-4a55-a5f9-acc341c400b7/Library1/Library1.csproj...
[13:52:49] :	 [Step 2/2]      Restoring packages for /home/aspnetagent/buildAgent/temp/buildTmp/tmpfiles/c46165e7-3a80-4a55-a5f9-acc341c400b7/Root/Test.csproj...
[13:52:49] :	 [Step 2/2]      Restoring packages for /home/aspnetagent/buildAgent/temp/buildTmp/tmpfiles/c46165e7-3a80-4a55-a5f9-acc341c400b7/Root/Test.csproj...
[13:52:49] :	 [Step 2/2]      Generating MSBuild file /home/aspnetagent/buildAgent/temp/buildTmp/tmpfiles/c46165e7-3a80-4a55-a5f9-acc341c400b7/Library1/obj/Library1.csproj.nuget.g.props.
[13:52:49] :	 [Step 2/2]      Generating MSBuild file …
```
> Add patch feed

- src/VS.Web.CG.Mvc/Templates/ControllerGenerator/ApiControllerWithContext.cshtml
- src/VS.Web.CG.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/DeletePageModel.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/DetailsPageModel.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/EditPageModel.cshtml
- test/E2E_Test/Compiler/Resources/CarsController.txt
- test/E2E_Test/Compiler/Resources/CarsWithViewController.txt
- test/E2E_Test/Compiler/Resources/ProductsController.txt
- test/E2E_Test/Compiler/Resources/RazorPages/Crud/DeleteCs.txt
- test/E2E_Test/Compiler/Resources/RazorPages/Crud/DetailsCs.txt
- test/E2E_Test/Compiler/Resources/RazorPages/Crud/EditCs.txt
Fixes #300 
Make use of `FindAsync` instead of `SingleOrDefaultAsync` in the scaffolding templates. Fixes the root cause of the problem identified by @ajcvickers in https://github.com/aspnet/Docs/pull/4253.
@divega Please review.
> Replace occurrences of SingleOrDefaultAsync

- build/dependencies.props
- test/Directory.Build.targets
- test/Shared/MsBuildProjectSetupHelper.cs
- test/Shared/MsBuildProjectStrings.cs.in
- version.props
Depends on https://github.com/aspnet/BuildTools/pull/416
Instead of manually updating the hard-coded test packages every time we change patch versions, this will generate the sample test projects using the versions in dependencies.props.
> Generate the test projects at build

- src/Shared/General/ConsoleLogger.cs
> Set output encoding to UTF8

- Directory.Build.props
- NuGet.config
- build/sources.props
- test/Ext.ProjectModel.Tests/NuGet.config
- test/Shared/MsBuildProjectSetupHelper.cs
- test/Shared/MsBuildProjectStrings.cs.in
Part of https://github.com/aspnet/Coherence-Signed/issues/682
This backports some fixes already in release/2.0.0 to better support orchestrated build.
> Use MSBuild to set NuGet feeds instead of NuGet.config

- src/Shared/Cli.Utils/DotNetMuxer.cs
This is why tests might fail on AppVeyor but not other machines. See also https://github.com/aspnet/Common/pull/299
> Use Process.MainModule, not FX_DEPS_FILE to find dotnet.exe

- Scaffolding.sln
- test/Shared/MsBuildProjectStrings.cs.in
The .cs.in file had undefined variables and was causing a build warning.
> Fix build warnings about missing template variables

- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorFileComparer.cs
- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorFilesConfig.cs
- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
- src/VS.Web.CG.Mvc/Identity/identitygeneratorfilesconfig.json
- test/E2E_Test/IdentityScaffolderTests.cs
- test/Shared/MsBuildProjectSetupHelper.cs
- test/Shared/MsBuildProjectStrings.cs.in
- test/VS.Web.CG.Mvc.Test/IdentityGeneratorTemplateModelBuilderTests.cs
- Changed the default name for the generated DbContext to be `IdentityDataContext` 
- Earlier it was `IdentityDbContext` and it would clash with the one from Identity assemblies.
- Enabled passing in an existing user class in case a new DbContext is being generated.
- Some pages under `Pages/Account/Mangage` have a dependency on `/Pages/Account/Manage/_ManageNav.cshtml`. 
- Added support to scaffold dependency pages when they are not selected. 
- Also added E2E tests that test scaffolding each individual page and ensure that the project still builds.
> Bug fixes for identity scaffolder.

- build/dependencies.props
- src/VS.Web.CG.Templating/RazorTemplating.cs
- src/VS.Web.CG.Templating/VS.Web.CG.Templating.csproj
Between preview1 and preview2, the bitness of .NET Framework targeting projects changed from x86 to AnyCPU [1]. Consequently the app is compiled with AnyCPU, but the Scaffolding binary is x86. In both preview1 and preview2, Mvc attempts to load Scaffolding binaries because it appears to be a candidate containing controllers[2]. However, the change in bitness of the app results in an exception when attempting to Assembly.Load scaffolding's binary. Possible suggested fixes:
* Make Scaffolding not appear to be a candidate for Mvc
* Put the correct bitness exe in the output directory.
[1] - Between Preview1 and Preview2, Asp.Net Core no longer depends on Libuv, a native dependency. This causes the PlatformTarget to change. Here's the culprit: …
> Remove reference to Microsoft.AspNetCore.Mvc.Razor.Extensions

- tools/Directory.Build.props
It throws off Universe's groove because these projects under tools/ appear to produce the same package ID.
> Set projects under tools/ as IsPackable=false

- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorFilesConfig.cs
- test/VS.Web.CG.Mvc.Test/IdentityGeneratorFilesConfigTests.cs
Fixes #844 
This fix is targeted for the release/2.2 branch. We can back-port it for servicing as appropriate.
> Dont overwrite wwwroot dir if it exists and is non-empty

- src/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs
- src/VS.Web.CG.EFCore/MessageStrings.Designer.cs
- src/VS.Web.CG.EFCore/MessageStrings.resx
The current behavior is that scaffolding exits with no message, and the logged info doesn't indicate the problem. This causes a meaningful message to be reported to the user when a newly generated DbContext has compilation errors - which is usually caused by type name clashes. For example, give a DbContext name of "AppContext", "MyApp.Data.AppContext", etc.
**Update**
This PR has been updated to deal with more general errors with DB Contexts. The error message was already created, this just causes the error message to properly propagate back to the user.
> Better messaging of DbContext errors

- Scaffolding.sln
- src/VS.Web.CG.EFCore/DbContextEditorServices.cs
- test/E2E_Test/Compiler/Resources/BlogsController.txt
- test/E2E_Test/Compiler/Resources/BlogsDerivedDbContext.txt
- test/E2E_Test/E2E_Test.csproj
- test/E2E_Test/MvcControllerTest.cs
- test/Shared/MsBuildProjectSetupHelper.cs
- test/Shared/MsBuildProjectStrings.cs.in
Before this fix, if the model property is defined on a class that the selected db context is derived from, the model property would be added on the selected db context. This would hide the base classes model property.
> Fix for EF controller scaffolding when the model is defined on a parent of the selected db context

- src/VS.Web.CG.Mvc/Identity/bootstrap3_identitygeneratorfilesconfig.json
- src/VS.Web.CG.Mvc/Identity/bootstrap4_identitygeneratorfilesconfig.json
This is meant to fix this issue: #750 
Most of the errors referenced in those tests indicate a casing issue between a filename on disk and how the file is referenced in the config files being changed here (which should only be an issue on *nix). But it seems like this error would have been occurring since identity scaffolding was added.
This may be a red-herring in terms of the test failures, but the config should match case anyway.
> Fix identity generator test. Fixes case diff between config and actual filenames

- src/VS.Web.CG.Mvc/Controller/CommandLineGeneratorModel.cs
- src/VS.Web.CG.Mvc/RazorPage/RazorPageScaffolderBase.cs
Causes razor page scaffolding to use the default bootstrap version when a bootstrap version is not provided by the command line args.
> Fix for razor scaffolding when user project provides no bootstrap version

- version.props
Per my understanding of how VS picks the version packages to add as a PackageReference, this is still required everytime we patch aspnetcore 2.1.&, right @vijayrkn ?
> Bump version to 2.1.7

- build/dependencies.props
- version.props
Update the scaffolding build to 2.2.1-servicing-<build number>
> Update to 2.2.1-servicing

- src/VS.Web.CG.Mvc/Identity/identitygeneratorfilesconfig.json
The file was removed from the directory tree in #949 - which broke Identity scaffolding of a project without a wwwroot directory. This resynchronizes the files on disk, and the configuration.
> Removing bower file from identity config

- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorFilesConfig.cs
I noticed that the casing of the two file names differed. This PR makes use of the existing constant to enforce consistency.
> Use constant for readme text file name

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.ConfirmEmailChange.cs.cshtml
Scaffolding fails during file generation due to missing parens in this template file.
> Fix scaffolding file generation issues in ConfirmEmailChange.cs.cshtml

- eng/Versions.props
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.ConfirmEmailChange.cs.cshtml
Scaffolding fails during file generation due to missing parens in this template file.
> Fix scaffolding file generation issues

- global_install.cmd
- src/VS.Web.CG.Design/VS.Web.CG.Design.csproj
- src/VS.Web.CG.Design/VS.Web.CG.Design.nuspec
removing win64 and changing it to anycpu to fix error with msbuild. 
tested with Windows, and Mac.
> changing win64 to anycpu.

- src/dotnet-aspnet-codegenerator/Resources.resx
The only place where Resources.NoCodeGeneratorsFound is used is
followed immediately by a use of Resources.AddDesignPackage
resulting in a duplicated instruction:
"No code generators are available in this project. Please add the
'Microsoft.VisualStudio.Web.CodeGeneration.Design' NuGet package
to the project.Please add
Microsoft.VisualStudio.Web.CodeGeneration.Design package to the
project as a NuGet package reference."
> Removed duplicated instruction from NoCodeGeneratorsFound

- src/VS.Web.CG.Mvc/RazorPage/RazorPageScaffolderBase.cs
Cli tool was still using application name over root namespace as namespace prefix when not provided a namespace. VS provides one.
> Razor page namespace fix

- src/VS.Web.CG.Mvc/Templates/ControllerGenerator/ApiControllerWithContext.cshtml
- src/VS.Web.CG.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap3/CreatePageModel.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap4/CreatePageModel.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap4/EditPageModel.cshtml
- test/E2E_Test/Compiler/Resources/CarsController.txt
- test/E2E_Test/Compiler/Resources/CarsControllerWithDAL.txt
- test/E2E_Test/Compiler/Resources/CarsWithViewController.txt
- test/E2E_Test/Compiler/Resources/ProductsController.txt
Changes comments in 9 files from the form:
```
// POST: Movies/Edit/5
// To protect from overposting attacks, enable the specific properties you want to bind to, for 
// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
```
to:
```
// POST: Movies/Edit/5
// To protect from overposting attacks, enable the specific properties you want to bind to.
// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
```
> Fix comment wording

- eng/Versions.props
- src/VS.Web.CG.Msbuild/ProjectContextWriter.cs
- src/VS.Web.CG.Msbuild/Properties/AssemblyInfo.cs
- src/VS.Web.CG.Msbuild/Target/build/Microsoft.VisualStudio.Web.CodeGeneration.Tools.targets
- src/VS.Web.CG.Msbuild/VS.Web.CG.Msbuild.csproj
- src/VS.Web.CG.Mvc/VS.Web.CG.Mvc.csproj
- src/dotnet-aspnet-codegenerator/Program.cs
- test/Shared/MSBuildProjectStrings.cs
- test/Shared/MsBuildProjectSetupHelper.cs
- test/Shared/TemporaryFileProvider.cs
- test/VS.Web.CG.MSBuild.Test/ProjectContextWriterTests.cs
- test/VS.Web.CG.MSBuild.Test/TestBase.cs
- test/VS.Web.CG.MSBuild.Test/VS.Web.CG.MSBuild.Tests.csproj
since the project system changes in the sdk 3.1.4+ and 5.0.0-preview7+, we need to populate dependencies using the projects.assets.json file.
- Using msbuild property to get the assets file location and then parsing the json.
- added unit tests and one to test dependencies using a bare net 5.0 project with the CodeGeneration.Design dependency.
Will port over VS fairly soon as well (until we are ready to use the Nuget API).
> using projects.assets.json to get project dependencies

- eng/Versions.props
- src/Ext.ProjectModel.MsBuild.Sources/MsBuildProjectContextBuilder.cs
- src/Shared/Cli.Utils/Command.cs
- src/Shared/DotNetDispatcher/DotnetToolDispatcher.cs
- src/VS.Web.CG.Contracts/ProjectModel/CommonProjectContext.cs
- src/VS.Web.CG.Contracts/ProjectModel/IProjectContext.cs
- src/VS.Web.CG.Msbuild/ProjectContextWriter.cs
- src/VS.Web.CG.Msbuild/Target/build/Microsoft.VisualStudio.Web.CodeGeneration.Tools.targets
- src/VS.Web.CG.Msbuild/VS.Web.CG.Msbuild.csproj
- src/VS.Web.CG.Utils/VS.Web.CG.Utils.csproj
- src/dotnet-aspnet-codegenerator/DotNetBuildCommandHelper.cs
- src/dotnet-aspnet-codegenerator/Program.cs
- src/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
- test/E2E_Test/E2E_Test.Tests.csproj
- test/Shared/MSBuildProjectStrings.cs
- test/VS.Web.CG.EFCore.Test/CodeModelServiceTests.cs
- test/VS.Web.CG.EFCore.Test/EntityFrameworkServicesTests.cs
- test/VS.Web.CG.MSBuild.Test/ProjectContextWriterTests.cs
- test/VS.Web.CG.MSBuild.Test/TestBase.cs
- test/VS.Web.CG.MSBuild.Test/VS.Web.CG.MSBuild.Tests.csproj
- test/VS.Web.CG.Sources.Test/TestBase.cs
- test/VS.Web.CG.Templating.Test/TestCompilationService.cs
- test/VS.Web.CG.Tools.Test/VS.Web.CG.Tools.Tests.csproj
removing Nuget.Frameworks dependency.
- only use for to get TargetFrameworkMoniker from short folder name.
- can get both properties from design time build
> removing Nuget.Frameworks dependency

- eng/Versions.props
Fixes issues is .NET Core projects with Razor Runtime compilation enabled. 3.7.0 is a stable version so should be more error free.
> fixing CodeAnalysis version

- src/VS.Web.CG.Mvc/Templates/ViewGenerator/Bootstrap4/Delete.cshtml
Was causing issues in the Delete page when scaffolded a model. User would have to manually edit the erroneous tag.
Removing it from the template should fix the issue.
> removed class atrribute from closing dd tag

- global_install.sh
cleans older packages, builds and installs the dotnet-aspnet-codegenerator tool on linux and mac systems.
> added global_install.sh

- src/VS.Web.CG.Msbuild/ProjectContextWriter.cs
- test/VS.Web.CG.MSBuild.Test/ProjectContextWriterTests.cs
- for linux and mac users, if capitalized path ala "Microsoft.VisualStudio..." cannot be found in the nuget folder due to the case-sensitive file system, it will also try to look for "microsoft.visualstudio..."
- going to get ported for 3.1, 5.0 and 6.0-preview1.
> added lower case check for package paths

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ExternalLogin.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ForgotPassword.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Login.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Register.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ResendEmailConfirmation.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ResetPassword.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.ChangePassword.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.DeletePersonalData.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.Disable2fa.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.DownloadPersonalData.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.EnableAuthenticator.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.ExternalLogins.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.GenerateRecoveryCodes.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.Index.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.PersonalData.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.SetPassword.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.ShowRecoveryCodes.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.TwoFactorAuthentication.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage._Layout.cshtml
Port of https://github.com/dotnet/aspnetcore/pull/29706
> Port Identity UI accessibility fixes to scaffolding

- src/Scaffolding/VS.Web.CG.Design-anycpu/VS.Web.CG.Design-anycpu.csproj
- src/Scaffolding/VS.Web.CG.Design-arm/VS.Web.CG.Design-arm.csproj
- src/Scaffolding/VS.Web.CG.Design-arm64/VS.Web.CG.Design-arm64.csproj
no need to pack the dotnet-aspnet-codegenerator-design tool for default or other runtimes.
> added false IsPackable for design tool.

- eng/Versions.MsIdentity.props
- eng/Versions.props
- src/MsIdentityScaffolding/Microsoft.DotNet.MsIdentity/AuthenticationParameters/ApplicationParameters.cs
- src/MsIdentityScaffolding/Microsoft.DotNet.MsIdentity/AuthenticationParameters/AzureAdProperties.cs
- src/MsIdentityScaffolding/Microsoft.DotNet.MsIdentity/CodeReaderWriter/CodeWriter.cs
- src/MsIdentityScaffolding/Microsoft.DotNet.MsIdentity/Microsoft.DotNet.MsIdentity.csproj
- src/MsIdentityScaffolding/Microsoft.DotNet.MsIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MsIdentityScaffolding/Microsoft.DotNet.MsIdentity/ProjectDescription/ProjectDescriptionReader.cs
- src/MsIdentityScaffolding/Microsoft.DotNet.MsIdentity/Tool/AppProvisioningTool.cs
- src/MsIdentityScaffolding/Microsoft.DotNet.MsIdentity/Tool/ProvisioningToolOptions.cs
- src/MsIdentityScaffolding/README.md
- src/Scaffolding/Shared/Cli.Utils/Command.cs
- src/Scaffolding/Shared/Cli.Utils/DotNetMuxer.cs
- tools/dotnet-msidentity/Program.cs
- tools/dotnet-msidentity/README.md
Preview 1 version of the tool to be used on the command line and with VS 16.10 Preview 2.
--update-project command --client-id [--calls-graph] [--calls-downstream-api] [--update-user-secrets]
- updates appsettings.json
- creates secret, adds to azure ad app, updates local user-secrets
> dotnet-msidentity Preview 1

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeReader.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeWriter.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectAuthenticationSettings.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/Commands.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/IMsAADTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/JsonResponse.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/MsAADTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/ProvisioningToolOptions.cs
- test/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity.UnitTests.Tests/MsAADToolTests.cs
- tools/dotnet-msidentity/Program.cs
Added 2 commands 
- add-client-secret
- Create a client secret, add it to the Azure AD app registration. 
- update-app-registration
- Update Azure AD app registrations with redirect URLs
> Added --add-client-secret and --update-app-registration

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/ApplicationParameters.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeReader.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeWriter.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/Commands.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/ConsoleLogger.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/IConsoleLogger.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/JsonResponse.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/MsAADTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/ProvisioningToolOptions.cs
- test/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity.Tests/ProjectDescriptionReaderTests.cs
- test/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity.UnitTests.Tests/MicrosoftIdentityPlatformApplicationManagerTests.cs
- tools/dotnet-msidentity/MsAADToolFactory.cs
- tools/dotnet-msidentity/Program.cs
Initial Draft
- added --create-app-registration
- allows to create Azure AD/AD B2C app registrations. 
- TODO : change object being passed back?
- renamed --add-client-secret --> --create-client-secret
- added ConsoleLogger to simplify outputting to console when --json is enabled
- changed --project-path to have path to the .csproj file instead of folder with the .csproj file.
- added ValidateUrisTest unit test
> added create-app-registration command

- src/MSIdentityScaffolding/README.md
- tools/dotnet-msidentity/Program.cs
- tools/dotnet-msidentity/README.md
- tools/dotnet-msidentity/dotnet-msidentity.csproj
Update
- both READMEs in src/tools/dotnet-msidentity and src/MsIdentity (package version in the README as well)
- help text in src/tools/dotnet-msidentity/Program.cs
> [dotnet-msidentity] help, README, and version update

- scripts/install-msidentity.cmd
I updated the `install-msidentity.cmd` to work from any folder. How it was written required the user to be in the `scaffolding` folder.
> updating install-msidentity.cmd to work from any folder

- tools/dotnet-msidentity/Program.cs
The `--update-project` will allow updating of the C# project incrementally now with the following new options:
- `--code-update` will update the Startup.cs, and other layout files for the C# project to be Microsoft Identity platform ready.
- `--packages-update` will add the necessary packages needed for Microsoft identity platform experience.
- `--config-update` will update the `appsettings.json` file appropriately.
- other minor edits
Only adding the command options currently for unblocking other scenarios. A follow up PR will the feature work very soon.
> added more command options for --update-project

- eng/Versions.props
- src/Scaffolding/VS.Web.CG/VS.Web.CG.csproj
Reacting to breaking change - https://github.com/dotnet/announcements/issues/190 by removing package reference to System.ComponentModel.Annotations.
- also corrected versions for 6.0-preview5 packages in Versions.props
> net 6.0 breaking change to remove package reference

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
When calling the CLI tool from VS, the tenant ID parameter sent in was not being used for creating app registrations, updating app registrations, etc. So in certain cases the CLI tool will infer the wrong tenant ID from the VS project rather than using the tenant that the VS user has currently selected. This change makes it so the CLI tool uses the tenant ID parameter sent in from VS for these operations.
> Propagate correct tenant ID from command line args

- src/Scaffolding/VS.Web.CG.Mvc/Identity/identityMinimalHostingChanges.json
Now we can add multiple .AddDbContext for SqlServer and Sqlite in Program.cs in identity scenarios.
> add more AddDbContext in Program.cs if one exists

- azure-pipelines.yml
Added if statements for Windows, macOS, and Linux build jobs.
- on public pipelines, build both Debug and Release configurations.
- on internal (signed) pipelines, build only Release configurations.
> adding if conditions for debug and release jobs

- src/Scaffolding/VS.Web.CG.Mvc/RazorPage/RazorPageScaffolderBase.cs
Fixing error when upgrading a .NET Core 3.1/5 app to .NET 6.
- Bootstrap 4 is not upgraded to Bootstrap 5, kept at 4 and no errors are thrown. 
- If users wants to upgrade to Bootstrap 5, we expect it to do it themselves or create a new .NET 6 app.
> added check for bootstrap 4

- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/DocumentBuilder.cs
Shouldn't matter what type of node, ExpressionStatementSyntax or InvocationStatementSyntax etc.
> removing node type check, we shouldn't care what type of node.

- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModel2.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
Fix for [#38640](https://github.com/dotnet/aspnetcore/issues/38640). 
If Blazor project w/ individual auth adds a custom Accout\Logout.cshtml file, don't try to add/suggest overwrite for that file.
> not adding/forcing Account.Logout.cshtml if blazor project already adding it

- azure-pipelines.yml
- src/Scaffolding/VS.Web.CG.Design/CodeGenCommandExecutor.cs
- src/Scaffolding/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs
- src/Scaffolding/VS.Web.CG.EFCore/NewDbContextTemplateModel.cs
- src/Scaffolding/VS.Web.CG.EFCore/Templates/DbContext/NewLocalDbContext.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Controller/ControllerWithContextGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Controller/ControllerWithContextTemplateModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/RazorPage/RazorPageScaffolderBase.cs
- src/Scaffolding/VS.Web.CG.Mvc/RazorPage/RazorPageWithContextTemplateModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/ControllerGenerator/ApiControllerWithContext.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/CreatePageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/DeletePageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/DetailsPageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/EditPageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/EmptyPageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/ListPageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/ViewGenerator/Bootstrap5/Details.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/View/ViewGeneratorTemplateModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/View/ViewScaffolderBase.cs
- src/Scaffolding/VS.Web.CG.Utils/DotNet/ApplicationInfo.cs
- src/Scaffolding/VS.Web.CG.Utils/DotNet/IApplicationInfo.cs
- src/Scaffolding/VS.Web.CG.Utils/Workspaces/RoslynWorkspace.cs
- src/Scaffolding/VS.Web.CG.Utils/Workspaces/RoslynWorkspaceHelper.cs
- test/Scaffolding/VS.Web.CG.EFCore.Test/CodeModelServiceTests.cs
- test/Scaffolding/VS.Web.CG.EFCore.Test/EntityFrameworkServicesTests.cs
- test/Scaffolding/VS.Web.CG.Mvc.Test/ControllerGeneratorBaseTests.cs
- test/Scaffolding/VS.Web.CG.Mvc.Test/IdentityGeneratorTemplateModelBuilderTests.cs
- test/Scaffolding/VS.Web.CG.Sources.Test/ApplicationInfoTests.cs
- Checking for `<Nullable>enable/disable</Nullable>` MsBuild property.
- Adding `#nullable disable` to EF Scaffolding templates if nullable is enabled for the project.
- Helps with current warnings.
- Will be handled with newer templates in .NET 7 timeline likely.
> Adding #nullable disable to scaffolding templates

- src/Scaffolding/VS.Web.CG.Core/ActionInvoker.cs
- test/Scaffolding/VS.Web.CG.Core.Test/ActionInvokerTests.cs
1. `ActionInvoker` constructs its `InvalidOperationException` chained with the caught exception.
2. Add a test to check that this is the case.
Does not fix #1726.
> [WiP] Make sure ActionInvoker throws with InnerException

- src/Scaffolding/VS.Web.CG.Core/ActionInvoker.cs
- src/Scaffolding/VS.Web.CG.Design/Program.cs
- src/Scaffolding/VS.Web.CG/CodeGenCommand.cs
Log the whole [exception chain](https://docs.microsoft.com/en-us/dotnet/api/system.exception.innerexception) when an [Exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception) gets caught by a program.
> OnExecute: log inner exceptions

- src/Scaffolding/VS.Web.CG.Utils/Workspaces/RoslynWorkspaceHelper.cs
`RoslynWorkspaceHelper.GetProjectReferenceInformation`: when `new Project` throws an [Exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception), wrap it with an [InvalidOperationException](https://docs.microsoft.com/en-us/dotnet/api/system.invalidoperationexception) holding the value of `projectReferenceString`.
> Include projectReferenceString in exception

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeFiles/Blazor/Server/CallWebApi.razor
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorserver.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapi.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapp.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.Designer.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.resx
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/CodeChange/CodeChangeHelper.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
1. Adds code updates for blazor server "calls downstream API" option including CallWebApi.razor
2. Adds more code file filtering -> Startup.cs will be ignored when "NonMinimalApp" is false, Program.cs will be ignored when "MinimalApp" is false
3. Fix bug in ProjectModifierHelper. UpdateDocument where code files are added by FileName rather than by FilePath
> Code updates for blazor server Downstream API option

- tools/dotnet-aspnet-codegenerator/Program.cs
- tools/dotnet-aspnet-codegenerator/Resources.Designer.cs
- tools/dotnet-aspnet-codegenerator/Resources.resx
`GetTargetsLocation` throws a [DirectoryNotFoundException](https://docs.microsoft.com/en-us/dotnet/api/system.io.directorynotfoundexception) if the build directory is not found.
Fixes #1733.
There are no tests for the tool.
> code generator: GetTargetsLocation: throw if not found

- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Cli.Utils/Command.cs
Add Command.ToString (returning file name and arguments)
Add Command._logger
Add LogMessage to Execute (before starting)
Fixes #1736
Tracing is not essential, so no test.
> Add tracing to Command.Execute

- scripts/install-aspnet-codegenerator.cmd
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
- src/Scaffolding/VS.Web.CG.Mvc/RazorPage/RazorPageGeneratorTemplateModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/RazorPage/RazorPageScaffolderBase.cs
- src/Scaffolding/VS.Web.CG.Mvc/RazorPage/RazorPageWithContextTemplateModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/View/ViewGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/View/ViewScaffolderBase.cs
- improved string check for commandline passed bootstrap versions.
- not throwing InvalidOperation exception if bootstrap version not found, just returning default.
Tested .net6 projects with bootstrap 3, 4, 5 and invalid versions. All work well.
> not throwing exception on invalid bootstrap versions.

- eng/Versions.MSIdentity.props
- eng/Versions.props
dotnet-aspnet-codegenerator --> 7.0.0-preview 1
dotnet-msidentity --> 2.0.0-preview 1
> bump on both preview versions.

- src/Scaffolding/VS.Web.CG.Core/ActionInvoker.cs
- src/Scaffolding/VS.Web.CG.Design/Program.cs
- src/Scaffolding/VS.Web.CG/CodeGenCommand.cs
reverting #1751.
After extensive debugging and looking at error messages in VS and on the command-line, have decided to revert this merge. 
- Error messages are significantly verbose, sometimes repeating themselves since top-level exceptions can be minor modifications of inner exceptions and since everything is logged, its quite messy looking.
- The issue remains but we need a better fix that to concatenate all the exception messages. Maybe that would be ok on command line experience but not for VS that is consuming the this tool as well.
@yecril71pl I have opened this [issue](https://github.com/dotnet/Scaffolding/issues/1820) to track it.
> Revert "OnExecute: log inner exceptions (#1751)"

- azure-pipelines.yml
- These builds do not contribute to the official build outputs
- These jobs are still run in PRs and rolling public CI
- This avoids having to use 1ES pools in these cases
> Avoid building OSX/Linux in official

- scripts/install-aspnet-codegenerator.sh
- src/Scaffolding/VS.Web.CG.Mvc/RazorPage/RazorPageGeneratorTemplateModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/RazorPage/RazorPageScaffolderBase.cs
- src/Scaffolding/VS.Web.CG.Mvc/RazorPage/RazorPageWithContextTemplateModel.cs
Fixing issue on macOS and Linux running the following command:
`dotnet aspnet-codegenerator razorpage Empty Empty -udl` with error:
> fixed missing NullableEnabled property in the RazorPageModel

- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorFilesConfig.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
Fixes - https://github.com/aspnet/AspNetCore-ManualTests/issues/1232
Only adding _ViewStart file for non blazor projects.
> Only adding _ViewStart to non blazor projects (identity)

- Directory.Build.props
- eng/Versions.props
Security compliance issue, bumping up version.
> bumping System.Security.Cryptography.X509Certificates version

- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/identityMinimalHostingChanges.json
throwing exception if GetConnectionString returns null, adding to identity config for when adding a new DbContext and DbContextConnectionString. 
[Context ](https://github.com/dotnet/Scaffolding/pull/1830)
> throwing exception if GetConnectionString returns null.

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/Scaffolding/VS.Web.CG.EFCore/DbContextEditorServices.cs
- src/Scaffolding/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs
- src/Scaffolding/VS.Web.CG.EFCore/IDbContextEditorServices.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/identityMinimalHostingChanges.json
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGenerator.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/CodeChange/CodeChangeHelper.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/DocumentBuilder.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
- test/Scaffolding/VS.Web.CG.EFCore.Test/DbContextEditorServicesTests.cs
- test/Scaffolding/VS.Web.CG.EFCore.Test/EntityFrameworkServicesTests.cs
- test/Scaffolding/VS.Web.CG.Mvc.Test/IdentityGeneratorTests.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/DocumentBuilderTestBase.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/DocumentBuilderTests.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/ProjectModifierHelperTests.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/weo444pm.j3w~
Added support for no top-level statements
- if dev opts into 'no top level statements', Program.cs file will have a classic namespace, class, and method structure.
- Adding code to 'Main' method in the correct spots.
- Added additional tests.
> Added support for no top-level statements

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorserver.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_minimal_api.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapi.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapp.json
- Fixes spacing issue for code update configs
- Fixes issue with Minimal Web API code modifier config where "scopeRequiredByApi" variable would not be generated if the Program.cs file does not contain "app.UseAuthorization" line, resulting in a failure to compile.
> Fix spacing and bug fix for Minimal Api Scopes code update

- src/Shared/Microsoft.DotNet.Scaffolding.Shared/MsBuild/MsBuildProjectContextBuilder.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectContextHelper.cs
adding support for tfm "net7.0-windows" 
- tfm was not supported, parsing projects.assets.json was failing. 
- fixed parsing, rest of the flow just works.
> supporting os version tfm for "-windows"

- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGeneratorCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/ModelMetadataUtilities.cs
Addresses #1897 
- support for mac/linux minimal api scaffolders with support for sqlite.
- use `-sqlite/--useSqlite` with the `minimalapi` scaffolder.
> added support for sqlite for minimal api scaffolding.

- src/Scaffolding/VS.Web.CG.EFCore/Templates/DbContext/NewLocalDbContext.cshtml
fixes nullable warnings
- don't use nullable entity set value, instead use default operator.
- fixes minimal api scaffolder, razor page and api scaffolder warnings.
> fix nullable warnings for new db context template.

- Directory.Build.props
- eng/Versions.props
forcing System.Configuration.ConfigurationManager v6.0.0 to fix missing system dlls error.
> forcing version for System.Configuration.ConfigurationManager

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorwasm.json
The "DownstreamApi" option needs to be specified for modifying the "FetchData" page for blazor wasm projects, otherwise the file gets modified even if there is not a downstream API configured.
See bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1553434
> Fix code update config for blazor wasm

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/AzureAdProperties.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorwasm.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/AppSettingsModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
> CTI Bug fixes for release7.0-preview5

- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/_LoginPartial.cshtml
The "btn-link" class has 1px border and, as a result, a button looks misplaced.
Before:
After:
> Fix position of the Logout button near the profile link

- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/identityMinimalHostingChanges.json
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/DocumentBuilder.cs
- not adding duplicate AddDbContext and AddDefaultIdentity blocks.
> fixed identity Program.cs changes

- tools/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
- tools/dotnet-msidentity/dotnet-msidentity.csproj
- tools/dotnet-scaffold/dotnet-scaffold.csproj
To fix Component governance vulnerability issue with Newtonsoft.Json v9.0.1 being installed.
> bumping up NuGet.Packaging to fix vulnerability.

- Directory.Build.props
- eng/Versions.props
- test/Directory.Build.props
- tools/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
- tools/dotnet-msidentity/dotnet-msidentity.csproj
- tools/dotnet-scaffold/dotnet-scaffold.csproj
To fix Component governance vulnerability issue with Newtonsoft.Json v9.0.1 being installed. 
#1947  didn't work.
> previous fix didn't work, using Build.props now

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeWriter.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Microsoft.DotNet.MSIdentity.csproj
- src/Scaffolding/VS.Web.CG.Core/VS.Web.CG.Core.csproj
- src/Scaffolding/VS.Web.CG.Design-anycpu/VS.Web.CG.Design-anycpu.csproj
- src/Scaffolding/VS.Web.CG.Design-arm/VS.Web.CG.Design-arm.csproj
- src/Scaffolding/VS.Web.CG.Design-arm64/VS.Web.CG.Design-arm64.csproj
- src/Scaffolding/VS.Web.CG.Design/VS.Web.CG.Design.csproj
- src/Scaffolding/VS.Web.CG.EFCore/VS.Web.CG.EFCore.csproj
- src/Scaffolding/VS.Web.CG.Msbuild/Target/build/Microsoft.VisualStudio.Web.CodeGeneration.Tools.targets
- src/Scaffolding/VS.Web.CG.Msbuild/VS.Web.CG.Msbuild.csproj
- src/Scaffolding/VS.Web.CG.Mvc/VS.Web.CG.Mvc.csproj
- src/Scaffolding/VS.Web.CG.Templating/VS.Web.CG.Templating.csproj
- src/Scaffolding/VS.Web.CG.Utils/VS.Web.CG.Utils.csproj
- src/Scaffolding/VS.Web.CG/VS.Web.CG.csproj
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Microsoft.DotNet.Scaffolding.Shared.csproj
- test/Scaffolding/TestApps/ClassLibrary1/ClassLibrary1.csproj
- test/Scaffolding/TestApps/ClassLibrary2/ClassLibrary2.csproj
- test/Scaffolding/TestApps/ModelTypesLocatorTestClassLibrary/ModelTypesLocatorTestClassLibrary.csproj
- test/Scaffolding/TestApps/ModelTypesLocatorTestWebApp/ModelTypesLocatorTestWebApp.csproj
- test/Scaffolding/TestApps/PreviousPackage/PreviousPackage.csproj
- test/Scaffolding/TestApps/StablePackage/StablePackage.csproj
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/ProjectModelHelperTests.cs
- tools/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
- tools/dotnet-msidentity/dotnet-msidentity.csproj
- tools/dotnet-scaffold/dotnet-scaffold.csproj
Updating all projects to net7.0.
- overdue and removes reliance on .NET 6 runtime.
> updating all source projects to net7.0.

- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
DbContext model's full name was not being checked. For example:
```
DbContext class : 
namespace blah 
{
public class TestDbContext : DbContext 
{}
}
```
Now, when we pass it to dotnet-aspnet-codegenerator, we can pass it as `blah.TestDbContext` or `TestDbContext`. Before this check, passing `blah.TestDbContext` would create an additional TestDbContext as it would not find the one we are looking for.
> [Scaffolding] checking for full model name (includes namespace) when checking for db context type

- scripts/install-scaffold.cmd
- tools/dotnet-msidentity/Program.cs
- tools/dotnet-msidentity/Properties/AssemblyInfo.cs
- tools/dotnet-scaffold/Program.cs
- tools/dotnet-scaffold/dotnet-scaffold.csproj
dotnet-scaffold changes:
- adding dotnet-msidentity commands.
- dotnet-aspnet-codegenerator commands have additional `--`. 
- dotnet-scaffold Program.cs calls into the CommandHandlers in Microsoft.DotNet.Tool.Program's CommandHandlers.
Previous help:
```
scaffold:
dotnet scaffold [command] [-p|--project] [-n|--nuget-package-dir] [-c|--configuration] [-tfm|--target-framework] [-b|--build-base-path] [--no-build]
Usage:
scaffold [options] [command]
Options:
-p, --project <project>                        Specifies the path of the project file to run (folder name or full path). If not specified, it defaults to the current directory.
-n, --nuget-package-dir <nuget-package-dir>    Specifies the NuGet package directory.
-c, --configuration <configuration>            Defines the build …
```
> changes for first dotnet-scaffold release

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/MsAADTool.cs
Adds check for "Downstream API" before adding API permissions for B2C apps
Adds "IsB2C" field to app registrations, so that "calls-graph" checkbox is disabled for B2C Apps
> Fix B2C Bugs

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Microsoft.DotNet.MSIdentity.csproj
- src/Scaffolding/VS.Web.CG.Design/CodeGenCommandExecutor.cs
- src/Scaffolding/VS.Web.CG.Design/VS.Web.CG.Design.csproj
- src/Scaffolding/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs
- src/Scaffolding/VS.Web.CG.Msbuild/ProjectContextWriter.cs
- src/Scaffolding/VS.Web.CG.Msbuild/Target/build/Microsoft.VisualStudio.Web.CodeGeneration.Tools.targets
- src/Scaffolding/VS.Web.CG.Mvc/Controller/ControllerWithContextGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/RazorPage/RazorPageGeneratorTemplateModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/RazorPage/RazorPageScaffolderBase.cs
- src/Scaffolding/VS.Web.CG.Mvc/View/ViewGeneratorTemplateModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/View/ViewScaffolderBase.cs
- src/Scaffolding/VS.Web.CG.Utils/DotNet/ApplicationInfo.cs
- src/Scaffolding/VS.Web.CG.Utils/DotNet/IApplicationInfo.cs
- src/Scaffolding/VS.Web.CG.Utils/VS.Web.CG.Utils.csproj
- src/Scaffolding/VS.Web.CG.Utils/Workspaces/RoslynWorkspace.cs
- src/Scaffolding/VS.Web.CG.Utils/Workspaces/RoslynWorkspaceHelper.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/CommonProjectContext.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/IProjectContext.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectContextExtensions.cs
- test/Scaffolding/Shared/MSBuildProjectStrings.cs
- test/Scaffolding/Shared/MsBuildProjectSetupHelper.cs
- test/Scaffolding/VS.Web.CG.MSBuild.Test/ProjectContextWriterTests.cs
- test/Scaffolding/VS.Web.CG.Mvc.Test/ControllerGeneratorBaseTests.cs
- test/Scaffolding/VS.Web.CG.Mvc.Test/IdentityGeneratorTemplateModelBuilderTests.cs
- test/Scaffolding/VS.Web.CG.Sources.Test/ApplicationInfoTests.cs
We were using Microsoft.Build.Locator to load in requisite Microsoft.Build assemblies (using MSBuildLocator.RegisterDefaults()) to : 
- initialize Microsoft.Build.Evaluation.Project object
- use `Project.GetProperty("ms build property name")?.EvaluatedValue` to get needed MSBuild project properties
- we needed the "Nullable" property.
Now:
- Added Nullable string property to IProjectContext
- Initialize IProjectContext during runtime msbuild operation using updated `VS.Web.CG.Msbuild/Target/build/Microsoft.VisualStudio.Web.CodeGeneration.Tools.targets` file.
- Nullable property populated at runtime without performing additional Microsoft.Build initialization and calls.
Changes : 
- Removed package references to `Microsoft.Build.Locator`
- Removed all calls to …
> init. Removed dependency on MSBuildLocator.RegisterDefaults().

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/CodeAnalysisHelper.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/CodeAnalysisHelperTests.cs
Changes CodeAnalysisHelper to use AdhocWorkspace instead of MSBuildWorkspace
With this change, Document filepaths are always found via Document.Name whereas before, .cs files had the filepath stored in Document.FilePath
> Use AdhocWorkspace instead of MSBuildWorkspace

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/AzureAdProperties.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.Designer.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.resx
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/DocumentBuilder.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
- test/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity.UnitTests.Tests/AppProvisioningToolTests.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/DocumentBuilderTests.cs
Fixes for B2C API scenarios
Adds better logging and error handling for app updates and code updates
> Updates for B2C Web APIs and Logging 

- scripts/install-aspnet-codegenerator.sh
- src/Scaffolding/VS.Web.CG.EFCore/DbContextEditorServices.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApi.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiNoClass.cshtml
- test/Scaffolding/VS.Web.CG.EFCore.Test/compiler/resources/DbContextNullable_After.txt
Addressing #1937 
- using routes.MapGroup instead of routes.Map(Get/Put/Post etc.)
- adding `Microsoft.AspNetCore.Http.HttpResults` to usings.
- changing nullable DbContext set from `public DbSet<Model>? DbSet { get; set; }` -->  `public DbSet<Model> DbSet { get; set; } = default!` for parity with scaffolding templates.
- addressing #1963 
- addressing #1954
> Minimal api changes

- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGenerator.cs
- test/Scaffolding/Shared/MSBuildProjectStrings.cs
Check if endpoints class is static,
- if it **IS**, continue as usual, create endpoints method in that class.
- if it **IS NOT**, create a new static class in the same file (at the end of the file) and add the scaffolded endpoints method to the newly created class.
- additional fix where `Microsoft.EntityFrameworkCore` namespace is added if a DbContext is being used, not just when a DbContext namespace is present (in the endpoints class).
> checking if endpoints class is static, if not, creating one.

- src/Scaffolding/VS.Web.CG.Mvc/Templates/ControllerGenerator/ApiControllerWithContext.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/CreatePageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/DeletePageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/DetailsPageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/EditPageModel.cshtml
new bug with the property `NullableEnabled` changing from bool to string. Need a string comparison for the check now.
> fix razor page and controller templates for NullableEnabled

- src/Scaffolding/VS.Web.CG.Mvc/Templates/ControllerGenerator/ApiControllerWithContext.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/CreatePageModel.cshtml
Bug introduced in #2008. `NullableEnabled` was still bool, not a string, so comparison changed.
> fixing controller templates

- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/identityMinimalHostingChanges.json
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/DocumentBuilder.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
- not adding extra whitespace when using top level statements.
- checking FileScopedNamespace and regular Namespace for finding methods in `GetMethodFromSyntaxRoot`
- adding extra logic for `IsUsingTopLevelStatements`
> not adding extra whitespace and checking for Main method correctly

- scripts/install-msidentity.cmd
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/ProvisioningToolOptions.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectModelHelper.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/DocumentBuilderTestBase.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/ProjectModifierHelperTests.cs
added `ProcessCsprojFile` and `ProcessTfm` to get a project's target framework(s) from the .csproj file.
- ProcessCsprojFile uses XDocument to get all children nodes in the csproj file
> [MsIdentity] parse csproj file and add tfm(s).

- src/Scaffolding/VS.Web.CG.Msbuild/ProjectReferenceInformationProvider.cs
- src/Scaffolding/VS.Web.CG.Msbuild/Target/build/Microsoft.VisualStudio.Web.CodeGeneration.Tools.targets
- src/Scaffolding/VS.Web.CG.Utils/Workspaces/RoslynWorkspace.cs
- src/Scaffolding/VS.Web.CG.Utils/Workspaces/RoslynWorkspaceHelper.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectContextExtensions.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectReferenceInformation.cs
After removing MSBuildLocator to get msbuild assemblies and loading msbuild projects, project references fail for models, db contexts etc.
- added `ResolveProjectReferences` task.
> adding target for and carrying over project refs.

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/ProjectDescription/ProjectDescriptionReader.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
- tools/dotnet-msidentity/Program.cs
Adds the optional parameter "--susi-policy-id" for the code update command. Used for B2C scenarios to update the appsettings.json file with the correct B2C Sign up sign in policy ID.
Also makes "dotnet-webapp" the default project type in case the project type cannot be inferred.
> Add Susi Policy Id parameter for Code Update 

- eng/Versions.props
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGenerator.cs
- test/Scaffolding/VS.Web.CG.Mvc.Test/MinimalApiGeneratorTests.cs
Addresses #1884 
- Changed `Path.Join` to `Path.Combine`
- Not skipping test for this use.
> fix minimal api --outDir bug

- eng/Versions.props
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
Following guidelines for [SA1202 ](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1202.md)and [SA1204](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1204.md)
- addresses #1840
> rearrange project modifier.cs

- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApi.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiNoClass.cshtml
Addressing changes from #2037.
Notes (@DamianEdwards) : 
> `Update non-EF Core scaffolder to also use TypedResults`
- the non-EF scaffolder has commented out the Results return so just have changed it TypedResults but still commented out.
> minimal api net7 changes

- scripts/install-aspnet-codegenerator.cmd
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGeneratorCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApi.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiNoClass.cshtml
Addressing more changes #2037  :
- added `MinimalApiGenerator.NoTypedResults` instead of TypedResults to make it an opt out option.
- opposite of `MinimalApiGenerator.OpenAPI` where it is an opt in, mistake in hindsight but due to backwards compat, cannot reverse this. Will be a minor fix for .NET 8 timeline.
- Opting in would allow an alternate of writing the API endpoints with `Produces` and `Results`.
- Template changes can be reviewed in this [repo](https://github.com/deepchoudhery/minimal-api-endpoints) (both EF and non EF scenarios)
> adding option to opt out of typed results and templates changes

- eng/Versions.props
bumped NuGet.Packaging from 6.2.1 --> 6.3.1 and NuGet.ProjectModel from 5.11.0 --> 6.3.1
> bumping NuGetPackagingVersion for security vulnerability

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/Scaffolding/VS.Web.CG.Design/Program.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectContextExtensions.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectContextHelper.cs
- test/Scaffolding/VS.Web.CG.MSBuild.Test/ProjectContextWriterTests.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/ProjectModifierHelperTests.cs
Context : IProjectContext is populated using a custom target msbuild restore operation. For the CLI scenario, we have no issues but for the VS scenario, it is not able to populate a newer IProjectContext yet with the `Nullable` property. Therefore, we need to set it in `src/Scaffolding/VS.Web.CG.Design/Program.cs`
- GetXmlKeyValue : parses any xml file and will return string value for any string key provided.
- CheckNullableVariable : checks for a missing nullable variable, and parses the csproj (xml) file to set one.
> added ProjectContextHelper.GetXmlKeyValue and IProjectContext.CheckNullableVariable

- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiModel.cs
- add `Microsoft.AspNetCore.Http.HttpResults` namespace when MinimalApiModel.UseTypedResults is true, not when OpenAPI is true.
> add `AspNetCore.Http.HttpResults` namespace when TypedResults is enabled.

- azure-pipelines.yml
In order to mitigate the cost of builds in released code, we move them to a "-Svc" pool provider. These providers use the same machine size and images as their non-Svc counterparts, but bill differently.
> Use "-Svc" build pools in release branches (release/7.0)

- azure-pipelines.yml
In order to mitigate the cost of builds in released code, we move them to a "-Svc" pool provider.  These providers use the same machine size and images as their non-Svc counterparts, but bill differently.
> Use "-Svc" build pools in release branches (release/6.0)

- azure-pipelines-codeql.yml
- azure-pipelines.yml
- removed Codeql.Enabled from `azure-pipelines.yml`
- created `azure-pipelines-codeql.yml`. Got it from dotnet/arcade pretty much.
- will create pipeline in devops after.
> removed codeql from pipeline, new one for codeql

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/MsAADTool.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/DocumentBuilder.cs
- Adding an error output when app registrations fail to load
- Fixing a redundant newline formatting nit in DocumentBuilder.cs
> Output error for app registrations, and small formatting nit

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/MsAADTool.cs
A few small fixes:
- if GetGraphObjects method fails, puts the output in the JsonResponse Output field rather than the Content field
- if there are no app registrations, but everything succeeded, returns a JsonResponse with empty list rather than failing
> Fix output for app registrations

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/DeveloperCredentials/DeveloperCredentialsReader.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/DeveloperCredentials/MsalTokenCredential.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/TokenCredentialAuthenticationProvider.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.Designer.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.resx
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/GraphObjectRetriever.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/MsAADTool.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ConsoleLogger.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/IConsoleLogger.cs
- test/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity.UnitTests.Tests/MsAADToolTests.cs
Refactored retrieving app registrations in order to make unit testing easier
Add ConsoleLogger for logging when token authentication fails
Add unit tests for getting app registrations
> Log token authentication failure to JsonResponse, Refactor getting app registrations

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/DeveloperCredentials/MsalTokenCredential.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.Designer.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.resx
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/GraphObjectRetriever.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/MsAADTool.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ConsoleLogger.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/IConsoleLogger.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/JsonResponse.cs
Some refactors to ConsoleLogger.cs, including passing in the CommandName. 
Catch exceptions that may be thrown while creating a new app registration (for example, permissions ServiceException), then log failure.
Also ensuring that Environment.Exit is called after logging failure, so that the JSON response will be parsed correctly in VS. There were sometimes multiple JSON responses and that caused a parsing error.
> Refactor console logger and catch app provisioning exceptions

- eng/Versions.MSIdentity.props
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/DeveloperCredentials/DeveloperCredentialsReader.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/DeveloperCredentials/MsalTokenCredential.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/TokenCredentialAuthenticationProvider.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.Designer.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.resx
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/GraphObjectRetriever.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/MsAADTool.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/DocumentBuilder.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ConsoleLogger.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/IConsoleLogger.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/JsonResponse.cs
- test/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity.UnitTests.Tests/MsAADToolTests.cs
Cherry-picked #2129 , #2144 , #2149, #2181, #2189 (when it goes in)
> dotnet-msidentity 2.0.1 servicing update

- NuGet.config
- eng/Versions.props
- scripts/install-aspnet-codegenerator.cmd
- tools/dotnet-msidentity/Program.cs
- tools/dotnet-msidentity/ProvisioningToolOptionsBinder.cs
- tools/dotnet-scaffold/Program.cs
bumping System.CommandLine version to 2.0.0-beta4.22613.1.
- added `dotnet-libraries` nuget feed for the latest System.CommandLine package
- added `ProvisioningToolOptionsBinder` for using `SetHandler` instead of `CommandHandler.Create`
- changed all the Options for dotnet-msidentity from new objects to readonly properties.
> bump system commandline version

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/DeveloperCredentials/MsalTokenCredential.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.Designer.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.resx
The tool has been relying on Visual Studio to populate or create the msal.cache file for storing account information, but since VS has transitioned to using WAM it no longer populates the msal.cache file. To work around this, we can make a call to AcquireTokenInteractive when an account is not found, and this will pop up a browser window allowing for picking an account.
> Fix authentication bug (regenerate msal.cache)

- src/Scaffolding/VS.Web.CG.Mvc/Common/CommonCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGeneratorCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/ParameterDefinitions/controller.json
- src/Scaffolding/VS.Web.CG.Mvc/ParameterDefinitions/identity.json
- src/Scaffolding/VS.Web.CG.Mvc/ParameterDefinitions/minimalapi.json
- src/Scaffolding/VS.Web.CG.Mvc/ParameterDefinitions/razorpage.json
- src/Scaffolding/VS.Web.CG.Mvc/ParameterDefinitions/view.json
VS uses Sqlite scenarios by adding the option `useSqLite`. 
- Microsoft.Extensions.CommandLineUtils is not case-friendly. Changed this typo in #2139 so reverting it back now.
- adding `useSqLite` back to parameter defintion json files so its available to display in --help.
> change `useSqlite` to `useSqLite` for VS scenarios

- .editorconfig
- NuGet.config
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/cross/toolchain.cmake
- eng/common/sdk-task.ps1
- eng/common/templates/steps/source-build.yml
- eng/common/tools.ps1
- eng/common/tools.sh
- global.json
- scripts/install-aspnet-codegenerator.cmd
- src/Scaffolding/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs
- src/Scaffolding/VS.Web.CG.Mvc/Common/CommonCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Controller/ControllerWithContextGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGeneratorCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/RazorPage/EFModelBasedRazorPageScaffolder.cs
- src/Scaffolding/VS.Web.CG.Mvc/View/EFModelBasedViewScaffolder.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/EFValidationUtil.cs
- reverting all auto updates for upgrading aspnetcore, efcore, and runtimes changes from 7.0.3 to previous GA versions.
- added `UseSqlite2` with option name `useSqlite`
- for backwards compat. for VS Mac scenarios.
- whitespace fixes based on new .editorconfig file.
- bumping `dotnet-aspnet-codegenerator` version to 7.0.3
> fix --useSqlite for mac scenarios

- eng/common/cross/toolchain.cmake
- eng/common/sdk-task.ps1
- eng/common/templates/steps/source-build.yml
- eng/common/tools.ps1
- eng/common/tools.sh
- scripts/install-aspnet-codegenerator.cmd
- src/Scaffolding/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs
- src/Scaffolding/VS.Web.CG.Mvc/Common/CommonCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Controller/ControllerWithContextGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGeneratorCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/RazorPage/EFModelBasedRazorPageScaffolder.cs
- src/Scaffolding/VS.Web.CG.Mvc/View/EFModelBasedViewScaffolder.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/EFValidationUtil.cs
cherry-picking #2241 for main.
> fix --useSqlite for mac scenarios (#2241)

- scripts/install-aspnet-codegenerator.cmd
- src/Scaffolding/VS.Web.CG.EFCore/ConnectionStringsWriter.cs
- src/Scaffolding/VS.Web.CG.EFCore/DbContextEditorServices.cs
- src/Scaffolding/VS.Web.CG.Mvc/Common/CommonCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGeneratorCommandLineModel.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/SharedConstants.cs
fixes issue with the AddDbContext statement for cosmos db scenarios to have a nullable warning.
- changed `IdentityDbProviders` and `AllDbProviders` to Dictionary<string, DbProvider> from List<string>
> fix AddDbContext statement for cosmos db.

- eng/Versions.props
- scripts/install-aspnet-codegenerator.cmd
- scripts/install-aspnet-codegenerator.sh
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/EFValidationUtil.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/SharedConstants.cs
Addressing #2134 
- changed default EF scenario package validation to checking `Microsoft.EntityFrameworkCore.Tools` than `Microsoft.EntityFrameworkCore.Design`
- Applied all template changes mentioned in the related issue above.
- using `ModelMetadata.Properties` to apply changes to all model properties, will be handy in future scenarios as well.
> minimal api templates update

- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApi.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiNoClass.cshtml
- used VSCode to fix the line endings, very minor fix.
> fix api endpoints line endings to CRLF

- global.json
- scripts/install-aspnet-codegenerator.cmd
- scripts/install-aspnet-codegenerator.sh
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGenerator.cs
`Program.cs` or similar classes with top level statements could not be used as an endpoints class for minimal api endpoints scenario.
- `Program.cs` or other (only 1 allowed currently but scaffolding does not care) can be used an endpoints class.
- Add a new static class at the end of `Program.cs` instead of creating a new file for the class.
- Add necessary usings and `IEndpointRouteBuilder` extension calls.
> fix minimal endpoints in minimal classes (w/ top level statements)

- eng/Versions.props
- global.json
- scripts/install-aspnet-codegenerator.cmd
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApi.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiNoClass.cshtml
been trying to fix this issue and didn't realize the newline characters needed line feed chars
- `\n` --> `\r\n`
- fixes issue with consistent line endings being created in the scaffolded minimal endpoints file
- will be ported over to .NET 6/7 as well.
> edited minimal api templates for correct encoding

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapp_mvc.json
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
Fixing a spacing issue with the MVC code modifier config
> Fix code modifier config

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/ProjectDescription/ProjectDescriptionReader.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/ProjectDescriptions/dotnet_webapp.json
- Fixes the string comparison for the project description, so that the default project description is set correctly.
- In the MVC Web App code modifier config PR, I had deleted the MatchesForProjectType entry for both the Views folder and for Startup.cs from the dotnet-webapp project description
-- We do not want the Views folder to set "Web app" because it should set MVC web app
-- But we do want the Startup.cs check, for .NET Framework projects, so I'm adding that back in
related bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1798608
> Fix string for default Project Description

- eng/Versions.props
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApi.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiNoClass.cshtml
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Microsoft.DotNet.Scaffolding.Shared.csproj
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ModelType.cs
using Humanizer v2.14.1
- will be porting to .NET 6, 7 and will be in the next .NET 8 Preview
> pluralizing model name in minimalapi scenarios using humanizer

- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApi.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiNoClass.cshtml
- fixed for non ef minimal api templates.
- /api/ was not being prefixed in the commented routes
> corrected api route for some minimal api scenarios

- Directory.Build.props
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Microsoft.DotNet.Scaffolding.Shared.csproj
- test/Scaffolding/Shared/MSBuildProjectStrings.cs
- test/Scaffolding/VS.Web.CG.MSBuild.Test/VS.Web.CG.MSBuild.Tests.csproj
- tools/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
mostly minor, will try to add this .NET 7 and 6 servicing to some capacity.
> removed unnecessary assemblies

- Directory.Build.props
- eng/Versions.props
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApi.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiNoClass.cshtml
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Microsoft.DotNet.Scaffolding.Shared.csproj
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ModelType.cs
- test/Directory.Build.props
- test/Scaffolding/Shared/MSBuildProjectStrings.cs
- test/Scaffolding/VS.Web.CG.MSBuild.Test/VS.Web.CG.MSBuild.Tests.csproj
- tools/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
> 7.0.7 servicing

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/DeveloperCredentials/DeveloperCredentialsReader.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/DeveloperCredentials/MsalTokenCredential.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/ProjectDescription/ProjectDescriptionReader.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/ProjectDescriptions/dotnet_webapp.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.Designer.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.resx
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/GraphObjectRetriever.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/MsAADTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/ProvisioningToolOptions.cs
- tools/dotnet-msidentity/Program.cs
Required some different code from main, as a result of a different System.CommandLine version, so making a separate PR instead of cherry-picking from main.
> Add instance parameter to Release/7.0 branch

- eng/Versions.MSIdentity.props
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/ApplicationParameters.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/AzureAdProperties.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorserver.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorwasm.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapp.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.Designer.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.resx
* Updates for CIAM
* Updates for code modifier configs
> CIAM updates (#2422)

- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
fix following templates:
- MinimalApiEf.cshtml
- MinimalApiEfNoClass.cshtml
remove and revert relational extension calls for MapPut and MapDelete methods generated in the endpoints scaffolder.
> fix cosmosdb templates for endpoints scaffolding.

- src/Scaffolding/VS.Web.CG.Mvc/Controller/ControllerWithContextTemplateModel.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Cli.Utils/DotnetCommands.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/General/StringUtil.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Microsoft.DotNet.Scaffolding.Shared.csproj
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectContextHelper.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/StringUtilTests.cs
adding support for netstandard2.0 for MIcrosoft.DotNet.Scaffolding.Shared so it can be consumed by VS.
- removing net6.0, net7.0, net8.0 build
- added ContainsIgnoreCase since netstandard2.0 does not have a string comparison with StringOrdinal parameters.
> supporting netstandard2.0 for Microsoft.DotNet.Scaffolding.Shared

- src/Scaffolding/VS.Web.CG.Templating/RazorTemplating.cs
- src/Scaffolding/VS.Web.CG.Utils/Workspaces/RoslynWorkspace.cs
fixes https://github.com/dotnet/Scaffolding/issues/2508.
- adding the project assembly to the custom roslyn workspace helps detecting blazor built components.
> add project assembly to the workspace to detect BlazorApp objects.

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.Designer.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.resx
Removing references to "Azure AD" for the Microsoft Entra ID rebranding
> Remove references to Azure AD

- src/Scaffolding/VS.Web.CG.Mvc/Blazor/BlazorModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.tt
- Create.tt and Edit.tt template html blazor code based on the input type for properties.
- only certain input types were hardcoded in BlazorModel with no generic fallbacks, added now.
> fixed bug caused by missing input types for blazor CRUD templates

- eng/Versions.props
- scripts/install-aspnet-codegenerator.cmd
- src/Scaffolding/VS.Web.CG.EFCore/DbContextEditorServices.cs
- src/Scaffolding/VS.Web.CG.Templating/RazorTemplating.cs
Razor templating engine was not liking C#12 code (primary constructors)
- Updated CodeAnalysis and Microsoft.AspNetCore.Razor packages
- Updated some roslyn modifiers to handle scenarios with no members (since the constructor is the class declaration).
> updating packages and roslyn code.

- src/Scaffolding/VS.Web.CG.EFCore/ConnectionStringsWriter.cs
- src/Scaffolding/VS.Web.CG.EFCore/DbContextEditorServices.cs
- src/Scaffolding/VS.Web.CG.EFCore/EntityFrameworkServices.cs
- src/Scaffolding/VS.Web.CG.EFCore/IConnectionStringsWriter.cs
- src/Scaffolding/VS.Web.CG.EFCore/IDbContextEditorServices.cs
- src/Scaffolding/VS.Web.CG.EFCore/IEntityFrameworkService.cs
- src/Scaffolding/VS.Web.CG.EFCore/baseline.netcore.json
- src/Scaffolding/VS.Web.CG.Mvc/Common/CommonCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGeneratorCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/ParameterDefinitions/controller.json
- src/Scaffolding/VS.Web.CG.Mvc/ParameterDefinitions/identity.json
- src/Scaffolding/VS.Web.CG.Mvc/ParameterDefinitions/minimalapi.json
- src/Scaffolding/VS.Web.CG.Mvc/ParameterDefinitions/razorpage.json
- src/Scaffolding/VS.Web.CG.Mvc/ParameterDefinitions/view.json
- test/Scaffolding/VS.Web.CG.EFCore.Test/ConnectionStringsWriterTests.cs
- test/Scaffolding/VS.Web.CG.EFCore.Test/DbContextEditorServicesTests.cs
- test/Scaffolding/VS.Web.CG.EFCore.Test/EntityFrameworkServicesTests.cs
addressing #2602
- removed `useSqLite` and `useSqlite` options from the `minimalapi` scaffolder completely.
- minor edits to minimalapi.json to reflect that.
- used feedback from the aforementioned issue.
- this will be for .NET 9 Preview 1+
> removed useSqlite and fixed minimalapi.json

- src/Scaffolding/VS.Web.CG.Mvc/BlazorIdentity/BlazorIdentityGenerator.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/CodeAnalysisHelper.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/General/StringUtil.cs
normalizes line endings to the appropriate ones regardless of OS (Environment.NewLine takes care of it).
> normalize line endings for blazor-identity changes

- azure-pipelines-pr.yml
This is just the first step of getting the build pipelines ready for 1ES pipeline template migration. Here we create a copy of the build pipeline that will be used for public/pr builds. Modifications to the file after copy are limited to removing conditionals that were relevant only to internal/ci builds. For review purposes its better to compare this new file with azure-pipelines.yml since its treated as a new file here.
Note that the PR build for this PR will still run against the old yml file. I'll swap over the public build to the new file once this PR completes.
> Fork build pipeline for pr/ci

- azure-pipelines-pr.yml
Quick fix from #2665 - I removed the trigger altogether, which actually made CI _always_ run. On second thought I'll just put it back as it was.
> Restore CI trigger for PR pipeline

- start-code.cmd
- startvs.cmd
Pulls in a couple of scripts (slightly modified) we were using in [Aspire](https://github.com/dotnet/aspire) to help with the dev time experience.
Background:
- `.\build.cmd` will download and install the version of the .NET SDK specified in global.json to a local folder (the `.dotnet` folder). It then uses that SDK to build
- But if you open VS or VS Code directly, it doesn't know about that local version of the .NET SDK and will just use what is installed globally
- The new `.\startvs.cmd` and `.\start-code.cmd` will set the `DOTNET_ROOT` environment variable to the local installation of the .NET SDK before launching VS or VS Code so it'll be properly located
A couple notes:
- If `.sln` files aren't already associated with a particular instance of VS, the first launch of `.\startvs.cmd` …
> Add helpful dev-time scripts

- All.sln
- Directory.Build.props
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Microsoft.DotNet.MSIdentity.csproj
- src/Shared/Microsoft.DotNet.Scaffolding.ComponentModel/Microsoft.DotNet.Scaffolding.ComponentModel.csproj
- src/Shared/Microsoft.DotNet.Scaffolding.Helpers/Microsoft.DotNet.Scaffolding.Helpers.csproj
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Microsoft.DotNet.Scaffolding.Shared.csproj
- test/Shared/Microsoft.DotNet.Scaffolding.ComponentModel.Tests/Microsoft.DotNet.Scaffolding.ComponentModel.Tests.csproj
- tools/dotnet-msidentity/dotnet-msidentity.csproj
- tools/dotnet-scaffold/dotnet-scaffold.csproj
We have several different LangVersions specified in different places and overridden in others (including defaulting to an old old version 7.3 in D.B.props). Just a quick attempt to consolidate on `latest`, which appears to work for all projects currently.
> Consolidate LangVersion on 'latest'

- All.sln
- eng/Versions.Scaffold.AspNet.props
- eng/Versions.Scaffold.Aspire.props
- src/Shared/Microsoft.DotNet.Scaffolding.ComponentModel/CommandInfo.cs
- src/Shared/Microsoft.DotNet.Scaffolding.ComponentModel/Parameter.cs
- test/Shared/Microsoft.DotNet.Scaffolding.ComponentModel.Tests/CommandInfoTests.cs
- tools/dotnet-scaffold-aspire/AnsiConsoleLogger.cs
- tools/dotnet-scaffold-aspire/AppBuilder/TypeRegistrar.cs
- tools/dotnet-scaffold-aspire/AppBuilder/TypeResolver.cs
- tools/dotnet-scaffold-aspire/Commands/GetCommands.cs
- tools/dotnet-scaffold-aspire/Commands/RedisCommand.cs
- tools/dotnet-scaffold-aspire/Helpers/SpectreExtensions.cs
- tools/dotnet-scaffold-aspire/Program.cs
- tools/dotnet-scaffold-aspire/dotnet-scaffold-aspire.csproj
- tools/dotnet-scaffold-aspnet/AnsiConsoleLogger.cs
- tools/dotnet-scaffold-aspnet/AppBuilder/TypeRegistrar.cs
- tools/dotnet-scaffold-aspnet/AppBuilder/TypeResolver.cs
- tools/dotnet-scaffold-aspnet/Commands/AreaCommand.cs
- tools/dotnet-scaffold-aspnet/Commands/GetCommands.cs
- tools/dotnet-scaffold-aspnet/Commands/MinimalApi/MinimalApiCommand.cs
- tools/dotnet-scaffold-aspnet/Commands/MinimalApi/MinimalApiModel.cs
- tools/dotnet-scaffold-aspnet/Helpers/SpectreExtensions.cs
- tools/dotnet-scaffold-aspnet/Program.cs
- tools/dotnet-scaffold-aspnet/dotnet-scaffold-aspnet.csproj
adding mostly hollow dotnet-scaffold-aspire and dotnet-scaffold-aspnet
- there is duplicate code for Specter.Console helpers. Currently do not want to add a dependency of Spectre.Console onto the Shared helper projects (Will abstract this work to a Spectre.Console.Helper project).
- Mostly hollow cmdline apps that execute 'get-commands' and will be filled out soon.
> adding 'dotnet-scaffold-aspire' and 'dotnet-scaffold-aspnet'

- scripts/install-scaffold-aspire.cmd
- scripts/install-scaffold-aspnet.cmd
- src/Shared/Microsoft.DotNet.Scaffolding.Helpers/Services/DotNetToolService.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Helpers/Services/IDotNetToolService.cs
- tools/dotnet-scaffold/Command/ScaffoldCommand.cs
- tools/dotnet-scaffold/Flow/FlowContextProperties.cs
- tools/dotnet-scaffold/Flow/FlowExtensions.cs
- tools/dotnet-scaffold/Flow/Steps/CategoryDiscovery.cs
- tools/dotnet-scaffold/Flow/Steps/CategoryPickerFlowStep.cs
- tools/dotnet-scaffold/Flow/Steps/CommandExecuteFlowStep.cs
- tools/dotnet-scaffold/Flow/Steps/StartupFlowStep.cs
- tools/dotnet-scaffold/Services/FirstPartyComponentInitializer.cs
- added `CategoryPickerFlowStep`
- Each `CommandInfo` has a `DisplayCategory` property. These are going to be presented in a selection flow before the project picker.
- Then all applicable `CommandInfo`s are presented
- Only applicable in the interactive mode
- The order of steps **was** : StartupFlowStep --> SourceProjectFlowStep --> CommandPickerFlowStep --> CommandExecuteFlowStep
- The order of steps **is** : StartupFlowStep --> CategoryPickerFlowStep --> SourceProjectFlowStep --> CommandPickerFlowStep --> CommandExecuteFlowStep
- added `IDotNetToolService.InstallDotNetTool`
- install a dotnet tool globally using `dotnet tool install -g`
Sample gif (ignore the debugger and Redis scaffolder details)
> added CategoryPickerFlowStep and FirstPartComponentInitializer

- tools/dotnet-scaffold-aspire/Commands/CachingCommand.cs
- tools/dotnet-scaffold-aspire/Commands/DatabaseCommand.cs
- tools/dotnet-scaffold-aspire/Commands/GetCommands.cs
- tools/dotnet-scaffold-aspire/Commands/StorageCommand.cs
My comment on a prior PR (https://github.com/dotnet/Scaffolding/pull/2744#discussion_r1600715024) was too brief and didn't convey what I intended. So just a quick PR to make the full change here. We can get the PM/docs folks later on whether it should be `App host` (like in the docs) or `AppHost` (like in the project name) or what, but it should probably have both parts (see [Aspire docs](https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/app-host-overview#app-host-project) for reference).
> Change AppHost verbiage

- tools/dotnet-scaffold-aspire/Commands/DatabaseCommand.cs
Looks like a simple copy/paste error here - seems to be using the AppHost dictionary for the ApiService reference install.
> Fix database apiservice package add

- src/Shared/Microsoft.DotNet.Scaffolding.Helpers/Extensions/StringExtensions.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Helpers/Roslyn/ProjectModifier.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Helpers/Services/CodeService.cs
- tools/dotnet-scaffold-aspire/Commands/CachingCommand.cs
- tools/dotnet-scaffold-aspire/Commands/CodeModificationConfigs/Caching/redis-apphost.json
- tools/dotnet-scaffold-aspire/Commands/CodeModificationConfigs/Caching/redis-webapp.json
- tools/dotnet-scaffold-aspire/Program.cs
- tools/dotnet-scaffold-aspire/dotnet-scaffold-aspire.csproj
- tools/dotnet-scaffold/Command/ScaffoldCommand.cs
- tools/dotnet-scaffold/Flow/Steps/CommandExecuteFlowStep.cs
- tools/dotnet-scaffold/Program.cs
adding to `dotnet-scaffold-aspire caching --type redis` scenario.
- added `UpdateAppHostAsync` and `UpdateWebAppAsync` to `CachingCommand.ExecuteAsync`
- flow for code modification is as follows in the above methods:
1. Get `CodeModifierConfig` from `ProjectModifierHelper.GetCodeModifierConfig`
2. Initialize `ICodeService` with a given project path (in `IAppSettings`)
3. Initialize `CodeChangeOptions`
4. Initialize `ProjectModifier` and then call `RunAsync`
- added `MSBuildLocator.RegisterDefaults()` before any roslyn workspace setup (when using `CodeService`. Missing MSBuild assemblies otherwise and exceptions are thrown when loading the `MSBuildWorkspace`. Currently a controlled initialization before any roslyn modifications.
- removed unnecessary `CachingCommand.InitializeCommand()`
- …
> add code modification when running 'caching --type redis' 

- src/Shared/Microsoft.DotNet.Scaffolding.Helpers/General/DotnetCommands.cs
- tools/dotnet-scaffold-aspire/Commands/CachingCommand.cs
- tools/dotnet-scaffold-aspire/Commands/DatabaseCommand.cs
- tools/dotnet-scaffold-aspire/Commands/GetCommands.cs
- tools/dotnet-scaffold-aspire/Commands/StorageCommand.cs
- tools/dotnet-scaffold/AppBuilder/ScaffoldCommandAppBuilder.cs
- tools/dotnet-scaffold/Command/ScaffoldCommand.cs
- tools/dotnet-scaffold/Flow/Steps/CommandExecuteFlowStep.cs
- tools/dotnet-scaffold/Flow/Steps/ParameterDiscovery.cs
- More cleanup on App host project command argument and its naming relative to the other project argument.
- Consolidating the web/api project command arguments into one Project command argument. It really doesn't matter in Aspire what type of thing it is - it could be web, web api, worker, even a WPF app or something. I started to just call it `.NET Project` in the display name but that felt _too_ generic. Went with Brady's suggestion of Web or worker for now.
- Missed one place when changing the version from 0.1.0 back to 9.0.0
- Turned off showing the selected options on launch at least for now since we're rarely doing it and it just clutters the demo
- Changed the way we displayed the output from the commands so that we always display both stdout/stderr regardless of exit code (there …
> Various quick tweaks

- src/Shared/Microsoft.DotNet.Scaffolding.Helpers/General/DotnetCliRunner.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Helpers/General/DotnetCommands.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Helpers/Roslyn/ProjectModifier.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Helpers/Services/DotNetToolService.cs
- tools/dotnet-scaffold-aspire/Commands/CachingCommand.cs
- tools/dotnet-scaffold/Flow/Steps/CommandExecuteFlowStep.cs
- Changes the output from the dependent tools to be displayed as it happens rather than all at once when it exits.
- Tweaks the output of the aspire tool slightly just to clean things up a bit
This is what it looks like at the end now (it has the status spinner thing while it's working, and these come in one at a time now):
> Stream output from tools

- tools/dotnet-scaffold/Flow/Steps/CommandExecuteFlowStep.cs
Per the [docs](https://spectreconsole.net/markup):
When working with interpolated strings, you can use the `MarkupInterpolated` and `MarkupLineInterpolated` methods to automatically escape the values in the interpolated string "holes".
The output from the tools often contains `[...]` sequences, which throws off the markup. This escapes that output.
> Escape tool output

- src/Shared/Microsoft.DotNet.Scaffolding.ComponentModel/Parameter.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Helpers/General/DotnetCommands.cs
- tools/dotnet-scaffold-aspire/Commands/CachingCommand.cs
- tools/dotnet-scaffold-aspire/Commands/DatabaseCommand.cs
- tools/dotnet-scaffold-aspire/Commands/GetCommands.cs
- tools/dotnet-scaffold-aspire/Commands/StorageCommand.cs
- tools/dotnet-scaffold/Flow/Steps/ParameterDiscovery.cs
- Adds a yes/no picker to keep in the "flow" of moving up/down through the options that we have for all the other selections rather than having to move to the y/n keys to answer the question with a confirmation prompt.
- Uses the yes/no picker to add a `--prerelease` option for each of the aspire commands that determines if we install the latest prerelease package (if you say Yes) or the latest release package (if you say No).
> Add --prerelease option

- azure-pipelines.yml
The `-pt` images were removed once they were redundant with the base images. We should no longer reference them. This change was already made in main but needed to be made in servicing branches as well.
> Remove -pt images from 8.0 branch

- azure-pipelines.yml
The `-pt` images were removed once they were redundant with the base images. We should no longer reference them. This change was already made in main but needed to be made in servicing branches as well.
> Remove -pt images from 6.0 branch

- azure-pipelines.yml
The `-pt` images were removed once they were redundant with the base images. We should no longer reference them. This change was already made in main but needed to be made in servicing branches as well.
> Remove -pt images from 7.0 branch

- azure-pipelines-pr.yml
MacOS 11 was EOL in September 2023, s we should probably move to newer supported machines.
> Change PR builds to use macos-13 image

- src/dotnet-scaffolding/dotnet-scaffold-aspire/dotnet-scaffold-aspire.csproj
- src/dotnet-scaffolding/dotnet-scaffold/dotnet-scaffold.csproj
This gets around Spectre.Console not being strong named while still keeping our stuff strong named. Since strong naming doesn't provide any actual value in .NET (Core/5+) and we don't ship this for .NET Framework, there shouldn't be any harm in ignoring these warnings.
> Bring back strong naming for dotnet-scaffolding packages

- src/dotnet-scaffolding/dotnet-scaffold-aspire/Commands/DatabaseCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspire/dotnet-scaffold-aspire.csproj
we missed adding the 'NewDbContext' for the `dotnet scaffold aspire database` scenarios in the database scenario [PR](https://github.com/dotnet/Scaffolding/pull/2767)
> adding new DbContext in aspire database scenarios

- src/dotnet-scaffolding/dotnet-scaffold/Services/AnsiConsoleLogger.cs
Spectre.Console has [logic in it](https://github.com/spectreconsole/spectre.console/blob/5c87d7fa04424faadf54686f92709af277ec28b3/src/Spectre.Console/AnsiConsoleFactory.cs#L31) to detect the output encoding of the shell being used, but we had a line in AnsiConsoleLogger that always overrode that to make it be Utf8. That worked ok in a lot of shells that were Utf8 natively (like powershell core) but some (e.g. Windows Powershell) did not have Utf8 enabled by default and this led to rendering bugs like this:
Removing this one line appears to allow the default detection through
> Remove encoding override

- scripts/install-scaffold-aspire.sh
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Helpers/General/StringUtil.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/ParameterDiscovery.cs
Duplicate project files were being displayed when using `InteractivePickerType.ProjectPicker`
- project files discovered rom `.sln` were not being normalized (based on platform) and duplicates were being added.
- fixed scripts for installing tools on macOS and linux.
> fix project discovery (for macOS and linux)

- eng/Versions.MSIdentity.props
Thes are already set in Versions.props: 
https://github.com/dotnet/Scaffolding/blob/aa14b4c5fa67c21cd1093d242cd7a537a5317981/eng/Versions.props#L3-L7
which is imported first into the same projects as part of the default arcade imports.. Essentially the things in this file (Versions.MSIdentity.props) just override a few things in Versions.props.
Just something small I noticed while preparing for Centralized Package Management
> Remove redundant msbuild props

- eng/Versions.props
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Microsoft.DotNet.MSIdentity.csproj
A few small tweaks:
- Update the `Microsoft.CodeAnalysis.*` references to `4.10.0` final which was just released yesterday
- Consolidate `Microsoft.CodeAnalysis.*` versioning references so all use the same version and can be updated together. Note that I left them as separate entries (for now at least)
- Remove some unused package version information in `Versions.props`
- Updated one reference in `src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Microsoft.DotNet.MSIdentity.csproj` that was a dependency of the `Microsoft.CodeAnalysis.*` packages
- Cleaned up the `src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Microsoft.DotNet.MSIdentity.csproj` a bit to separate out the package refs, project refs, folder includes, etc.
> Update CodeAnalysis packages, some cleanup

- Directory.Packages.props
- NuGet.config
- eng/Versions.props
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Microsoft.DotNet.MSIdentity.csproj
- src/MSIdentityScaffolding/dotnet-msidentity/dotnet-msidentity.csproj
- src/Scaffolding/VS.Web.CG.Core/VS.Web.CG.Core.csproj
- src/Scaffolding/VS.Web.CG.Design/Shared.props
- src/Scaffolding/VS.Web.CG.EFCore/VS.Web.CG.EFCore.csproj
- src/Scaffolding/VS.Web.CG.Msbuild/VS.Web.CG.Msbuild.csproj
- src/Scaffolding/VS.Web.CG.Templating/VS.Web.CG.Templating.csproj
- src/Scaffolding/VS.Web.CG.Utils/VS.Web.CG.Utils.csproj
- src/Scaffolding/VS.Web.CG/VS.Web.CG.csproj
- src/Scaffolding/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Microsoft.DotNet.Scaffolding.Shared.csproj
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Helpers/Microsoft.DotNet.Scaffolding.Helpers.csproj
- src/dotnet-scaffolding/dotnet-scaffold-aspire/dotnet-scaffold-aspire.csproj
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/dotnet-scaffold-aspnet.csproj
- src/dotnet-scaffolding/dotnet-scaffold/dotnet-scaffold.csproj
- test/Directory.Build.props
- test/Scaffolding/E2E_Test/E2E_Test.Tests.csproj
- test/Scaffolding/Ext.ProjectModel.Tests/Ext.ProjectModel.Tests.csproj
- test/Scaffolding/TestApps/ModelTypesLocatorTestWebApp/ModelTypesLocatorTestWebApp.csproj
- test/Scaffolding/VS.Web.CG.EFCore.Test/VS.Web.CG.EFCore.Tests.csproj
- test/Scaffolding/VS.Web.CG.MSBuild.Test/VS.Web.CG.MSBuild.Tests.csproj
- test/Scaffolding/VS.Web.CG.Mvc.Test/VS.Web.CG.Mvc.Tests.csproj
- test/Scaffolding/VS.Web.CG.Sources.Test/VS.Web.CG.Sources.Tests.csproj
- test/Scaffolding/VS.Web.CG.Templating.Test/VS.Web.CG.Templating.Tests.csproj
- test/Scaffolding/VS.Web.CG.Tools.Test/VS.Web.CG.Tools.Tests.csproj
This started off as updating the versions of some dependencies from .NET 9 Preview 1 to .NET 9 Preview 5 because we were going to add a few more in an upcoming PR and wanted to add the latest. But doing so caused version conflicts and that seemed like a good time to go ahead and get CPM out of the way.
> Implement central package management

- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/DeletePageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/DetailsPageModel.cshtml
Refactored the `OnGetAsync` method to simplify control flow by removing the unnecessary else statement and moving the `return Page();` inside the conditional check where record is not null. This enhances readability and reduces nesting.
> Bootstrap5: Refactor unnecessary else block

- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/API/ApiControllerEmptyCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/Blazor/BlazorEmptyCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/GetCommands.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/MVC/MvcControllerEmptyCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/MVC/RazorViewEmptyCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/Razor Pages/RazorPageEmptyCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Program.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CategoryDiscovery.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CommandDiscovery.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/ParameterDiscovery.cs
Commands added for `dotnet-scaffold-aspnet` : `apicontroller-empty`, `mvccontroller-empty`, `razorpage-empty`, `razorview-empty`, `blazor-empty`
- only `--name` and `--project` options for all the new empty scaffolders
- `--actions` option for `mvccontroller-empty` and `apicontroller-empty` to enable read/write actions controller option
- all new commands into their respective `dotnet new` templates.
- sorting display options in `CommandDiscovery` and `CategoryDiscovery`
> adding empty scaffolders for dotnet-scaffold-aspnet

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Helpers/Services/CodeService.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Helpers/Services/ICodeService.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/ParameterDiscovery.cs
was causing an issue where the call `MSBuildWorkspace.OpenProjectAsync` was blocking the main thread and the AnsiConsole.Status progress UI was dropped. Switching to `AnsiConsole.Status.StartAsync` to allow async Tasks. Fixed the issue!
> switch AnsiConsole.Status to calling StartAsync instead of Start

- src/Scaffolding/VS.Web.CG.EFCore/DbContextEditorServices.cs
- src/Scaffolding/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs
- src/Scaffolding/VS.Web.CG.EFCore/EntityFrameworkServices.cs
- src/Scaffolding/VS.Web.CG.EFCore/IEntityFrameworkService.cs
- src/Scaffolding/VS.Web.CG.Mvc/Blazor/BlazorWebCRUDGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Blazor/blazorWebCrudChanges.json
- src/Scaffolding/VS.Web.CG.Mvc/ModelMetadataUtilities.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.tt
- test/Scaffolding/VS.Web.CG.Mvc.Test/BlazorWebCRUDGeneratorTests.cs
- test/Scaffolding/VS.Web.CG.Mvc.Test/ModelMetadataUtilitiesTest.cs
- updated `blazorWebCrudChanges.json` to include some additional code changes.
- updated all blazor crud T4 templates to use `IDbContextFactory` instead of `DbContext`
- updated `IEntityFrameworkService.cs` and relating files to allow optional use of `AddDbContextFactory` instead of `AddDbContext`
- added use of `ApplyTextReplacements` to `BlazorWebCRUDGenerator.cs` to allow 'Replacements' in the code modifier configs.
- removed `ModifyProgramCsTests` since the test is invalid due to above change.
> added code changes in json config and using IDbContextFactory now

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Helpers/General/DbContextHelper.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Helpers/General/DbContextProperties.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspire/Commands/DatabaseCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspire/Commands/GetCommands.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/API/MinimalApi/MinimalApiCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/Blazor/BlazorCrud/BlazorCrudCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/Common/CommandHelpers.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/Common/DbContextInfo.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Helpers/AspNetDbContextHelper.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Helpers/PackageConstants.cs
added `AddConnectionString` to `DbContextHelper` and calling it in `CreateDbContext`
- find `appsettings.json` file
- parse it to a `JObject`
- find/create a `ConnectionStrings` node
- add the new connection string for the newly created DbContext
other minor changes :
- `DatabaseCommand` now actually configuring for the correct `--type` parameter.
- initialize `DbContextProperties` to include new property `NewDbConnectionString`
- remove unnecessary `CommandHelpers.AddDbContext` method and switch `MinimalApiCommand` use of it to `DbContextInfo.AddDbContext`
- removed unnecessary properties from `PackageConstants.cs`
-
> adding a connection string in new DbContext scenarios

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/Scaffolding/VS.Web.CG.EFCore/DbContextEditorServices.cs
- src/Scaffolding/VS.Web.CG.Mvc/Blazor/BlazorWebCRUDGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/BlazorIdentity/BlazorIdentityGenerator.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/DocumentBuilder.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
fixing an issue where file changes were not being persisted without using IFileSystem (for VS scenarios)
- due to file changes being tracked by `MessageOrchestrator.cs` and sent to VS using `SendFileSystemChangeInformation`
also fixed an issue where `useDbFactory` was not being passed to the methods creating the `AddDb` strings in `DbContextEditorServices.cs`
- will be porting this to release/9.0-preview6 and release/8.0
> using IFileSystem instead of System.IO.File

- eng/Versions.props
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/DeveloperCredentials/MsalTokenCredential.cs
- src/dotnet-scaffolding/Directory.Packages.props
- splitting up CPM, one for all projects in `src\dotnet-scaffolding` and one for the rest.
- updated all dependencies to .NET 9 Preview 6.
> add separate CPM for 'dotnet-scaffolding'

- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/Blazor/BlazorEmptyCommand.cs
- Component names cannot start with a lower-case ascii character. (causes a build failure `RZ10011`)
- using `CultureInfo.CurrentCulture.TextInfo.ToTitleCase` to ensure a capitalized first character (lowercase for the rest of the word).
- only affects the ascii letters
- names starting with numbers/special characters are unaffected and do not cause build errors.
> validating  empty razor component name with 'ToTitleCase'

- src/dotnet-scaffolding/dotnet-scaffold-aspnet/AnsiConsoleLogger.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/API/MinimalApi/MinimalApiCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/Blazor/BlazorCrud/BlazorCrudCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/Common/ClassAnalyzers.cs
added `ClassAnalyzers.ValidateModelForCrudScaffolders`
- check if any `ModelProperties` were populated
- check if a primary key was initialized
- fixed writing to AnsiConsole in `dotnet-scaffold-aspnet\AnsiConsoleLogger`
- tested with MinimalApiCommand and BlazorCrudCommand
> validating `ModelInfo` for required CRUD properties

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Helpers/Services/DotNetToolService.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/FirstPartyComponentInitializer.cs
- edited `List<string> _firstPartyTools` to have the correct tool names
- checking for the correct property in `DotnetToolService.GetCommands`
> fixing `FirstPartyComponentInitializer`

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Helpers/Services/DotNetToolService.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Helpers/Services/IDotNetToolService.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CategoryPickerFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CommandPickerFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/ComponentDiscovery.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/FirstPartyComponentInitializer.cs
surfacing `IDotNetToolService.GetDotNetTools` instead of being a private helper and removing `GlobalDotNetTools`
- using this when checking for installed 1st party tools instead of invoking `GlobalDotNetTools`
- added a `bool refresh` parameter and using it in `FirstPartyComponentInitializer`
- fixes the scenario where commands are not found on the first run. `GlobalDotNetTools` was getting initialized with all the dotnet tools before our installation and this property was not refreshed after the new 1st party tools get installed.
> not invoking 'GlobalDotNetTools' before installing 1st party tools

- src/Scaffolding/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs
Might fix #1765
The method `TryCreateContextUsingAppCode` accepts a `dbContextType` and a `startupType`, but the calling code doesn't pass any startup type, instead it passes the `dbContextType` twice.
I believe this might be the reason why scaffolding with `dotnet aspnet-codegenerator` fails when your `DbContext` resides in a class library (see long list of victims in #1765).
> Fix incorrect usage of TryCreateContextUsingAppCode

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Helpers/Services/CodeService.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Helpers/Services/DotNetToolService.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Helpers/Services/IAppSettings.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Helpers/Steps/AddPackagesStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/FirstPartyComponentInitializer.cs
minor fixes
- `FirstPartyComponentInitializer` was checking for installed dotnet tools with case sensitivity. We were reinstalling the 1st party tools every time, fixes that issue.
- adding a `DotNetToolInfo.CommandName` check in `DotNetToolService.GetCommands` alongside the `DotNetToolInfo.PackageName` check
- added `MsBuildInitializer.Initialize()` to `AddPackagesStep` (each step that needs MSBuild initialization should do it)
- added `EnsureInitialized()` to `CodeService` implementation. Making sure the initialization is thread safe.
> fix FirstPartyComponentInitializer and DotNetToolService

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Builder/IScaffoldBuilder.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Builder/IScaffoldRunner.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Builder/IScaffoldRunnerBuilder.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Builder/ScaffoldBuilder.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Builder/ScaffoldRunnerBuilder.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Hosting/Host.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Properties/AssemblyInfo.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Scaffolders/IScaffolder.cs
Small follow up to #2875 
- Adds some doc comments
- Deletes some unused code and unused usings
- Tweaks the way scaffolder name is stored so it can more reliably be used as a command line command (e.g. can't contain spaces).
> Small builder cleanup/docs changes

- src/dotnet-scaffolding/dotnet-scaffold/AppBuilder/ScaffoldCommandAppBuilder.cs
- src/dotnet-scaffolding/dotnet-scaffold/Command/ToolInstallCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold/Command/ToolInstallSettings.cs
- src/dotnet-scaffolding/dotnet-scaffold/Command/ToolListCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold/Command/ToolListSettings.cs
- src/dotnet-scaffolding/dotnet-scaffold/Command/ToolSettings.cs
- src/dotnet-scaffolding/dotnet-scaffold/Command/ToolUninstallCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold/Command/ToolUninstallSettings.cs
- src/dotnet-scaffolding/dotnet-scaffold/Models/ScaffoldManifest.cs
- src/dotnet-scaffolding/dotnet-scaffold/Models/ScaffoldTool.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/DotNetToolService.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/FirstPartyComponentInitializer.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/IDotNetToolService.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/IToolManager.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/IToolManifestService.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/ToolManager.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/ToolManifestService.cs
These commands are standalone right now since they aren't plugged into anything, but it lays the foundation for being able to use them elsewhere.
These commands are implemented:
`dotnet-scaffold tool install [name]`
`dotnet-scaffold tool list`
`dotnet-scaffold tool uninstall [name]`
Install will (if required) install the tool globally and add it to the manifest. uninstall will remove it from the manifest and uninstall it globally. List prints a table that just shows the name for now, But I assume we'll add more information.
Under the hood, `IToolManager` and `IManifestService` can be used in the FirstPartyToolInitializer to do the work it needs to do there when we're ready to plug that in. Then `IManifestService` can be used to get the list of registered tools to call get-commands on …
> Add tool commands

- src/Scaffolding/VS.Web.CG.Mvc/BlazorIdentity/BlazorIdentityGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/BlazorIdentity/blazorIdentityChanges.json
- not adding blazor identity blazor files when they are already on disk
- adding `CheckBlocks` (property for checking statements and if found, skip the code change) for some blazor identity code changes.
> only adding blazor identity when they are not on disk

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/CodeModificationStep.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.TextTemplating/Constants.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.TextTemplating/DbContext/DbContextProperties.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.TextTemplating/ScaffolderBuilderExtensions.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.TextTemplating/TextTemplatingProperty.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.TextTemplating/TextTemplatingStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Extensions/BlazorCrudScaffolderBuilderExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Extensions/MinimalApiScaffolderBuilderExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Extensions/ScaffolderBuilderExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Helpers/BlazorCrudHelper.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Helpers/MinimalApiHelper.cs
- added `TextTemplatingProperty` and using an `IEnumerable<TextTemplatingProperty>` in `TextTemplatingStep` instead of having a single instance of these properties in the `TextTemplatingStep`.
- moved logic for finding the `.tt` templates out of the `*BuilderExtensions.cs` to Helper classes.
> adding support for multi template execution in a single step.

- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Index.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Index.tt
extra '.' was being added to the `dbContextNamespace`
> remove extra '.' for Index.tt template

- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Create.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Create.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Delete.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Delete.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Details.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Details.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Edit.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Edit.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Index.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Index.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/MinimalApi/MinimalApiEf.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/MinimalApi/MinimalApiEf.tt
`blazor-crud` templates : 
- added `dbContextFullName` and using it correctly (was missing a '.' after last change but the '.' would cause errors elsewhere in the templates).
`minimalapi` templates : 
- fix the check for `cosmos-efcore` db provider type.
> T4 template fixes

- src/Scaffolding/VS.Web.CG.Mvc/BlazorIdentity/BlazorIdentityCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/ParameterDefinitions/blazor-identity.json
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap4/CreatePageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap4/EditPageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/CreatePageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/EditPageModel.cshtml
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Create.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Create.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Delete.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Delete.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Details.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Details.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Edit.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Edit.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Index.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Index.tt
Addressing issues from #2743
- [extra semicolon ](https://github.com/dotnet/Scaffolding/issues/2743#issue-2293454096)in `builder.Services.AddQuickGridEntityFrameworkAdapter();` : [fixed](https://github.com/dotnet/Scaffolding/pull/2835) earlier
- fixed directive orders and change properties + methods to [private](https://github.com/dotnet/Scaffolding/issues/2743#issuecomment-2145808254) [issue](https://github.com/dotnet/Scaffolding/issues/2743#issuecomment-2114978607): fixed
- nit issues : [1](https://github.com/dotnet/Scaffolding/issues/2743#issuecomment-2114992611), [2](https://github.com/dotnet/Scaffolding/issues/2743#issuecomment-2115098170), [3](https://github.com/dotnet/Scaffolding/issues/2743#issuecomment-2173418176), [4](https://github.com/dotnet/Scaffolding/issues/2743#issuecomment …
> blazor-crud scaffolder minor fixes

- eng/Versions.DotNetScaffold.props
- eng/Versions.props
- src/dotnet-scaffolding/Directory.Build.props
- test/Scaffolding/VS.Web.CG.Core.Test/CodeGeneratorDescriptorTests.cs
- split versioning for `src\dotnet-scaffolding` since other scaffolding versinos are going to be `9.0-rc.1` instead of `9.0-preview.8`
- bump dependencies 9.0-rc1
- skipping an unrelated test, added a TODO to fix/investigate.
> update dependencies and separate versioning for dotnet-scaffolding

- src/dotnet-scaffolding/dotnet-scaffold-aspnet/CodeModificationConfigs/blazorIdentityChanges.json
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/CodeModificationConfigs/blazorWebCrudChanges.json
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/CodeModificationConfigs/efControllerChanges.json
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/CodeModificationConfigs/minimalApiChanges.json
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/CodeModificationConfigs/razorPagesChanges.json
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Common/PackageConstants.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Helpers/AspNetDbContextHelper.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/MinimalApi/MinimalApiEf.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/MinimalApi/MinimalApiEf.tt
- fix an added statement in EF scenario for `postgres-efcore` db provider type.
- `UsePostgres()` --> `UseNpgsql()`
- `UsePostgres` is used in Aspire scenarios but not in ASPNET.Core scenarios
- fix `UseCosmos(connectionString)` call as this is not supported anymore. For the `cosmos-efcore` db provider, adding `UseCosmos(connectionString, DB_NAME)` (formatting the DbContext name in this statement) instead. It is backwards-compat for .net8.0 scenarios as well.
- fix spacing issue for minimalapi w/ EF template, extra 4 spaces at the start of the `group.MapPut..` statement.
> fix postgres UseDb method name + UseDb method invocation statement

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/CodeModification/ProjectModifier.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/Helpers/ProjectModifierHelper.cs
- `ProjectModifierHelper.ModifyDocumentTextAsync` has incorrect logic
- `fileDoc` could have been of type `Document` or its base class `TextDocument`, however the logic was only handling `TextDocument`
- added logic for handling `Document` types
- minor change in log message when an exception is caught it `ProjectModifier.HandleCodeFileAsync`
> fix ModifyDocumentTextAsync

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/ComponentModel/DotnetToolInfo.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/EmptyControllerScaffolderStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Command/ToolInstallCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold/Command/ToolInstallSettings.cs
- src/dotnet-scaffolding/dotnet-scaffold/Command/ToolUninstallCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold/Command/ToolUninstallSettings.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CategoryPickerFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CommandExecuteFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CommandPickerFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/DotNetToolService.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/IDotNetToolService.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/IToolManager.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/ToolManager.cs
Currently dotnet-scaffold only deals with global tools"
- It will install the 1st party tools (`dotnet-scaffold-aspire` and `dotnet-scaffold-aspnet`) globally
- Also populates the list of commands and category by iterating over all global tools. 
Changing this to installing 1st party tools as 'local' tools:
- Allow repos to control the version of these 1st party tools 
- These 1st party tools are only relevant in the context of the repo/project so global tool list will stay clean
- When populating the list of commands, search local tools first, and then global tools. For duplicates, only track and invoke the local one.
changes description:
- most changes are in `DotNetToolService.GetCommands`
- for invoking local tools, we have to invoke the `dotnet` command, for eg. `dotnet …
> installing and prioritizing local tools for dotnet-scaffold

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Internal/CliHelpers/DotnetCliRunner.cs
When using `DotNetCliRunner.ExecuteWithCallbacks` or `DotNetCliRunner.ExecuteAndCaptureOutput` either in dotnet-scaffold or elsewhere, `Process.Start()` can throw on a myriad of reasons. 
- Found this when had another dotnet global tool installed `Sarif.PatternMatcher.Cli` and this method would throw and exit when trying to start the tool's process. 
- We should catch the exception and continue execution
- `dotnet-scaffold` would fail on getting all the commands due to this failure instead of returning all found commands.
> fix `DotnetCliRunner`

- scripts/install-aspnet-codegenerator.cmd
- src/Scaffolding/VS.Web.CG.Mvc/BlazorIdentity/blazorIdentityChanges.json
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
- 'CheckBlock' property was not being checked before replacing a snippet was causing duplicated (in `ProjectModifierHelper.ModifyDocumentText`)
- added some 'CheckBlock's
> minor Blazor Identity fixes

- src/Scaffolding/VS.Web.CG.Mvc/BlazorIdentity/BlazorIdentityGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/BlazorIdentity/BlazorIdentityHelper.cs
Context : Currently, scaffolding does not support updating/removing existing statements in a C# class and chosing not to add additional duplicate references with the newly created names. This causes more build errors and confusion. Updating using roslyn required more complicated logic and chosing to not add it for the older scaffolders. Therefore, just adding a readme to clear up the confusion with very simple, obvious workarounds.
For Blazor Identity scenarios, there was some confusion regarding the identity specific statements/calls in the Program.cs file. If blazor-identity was scaffolded on top an app with preexisting identity:
- the `IdentityUser` class could be incorrect (old one) if a new one was created.
- the `DbContextClass` class could be incorrect (old one) if a new one was …
> adding a readme for blazor identity for scenario specific information.

- eng/Versions.DotNetScaffold.props
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/README.md
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/CommandLine/DotnetCommands.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/README.md
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Internal/CliHelpers/ProcessOutputStreamReader.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn/Services/MsBuildInitializer.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.TextTemplating/README.md
- src/dotnet-scaffolding/dotnet-scaffold-aspire/Program.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Program.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CategoryPickerFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CommandPickerFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/ParameterDiscovery.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/StartupFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/FirstPartyComponentInitializer.cs
- removed `!` from logged messages
- removed `- Empty` from MVC and API controllers since there might be generated content (with `--actions` flag)
- updated logic in `MsBuildInitializer.RegisterMsbuild()` to get the newest MSBuild from the newest dotnet sdk installed
- if there were folders present in the default .NET SDK directory that did not follow the .NET version convention, the descending sort would to get the incorrect highest versioned sdk folder.
- checking correct folders by performing a `Version.TryParse`
- also splitting by `-` to account for preview and RC versions.
> minor string changes, sdk version check

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn/Services/MsBuildInitializer.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Common/ClassAnalyzers.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Common/ModelInfo.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/DotnetNewScaffolderStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateBlazorCrudStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateEfControllerStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateMinimalApiStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateRazorPagesStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/MinimalApi/MinimalApiEf.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/MinimalApi/MinimalApiEf.tt
- fixed `MsBuildInitializer.RegisterMsbuild()` change from last PR. The LINQ op was returning the highest version of the .NET SDK but not the path. Didn't catch it due no verbose logging rn, coming soon.
- adding the model namespace (if non-empty) to the Minimal API scaffolded class (EF scenario).
- was not missing from other EF scenario templates
- adding the full model name to the DbContext class when defining the DbSet property.
- was not accounting for namespaces at all.
> bunch of little fixes for `dotnet-scaffold`

- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Program.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/DotnetNewScaffolderStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/EmptyControllerScaffolderStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/Settings/DotnetNewStepSettings.cs
fix empty scaffolders
- `razorpage-empty` : adding missing `--namespace` parameter
- `controller` scaffolders : 
- adding missing `--namespace` parameter
- correctly adding `--actions` parameter (was being added to every scenario)
- `razorview-empty` and `blazor-empty` : not adding unnecessary `--namespace` parameter, was causing the scenario to fail.
> correctly adding --namespace for a bunch of scaffolders

- src/dotnet-scaffolding/dotnet-scaffold/Services/DotNetToolService.cs
when bumping .NET SDK versions on a machine (.NET 8 --> 9 lets  say), local tools are not available to call until a 'dotnet tool restore' is called. Also a fairly mindful operation incase local tool files are messed with, this will help them be repaired before invocation.
> calling 'dotnet tool restore' before invoking local tools

- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Common/Constants.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Models/IdentityModel.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateBlazorCrudStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateEfControllerStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateIdentityStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateMinimalApiStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateRazorPagesStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateViewsStep.cs
scaffolders supporting `--dataContext` classes, any ol non-empty identifier was being allowed to be used for the name of a new DbContext class. Ran into a bug where someone tried to name these classes 'DbContext' which causes error due to it inheriting from 'Microsoft.EntityFrameworkCore.DbContext' 
- checking for valid identifiers using [SyntaxFacts](https://github.com/dotnet/roslyn/blob/main/src/Compilers/CSharp/Portable/Parser/CharacterInfo.cs).IsValidIdentifier
- using constant `NewDbContext` as the default
- updated error messages to include the invalid identifier that was used
- updated all `Validate` steps for `dotnet-scaffold-aspnet` tool.
- removed unused properties in `IdentityModel`.
> check for valid identifiers for --dataContext option

- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Extensions/BlazorCrudScaffolderBuilderExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Extensions/EfControllerScaffolderBuilderExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Extensions/MinimalApiScaffolderBuilderExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Extensions/RazorPagesScaffolderBuilderExtensions.cs
`Microsoft.EntityFrameworkCore.Tools` package was not being added as part of the EF scaffolders. We need to to perform ef migrations and update the database.
- added to all EF scaffolders
> add missing EfCore.Tools package to dotnet-scaffold-aspnet scaffolders.

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Builder/ScaffoldBuilder.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/CommandLine/CommandLineExtensions.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/ComponentModel/CommandInfo.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Scaffolders/IScaffolder.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Scaffolders/Scaffolder.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Program.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/FlowContextProperties.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/FlowExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CategoryDiscovery.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CategoryPickerFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CommandDiscovery.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CommandExecuteFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Telemetry/CommandExecuteTelemetryEvent.cs
previously, scaffolders only were allowed 1 'Category'. Multiple are supported now : 
- changed `Microsoft.DotNet.Scaffolding.Core.Scaffolders.IScaffolder.Category` --> `Microsoft.DotNet.Scaffolding.Core.Scaffolders.IScaffolder.Categories`
- `IScaffoldBuilder.WithCategory` is adding to a `HashSet` now, by default including an `All` category.
- `Microsoft.DotNet.Scaffolding.Core.ComponentModel.DisplayCategory` --> `DisplayCategories` to account for the changes above
- `blazor-identity` now under multiple categories : `Blazor` and `Identity`
- changed telemetry tracking : 
- previously, only tracking `CommandCategory` for the category for the picked scaffolder.
- with above changes, tracking `ChosenCategory` for the interactively picked category, and `AllCommandCategories` for all …
> supporting scaffolders having multiple categories

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Internal/CliHelpers/DotnetCliRunner.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/StartupFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/DotNetToolService.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/FirstPartyComponentInitializer.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/IDotNetToolService.cs
issue started with first time `dotnet-scaffold` use not detecting any categories, delved deeper and found a bunch of issues.
1. `dotnet-scaffold-aspnet` and `dotnet-scaffold-aspire` first time sentinel files were being created even when invoked through dotnet-scaffold.
2. led to environment variable `TelemetryConstants.DOTNET_SCAFFOLD_TELEMETRY_STATE` not being passed correctly. Passing it in all dotnet invocations now.
3. this subsequently fixed the issue at the top, since first time sentinel text was being presented instead of the appropriate `get-commands` result
> fix telemetry flow

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn/Services/MsBuildInitializer.cs
incorrect paths were being checked for both mac and linux. For mac, the ARM path was not being checked. For linux, the path being checked was wrong.
- added the correct linux default path.
- added the correct path to look in macOS for the ARM .NET SDK. Check for this before an x64 version of the sdk because macOS is ARM based now (and x64 will eventually be deprecated)
> add/edit paths where we look for dotnet sdk.

- src/dotnet-scaffolding/Directory.Packages.props
Updating a few transitive dependencies to fix some alerts. The 9.0 versions of these packages still ship net8.0 binaries so we should be ok to update to them.
> Update transitive dependencies

- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Common/Constants.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Common/PackageConstants.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Program.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/DotnetNewScaffolderStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/EmptyControllerScaffolderStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateEfControllerStep.cs
Currently, there is no consistency between scaffolders and where the templates are outputted. Right now: 
- API Controller ---> project-root
- API Controller with actions, using EF  ---> project-root
- Minimal API (Endpoints file) --> project-root
- MVC Controller --> project-root
- MVC Controller with views, using EF --> project-root and project-root\Views
- Razor Component --> project-root
- Razor Component with EF --> project-root\Components
- Razor Page (Empty) --> project-root
- Razor Page using EF --> project-root\Pages
- Razor View (Empty)--> project-root
- Razor Views --> project-root\Views
with this PR:
- **API Controller ---> project-root\Controllers**
- **API Controller with actions, using EF  ---> project-root\Controllers**
- Minimal API (Endpoints file) --> project-root
- …
> fix output paths for a bunch of scaffolders

- All.sln
- scripts/install-scaffold-all.cmd
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn/Helpers/MSBuildProjectServiceHelper.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn/Properties/AssemblyInfo.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn/Services/IMSBuildProjectService.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn/Services/MSBuildProjectService.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn/Services/MsBuildInitializer.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Common/ClassAnalyzers.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Common/ProjectInfo.cs
- test/dotnet-scaffolding/Directory.Packages.props
- test/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn.Tests/MSBuildProjectServiceHelperTests.cs
- test/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn.Tests/Microsoft.DotNet.Scaffolding.Roslyn.Tests.csproj
Roslyn (CodeAnalysis) projects do not contain any information about MSBuild properties such as project capabilities, project tfm(s), root namespaces and so forth.
added MSBuildProjectService to help getting such properties
- using `new Microsoft.Build.Project()` to initialize MSBuild project, fallback is to use  `ProjectCollection.GlobalProjectCollection.LoadProject`
- bulk of the logic is in `MSBuildProjectServiceHelper`, helps with unit testing a lot since MSBuild testing is quite annoying.
- made `MsBuildInitializer` public for access, also iterating through possible sdk paths (for registration) if the first option is not found on disk.
- initializing new found info in `ProjectInfo`
> added MSBuildProjectService

- eng/Versions.DotNetScaffold.props
- scripts/install-scaffold-all.cmd
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn/Services/MSBuildProjectService.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateIdentityStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorIdentity/Shared/AccountLayout.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorIdentity/Shared/AccountLayout.tt
AccountLayout had an incorrect `@layout` reference. Fixing that reference.
- adding a try catch to MSBuildProjectService.Initialize. Loading MSBuild projects fails for blazor projects with no real solution afaik so will dig into this later.  The MSBuildProjectService is nullable friendly so no issues.
- fixed `@layout` reference to `IdentityModel.IdentityLayoutNamespace` and initializing this property correctly.
- updated version from 9.0.0 to 9.0.1.
> fix AccountLayout, also MSBuildProjectService for blazor projects.

- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/ProjectExtensions.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/General/StringUtil.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Internal/StringUtil.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/StringUtilTests.cs
Blazor Identity and CRUD scenario was broken in projects where project names had '.' characters in them. Due to faulty StringUtil.ToPath method
- fixed the method to account for such project names (both dotnet-aspnet-codegenerator and new dotnet-scaffold)
- added a test case, fixed one as well
- added a missing null check in ProjectExtensions.GetDocumentFromName
> fix StringUtil.ToPath and some null checks

- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
- fix MinimalApiEf scaffolder template generates wrong route parameter when primary key is not named "Id"
Fixes #2576
> Fix MinimalApiEf scaffolder generates wrong route parameter when primary key is not named "Id"

- global.json
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/Helpers/EfDbContextHelpers.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Common/ClassAnalyzers.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/EfController/MvcEfController.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/EfController/MvcEfController.tt
found in a couple issues using the `MVC Controller w/ Views using EF` scaffolder : 
1. When using an existing DbContext, the correct DbSet name was not used in the resulting controller
2. All model properties were not being detected (properties from a given model's base class, and its base class and so forth)
3. `MvcEfController.tt` had some minor issues ('movie' name being hardcoded instead of the given model's lower invariant name)
fixes : 
- checking for DbSet name using the full model name (includes namespace)
- using `INamedTypeSymbol.BaseType` (in a loop until BaseType is the default object/null) and adding all properties to a list.
- minor fixes in `MvcEfController.tt`
> fix primary key and DbSet detection for dotnet-scaffold-aspnet

- src/Scaffolding/VS.Web.CG.EFCore/VS.Web.CG.EFCore.csproj
Starting with 9.0.200 (preview right now, will be in VS 17.13 Preview 3+) there is an issue loading transitive dependencies in-proc
- Microsoft.VisualStudio.Web.CodeGeneration.Design --> Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore --> Microsoft.EntityFrameworkCore.Design
- This dependency was set to `PrivateAssets="All"` since it gets loaded by the project when needed (through the scaffolding VS experience)
- However, loading dependencies (assemblies being loaded in proc) has changed in 9.0.200 
-  the `Microsoft.EntityFrameworkCore.Design/Tools` package install with `<PrivateAssets>all</PrivateAssets>`
and `<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>`
- Something has changed in the new sdk where the dependencies are …
> change EFCore.Design dependency to include assets

- test/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn.Tests/MSBuildProjectServiceHelperTests.cs
- we should just use simple projects without SDK reference in order to make tests more reliable.
- this avoids having a dependency on the SDK for tests which do not need anything from the SDK
We are making this change due to the tests failing from breaking SDK changes which would impact the virtual project here. If we wanted a complete end to end, we could use the SDK locator to properly load the SDK, or inject the imports with the complete paths into the csprojectContent
> Just use simple projects in MSBuildProjectServiceHelperTests

- scripts/install-scaffold-all.cmd
Bump the package version to ensure that the `install-scaffold-all.cmd` script runs correctly
this is the package version for `microsoft.dotnet-scaffold-aspire` and `microsoft.dotnet-scaffold-aspnet` and `microsoft.dotnet-scaffold`
> Bump Nuget package version to 10.0.0

- src/dotnet-scaffolding/dotnet-scaffold/AppBuilder/ScaffoldCommandAppBuilder.cs
This Application name is used in the `--help` and it was misrepresenting the usage of the command there. the tool is not invoked with `dotnet-scaffold` , but with `dotnet scaffold` this corrects that error:
before:
after:
> Change the application name from "dotnet-scaffold" to "dotnet scaffold"

- azure-pipelines-pr.yml
Only call publish from windows debug strategy
> Call build.sh/.cmd directly to avoid multiple publish

- src/dotnet-scaffolding/dotnet-scaffold/Command/ScaffoldCommand.cs
Part of the work to make the tool's `--help` more robust
Before:
after:
> add component help description

- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Helpers/AzCliHelper.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Program.cs
If the az cli commands are unavailable or fail, do not show the `Entra ID` Scaffold option. 
This change abstracts the az CLI getting the usernames, tenant ids and app ids for users. 
There are more `try`s and `catch`es to ensure that errors get caught and propagated correctly.
fixes #3217
> az CLI commands are caught correctly

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/ComponentModel/CommandInfoExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold/Interactive/Flow/Steps/CommandExecuteFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/DotNetToolService.cs
After merging the `aspire` scaffolders into `dotnet-scaffold` the `aspire` scaffolders were not appearing in the interactive mode. The way that the interactive scaffolder command is through running `get-commands` for identified scaffolding tools, but it was ignoring `dotnet-scaffold` explicitly.  Now, `aspire` commands can be run in addition to the `aspnet` commands.
Note: this is a temporary fix. I am going to rework the command identification of our own commands through `get-commands`. I want to do this after I merge `aspnet` into the `dotnet-scaffold`.
> invoke "dotnet-scaffold aspire" for aspire commands
