dotnet/Scaffolding

- build.cmd
- build.sh
- src/Microsoft.Framework.CodeGeneration.Common/project.json
- src/Microsoft.Framework.CodeGeneration.Core/project.json
- src/Microsoft.Framework.CodeGeneration.EntityFramework/project.json
- src/Microsoft.Framework.CodeGeneration.Templating/project.json
- src/Microsoft.Framework.CodeGeneration/project.json
- src/Microsoft.Framework.CodeGenerators.Mvc/project.json
- test/Microsoft.Framework.CodeGeneration.Core.FunctionalTest/project.json
- test/Microsoft.Framework.CodeGeneration.Core.Test/KpmPackageInstallerTests.cs
- test/Microsoft.Framework.CodeGeneration.Core.Test/project.json
- test/Microsoft.Framework.CodeGeneration.EntityFramework.Test/project.json
- test/Microsoft.Framework.CodeGeneration.Templating.Test/project.json
- test/Microsoft.Framework.CodeGenerators.Mvc.Test/project.json
- test/TestApps/ModelTypesLocatorTestClassLibrary/project.json
- test/TestApps/ModelTypesLocatorTestWebApp/project.json
Prepping to be merged once ready.
> Update aspnet50/aspnetcore50 => dnx50/dnxcore50.

- test/Microsoft.Framework.CodeGeneration.Core.FunctionalTest/TestHelper.cs
cc @davidfowl https://github.com/aspnet/Scaffolding/compare/haok/3-19hosting?expand=1#diff-11db4bb67531caae73c11d80587988bfR35
> React to hosting

- src/Microsoft.Framework.CodeGeneration.Core/KpmPackageInstaller.cs
- src/Microsoft.Framework.CodeGeneration/Program.cs
- test/Microsoft.Framework.CodeGeneration.Core.Test/KpmPackageInstallerTests.cs
https://github.com/aspnet/Universe/issues/186
@davidfowl @muratg
> Rename kpm to dnu

- build.sh
- src/Microsoft.Framework.CodeGeneration/Program.cs
- test/runtests.cmd
https://github.com/aspnet/dnx/issues/1473
@davidfowl @muratg
> Remove k command and use dnx instead

- src/Microsoft.Framework.CodeGeneration.Core/project.json
> Make CommandLineUtils dependency build time

- src/Microsoft.Framework.CodeGeneration.EntityFramework/EntityFrameworkServices.cs
- src/Microsoft.Framework.CodeGeneration.EntityFramework/project.json
This reverts commit 83925fee30a52e6c600a663f49ba24b043b645a5.
> Revert "React to aspnet/EntityFramework#2613"

- src/Microsoft.Extensions.CodeGeneration.EntityFramework/EntityFrameworkServices.cs
:watch: https://github.com/aspnet/EntityFramework/pull/3331
> React to EF rename

- src/Microsoft.Extensions.CodeGenerators.Mvc/Common/CommonGeneratorBase.cs
- src/Microsoft.Extensions.CodeGenerators.Mvc/Common/ModelTypeAndContextModel.cs
- src/Microsoft.Extensions.CodeGenerators.Mvc/Controller/ControllerGeneratorBase.cs
- src/Microsoft.Extensions.CodeGenerators.Mvc/Controller/ControllerWithContextGenerator.cs
- src/Microsoft.Extensions.CodeGenerators.Mvc/Controller/MvcControllerWithContext.cs
- src/Microsoft.Extensions.CodeGenerators.Mvc/View/ViewGenerator.cs
> Refactoring.

- src/Microsoft.Extensions.CodeGeneration/Program.cs
- test/Microsoft.Extensions.CodeGeneration.Core.FunctionalTest/TestHelper.cs
> Refactor dependency injection usages

- src/Microsoft.Extensions.CodeGeneration.EntityFramework/ModelMetadata.cs
- test/Microsoft.Extensions.CodeGeneration.EntityFramework.Test/ModelMetadataTests.cs
- test/Microsoft.Extensions.CodeGeneration.EntityFramework.Test/NavigationMetadataTests.cs
- test/Microsoft.Extensions.CodeGeneration.EntityFramework.Test/PropertyMetadataTests.cs
Fix build after https://github.com/aspnet/EntityFramework/commit/de4f73e9517ba75f69064e45ff30d2755a3981d3
@anpete @natemcmaster
> React to EF changes

- .gitignore
- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ViewGenerator/Edit.cshtml
> Fix for bug 155796 formatting of the Edit.cshtml is iincorrect

- src/Microsoft.Extensions.CodeGeneration.Core/ModelTypesLocator.cs
- src/Microsoft.Extensions.CodeGeneration.Core/ProjectUtilities.cs
- src/Microsoft.Extensions.CodeGeneration.Core/ReflectionUtilities.cs
- src/Microsoft.Extensions.CodeGeneration.Core/RoslynUtilities.cs
- src/Microsoft.Extensions.CodeGeneration.EntityFramework/EntityFrameworkServices.cs
- src/Microsoft.Extensions.CodeGeneration.Sources/CommonUtilities.cs
- src/Microsoft.Extensions.CodeGeneration.Templating/Compilation/RoslynCompilationService.cs
- src/Microsoft.Extensions.CodeGeneration/Program.cs
- test/Microsoft.Extensions.CodeGeneration.Core.FunctionalTest/ModelTypesLocatorTests.cs
- test/Microsoft.Extensions.CodeGeneration.Core.FunctionalTest/TestHelper.cs
- test/Microsoft.Extensions.CodeGeneration.Templating.Test/RazorTemplatingTests.cs
Issue: https://github.com/aspnet/Universe/issues/318
Depends on https://github.com/aspnet/dnx/pull/3126
/cc @davidfowl @pranavkm
> Rename Microsoft.Dnx.Compilation.Abstractions to Microsoft.Extensions.Compilation.Abstractions 

- src/Microsoft.Extensions.CodeGenerators.Mvc/Constants.cs
- src/Microsoft.Extensions.CodeGenerators.Mvc/Controller/CommandLineGenerator.cs
- src/Microsoft.Extensions.CodeGenerators.Mvc/Controller/ControllerGeneratorBase.cs
- src/Microsoft.Extensions.CodeGenerators.Mvc/Controller/ControllerWithContextGenerator.cs
- src/Microsoft.Extensions.CodeGenerators.Mvc/Controller/MvcController.cs
- src/Microsoft.Extensions.CodeGenerators.Mvc/Controller/MvcControllerEmpty.cs
- src/Microsoft.Extensions.CodeGenerators.Mvc/Controller/MvcControllerWithReadWriteActionGenerator.cs
- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/ApiControllerWIthActions.cshtml
- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/ApiEmptyController.cshtml
- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/ControllerWithActions.cshtml
Code Reviewed by Bill Hiebert.
http://codeflow/dashboard/review/display/prbhosal-3a31f467fa574ee399bf0ca0579bc2cd
> Adding Empty and Crud Controller scaffolders (Web and Api)

- src/Microsoft.Extensions.CodeGeneration.EntityFramework/EntityFrameworkServices.cs
- test/Microsoft.Extensions.CodeGeneration.Core.FunctionalTest/TestHelper.cs
Reacting to https://github.com/aspnet/Hosting/pull/521.
For reference only, pushing immediately.
> Reacting to new Hosting API

- src/Microsoft.Extensions.CodeGenerators.Mvc/Controller/ControllerWithContextTemplateModel.cs
- src/Microsoft.Extensions.CodeGenerators.Mvc/RoslynUtilities.cs
- test/Microsoft.Extensions.CodeGenerators.Mvc.Test/RoslynUtilitiesTest.cs
> Handle reserved keywords while creating model variables in controller

- src/Microsoft.Extensions.CodeGeneration.Core/ActionInvoker.cs
- src/Microsoft.Extensions.CodeGeneration.Core/ParameterDescriptor.cs
- src/Microsoft.Extensions.CodeGeneration.Core/project.json
- src/Microsoft.Extensions.CodeGeneration/project.json
- test/Microsoft.Extensions.CodeGeneration.Core.Test/ParameterDescriptorTests.cs
> Unsource CommandLineUtils

- src/Microsoft.Extensions.CodeGeneration.EntityFramework/Templates/DbContext/NewLocalDbContext.cshtml
- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/ApiControllerWIthActions.cshtml
- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/ApiControllerWithContext.cshtml
- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/ApiEmptyController.cshtml
- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/ControllerWithActions.cshtml
- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/EmptyController.cshtml
- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
> Adding minimum set of namespaces to templates.

- test/Microsoft.Extensions.CodeGeneration.EntityFramework.Test/ResourceUtilities.cs
- test/Microsoft.Extensions.CodeGeneration.EntityFramework.Test/project.json
> React to Fileprovider namespace changes

- src/Microsoft.Extensions.CodeGeneration.Core/project.json
- src/Microsoft.Extensions.CodeGenerators.Mvc/project.json
> Updated Json.Net versions

- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/ApiControllerWithContext.cshtml
- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
Addresses #172 
cc @abpiskunov
> React to MVC action result naming changes

- src/Microsoft.Extensions.CodeGeneration.Utils/DotNet/ApplicationEnvironment.cs
- src/Microsoft.Extensions.CodeGeneration.Utils/DotNet/IApplicationEnvironment.cs
- src/Microsoft.Extensions.CodeGeneration.Utils/DotNet/LibraryExporter.cs
- src/Microsoft.Extensions.CodeGeneration/Program.cs
- test/Microsoft.Extensions.CodeGeneration.Core.FunctionalTest/TestApplicationEnvironment.cs
- test/Microsoft.Extensions.CodeGeneration.Core.FunctionalTest/TestHelper.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/CommonUtilitiesTests.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/DefaultAssemblyLoadContextTests.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/LibraryExporterTests.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/TestBase.cs
- test/Microsoft.Extensions.CodeGeneration.Templating.Test/RazorTemplatingTests.cs
> Fixes #175 by removing hardcoded configuration for LibraryExporter.

- src/Microsoft.Extensions.CodeGeneration.Utils/CommonUtilities.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/CommonUtilitiesTests.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/LibraryExporterTests.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/LibraryManagerTests.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/project.json
> Fix build and tests on *nix.

- src/Microsoft.Extensions.CodeGeneration.Core/project.json
- src/Microsoft.Extensions.CodeGenerators.Mvc/project.json
> Updated Json.Net version

- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/ControllerWithActions.cshtml
/cc @davidfowl @prafullbhosale
> Use `IFormCollection` not `.Internal` implementation

- test/Microsoft.Extensions.CodeGeneration.Sources.Test/CommonUtilitiesTests.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/DefaultAssemblyLoadContextTests.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/LibraryExportExtensionsTest.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/LibraryExporterTests.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/LibraryManagerTests.cs
https://github.com/aspnet/Coherence-Signed/issues/225
cc @pranavkm @NTaylorMullen @dougbu
> Fix failing test on non-Windows.

- test/Microsoft.Extensions.CodeGeneration.Sources.Test/ApplicationEnvironmentTests.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/CommonUtilitiesTests.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/CompilationResultTests.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/DefaultAssemblyLoadContextTests.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/LibraryExportExtensionsTest.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/LibraryExporterTests.cs
- test/Microsoft.Extensions.CodeGeneration.Sources.Test/LibraryManagerTests.cs
This will resolve https://github.com/aspnet/Coherence-Signed/issues/230
> Fix sources tests

- src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/ControllerWithActions.cshtml
cc @phenning @barrytang 
@Eilon and @DamianEdwards  for RC2 approval.
> Add [ValidateAntiForgeryToken] for all post methods

- src/Microsoft.Extensions.CodeGeneration.Tools/DotNetBuildCommandHelper.cs
- src/Microsoft.Extensions.CodeGeneration.Tools/Program.cs
Fixes #220 
cc @NTaylorMullen 
cc @barrytang, @Eilon for RC2 approval
> Add handlers for StdOut and StdErr for build command

- Scaffolding.sln
- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/DefaultFileSystem.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/IFileSystem.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/DbContextEditorServices.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/CodeGeneratorActionsServiceTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/FilesLocatorTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/PackageInstallerTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/DbContextEditorServicesTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/compiler/resources/Startup_Empty_Method_RegisterContext_After.txt
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/compiler/resources/Startup_Empty_Method_RegisterContext_Before.txt
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/compiler/resources/Startup_RegisterContext_After.txt
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/compiler/resources/Startup_RegisterContext_Before.txt
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Test.Sources/Microsoft.VisualStudio.Web.CodeGeneration.Test.Sources.xproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Test.Sources/MockFileSystem.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.Test.Sources/project.json
Porting changes from https://github.com/aspnet/Scaffolding/tree/pk/155791
The original issue of app reload when appsettings is modified is resolved already.
> Changes to write connection string to appsettings.json

- makefile.shade
> Use KOREBUILD_NUGET_EXE for repacks

- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/ModelTypesLocator.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest/ModelTypesLocatorTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest/TestHelper.cs
- test/TestApps/ClassLibrary1/Class1.cs
- test/TestApps/ClassLibrary1/ClassLibrary1.xproj
- test/TestApps/ClassLibrary1/Properties/AssemblyInfo.cs
- test/TestApps/ClassLibrary1/project.json
- test/TestApps/ModelTypesLocatorTestClassLibrary/project.json
> Get distinct model types from projects and dependencies

- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/DbContextEditorServices.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ControllerGenerator/ControllerWithActions.cshtml
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/DbContextEditorServicesTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/compiler/resources/Startup_Empty_Method_RegisterContext_After.txt
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/compiler/resources/Startup_RegisterContext_After.txt
Add new connection string under ConnectionStrings node in appsettings.json. Fixes #259
Added a newline in controllerWithActions.cshtml. Fixes #228
cc @abpiskunov
> Bug fixes 

- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Program.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/ToolCommandLineHelper.cs
> Add --no-build flag to dotnet-aspnet-codegenerator. Fixes #261

- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/EntityFrameworkServices.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/EntityFrameworkServicesTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/TestAssemblyLoadContext.cs
- test/TestApps/ModelTypesLocatorTestClassLibrary/Car.cs
- test/TestApps/ModelTypesLocatorTestWebApp/Models/CarContext.cs
- test/TestApps/ModelTypesLocatorTestWebApp/Startup.cs
- test/TestApps/ModelTypesLocatorTestWebApp/project.json
> Look for model type in dependencies if its not found in the project directly.

- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest/ModelTypesLocatorTests.cs
- test/TestApps/ClassLibrary2/Class2.cs
- test/TestApps/ClassLibrary2/ClassLibrary2.xproj
- test/TestApps/ClassLibrary2/Properties/AssemblyInfo.cs
- test/TestApps/ClassLibrary2/project.json
Created a new test app with limited number of types in it and its dependencies to definitively test the GetAllTypes()
cc @abpiskunov
> Re-enable ModelTypesLocatorsTest. Fixes #88

- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/ExceptionExtensions.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/EntityFrameworkServices.cs
> Surface proper exception when DbContext instance creation fails rather than attempting to create an instance using DI. 

- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Templating/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration/project.json
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Test.Sources/project.json
- test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test/project.json
- test/TestApps/ModelTypesLocatorTestClassLibrary/project.json
> Updating version to 1.0.0-preview2-update1

- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/Templates/DbContext/NewLocalDbContext.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ControllerGenerator/ApiControllerWIthActions.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ControllerGenerator/ApiControllerWithContext.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ControllerGenerator/ApiEmptyController.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ControllerGenerator/ControllerWithActions.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ControllerGenerator/EmptyController.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/Startup/ReadMe.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/Startup/Startup.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ViewGenerator/Create.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ViewGenerator/Delete.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ViewGenerator/Details.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ViewGenerator/Edit.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ViewGenerator/Empty.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ViewGenerator/List.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ViewGenerator/_ValidationScriptsPartial.cshtml
> Add UTF-8 BOM to template files

- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/EntityFrameworkServices.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/IEntityFrameworkService.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Areas/AreaGenerator.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Areas/AreaGeneratorCommandLine.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Controller/ControllerGeneratorBase.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Controller/ControllerWithContextGenerator.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Dependency/ReadMeGenerator.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/ModelMetadataUtilities.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/Startup/ReadMe.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/View/ModelBasedViewScaffolder.cs
- test/E2E_Test/AreaScaffolderTests.cs
- test/E2E_Test/Baseline/CarsWithViewController.txt
- test/E2E_Test/Baseline/ReadMe/Readme.txt
- test/E2E_Test/E2ETestBase.cs
- test/E2E_Test/MvcControllerTest.cs
- test/E2E_Test/ScaffoldingE2ETestFixture.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/EntityFrameworkServicesTests.cs
- test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test/ModelMetadataUtilitiesTest.cs
- Added scaffolder for Areas
- Modified controller scaffolders to add [Area] attribute if the scaffolding is being done under \Areas
- Compute area based output path for views while scaffolding an MvcController with DbContext.
cc @abpiskunov
> Support for scaffolding areas.

- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Common/ValidationUtil.cs
> Make ValidationUtil public. 

- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/project.json
> Add Microsoft.DotNet.InternalAbstractions dependency to the tools package

- build.ps1
- build.sh
- makefile.shade
- src/Microsoft.Extensions.ProjectModel.MsBuild.Sources/MsBuildProjectContextBuilder.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/DotNetBuildCommandHelper.cs
- test/E2E_Test/E2ETestBase.cs
- test/Microsoft.Extensions.ProjectModel.Tests/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Tools.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test/project.json
- test/Shared/MsBuildProjectSetupHelper.cs
> Run tests with CLI 1.0.0-preview3 without *3 verbs

- makefile.shade
- test/Shared/MsBuildProjectStrings.cs
cref https://github.com/dotnet/cli/pull/4602
cc @prafullbhosale
> Fork version to 1.0.0-msbuild1

- makefile.shade
- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Templating/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration/project.json
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Test.Sources/project.json
- test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test/project.json
- test/TestApps/ModelTypesLocatorTestClassLibrary/project.json
This is LTS version with Project.json support. 
cc @natemcmaster @pranavkm @NTaylorMullen
> Bump version to preview4

- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/project.json
- test/E2E_Test/project.json
- test/Microsoft.Extensions.ProjectModel.Tests/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/project.json
cc @prafullbhosale 
:watch: on a final build version of Microsoft.DotNet.Cli.Utils
> feature/msbuild: pin to stable versions

- .gitignore
- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Templating/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration/project.json
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/project.json
- test/E2E_Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Test.Sources/project.json
This is for FTS with PJ support. 
@natemcmaster @pranavkm
> Bump versions to 1.1.0-*

- test/E2E_Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test/project.json
- test/TestApps/WebApplication1/project.json
> Fix version for NetCoreApp in test projects.

- TestApps/WebApplication1/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/project.json
- test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test/project.json
> Fix version numbers in test apps.

- build.ps1
- build.sh
- makefile.shade
> Bump to msbuild2

- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/project.json
- test/E2E_Test/project.json
- test/Microsoft.Extensions.ProjectModel.Tests/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/project.json
cc @mlorbetske @barrytang @pranavkm
> Upgrade Cli.Utils to 4215. Fixes #350

- src/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild/project.json
- test/Microsoft.Extensions.ProjectModel.Tests/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/project.json
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/project.json
> Update MSBuild versions to match CLI

- test/Shared/MsBuildProjectStrings.cs
> Add nuget sources to fix E2E_tests

- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/project.json
Fixes #355 
cc @natemcmaster @mlorbetske
> Add prefercliruntime file to CodeGeneration.Tools package.

- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/project.json
- src/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild/Target/build/Microsoft.VisualStudio.Web.CodeGeneration.Tools.targets
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/project.json
Change the CodeGeneration.MsBuild.dll location (tools -> toolassets)
Fixes #357 
Related: https://github.com/aspnet/Coherence/issues/141
cc @natemcmaster @mlorbetske
> Downgrade Microsoft.NETCoreApp to 1.0.0

- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/EntityFrameworkServices.cs
> Throw error from EF as is if finding entityType fails.

- Scaffolding.sln
- src/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild/ProjectReferenceInformationProvider.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.Test/Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.Test.xproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.Test/ProjectReferenceInformationProviderTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.Test/project.json
Resolve absolute paths of projectreferences.
@mlorbetske
> Fixes #347

- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/project.json
cc @DamianEdwards @mikeharder @muratg
> Remove reference to NETStandard.Library

- src/Shared/Cli.Utils/ArgumentEscaper.cs
- src/Shared/Cli.Utils/Command.cs
- src/Shared/DotNetDispatcher/DotnetToolDispatcher.cs
> Escape arguments before starting new process 

- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/AssemblyAttributeGenerator.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/EntityFrameworkServices.cs
- test/Shared/MsBuildProjectStrings.cs
Fixes #373 
cc @natemcmaster @mlorbetske
> Add UserSecretsAttribute to in memory assembly

- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/Microsoft.VisualStudio.Web.CodeGeneration.Core.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/Microsoft.VisualStudio.Web.CodeGeneration.Design.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Templating/Microsoft.VisualStudio.Web.CodeGeneration.Templating.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Microsoft.VisualStudio.Web.CodeGeneration.Tools.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/Microsoft.VisualStudio.Web.CodeGeneration.Utils.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration/Microsoft.VisualStudio.Web.CodeGeneration.csproj
- test/Shared/MsBuildProjectStrings.cs
- version.props
Creating a feature/msbuild-1.1.0 branch from feature/msbuild and bumping versions to 1.1.0
Once, this PR is merged, will create a rel/msbuild-1.1.0 branch from this.
cc @natemcmaster @muratg @mlorbetske @pranavkm
> Bump package versions to 1.1.0

- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ViewGenerator/Delete.cshtml
- test/E2E_Test/Compiler/Resources/CarViews/Delete.cshtml
- test/E2E_Test/Compiler/Resources/ProductViews/Delete.cshtml
Fixes #308 
cc @rowanmiller @mlorbetske
> Add Hidden input for primary key on delete page

- src/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild.csproj
> Add tags to Microsoft.VisualStudio.Web.CodeGeneration.MsBuild

- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/DbContextEditorServices.cs
> Compute entityset variable name based on exisiting symbols.

- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Microsoft.VisualStudio.Web.CodeGeneration.Tools.csproj
cc @natemcmaster 
Addresses aspnet/coherence-signed/issues/397
Same change needs to happen in `rel/1.1.0`
cc @Eilon @mlorbetske @muratg for Escrow approval.
> Remove deps.json from the CodeGeneration.Tools package

- src/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Microsoft.VisualStudio.Web.CodeGeneration.Tools.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/Microsoft.VisualStudio.Web.CodeGeneration.Utils.csproj
- test/Microsoft.Extensions.ProjectModel.Tests/Microsoft.Extensions.ProjectModel.Tests.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.Test/Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test.csproj
cc @natemcmaster 
This same change will need to happen in `rel/1.1.0` branch
> Update msbuild version

- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/Microsoft.VisualStudio.Web.CodeGeneration.Design.csproj
- test/E2E_Test/E2E_Test.csproj
- test/Microsoft.Extensions.ProjectModel.Tests/Microsoft.Extensions.ProjectModel.Tests.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.Test/Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Tools.Test/Microsoft.VisualStudio.Web.CodeGeneration.Tools.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test.csproj
- test/Shared/MsBuildProjectStrings.cs
@phenning @natemcmaster 
@mlorbetske
> Update netcoreapp1.0 -> netcoreapp1.1 for CodeGeneration.Design

- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/CodeModelMetadata.cs
- test/E2E_Test/ViewGeneratorTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/CodeModelMetadataTests.cs
- test/Shared/MsBuildProjectStrings.cs
- version.props
Fixes #425 
cc @mlorbetske, @Eilon @muratg
> Fix view generation without DbContext

- build/dependencies.props
- src/Microsoft.VisualStudio.Web.CodeGeneration.Contracts/Microsoft.VisualStudio.Web.CodeGeneration.Contracts.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/Microsoft.VisualStudio.Web.CodeGeneration.Core.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Microsoft.VisualStudio.Web.CodeGeneration.Tools.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/Microsoft.VisualStudio.Web.CodeGeneration.Utils.csproj
- test/E2E_Test/E2E_Test.csproj
- test/Microsoft.Extensions.ProjectModel.Tests/Microsoft.Extensions.ProjectModel.Tests.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.Test/Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Tools.Test/Microsoft.VisualStudio.Web.CodeGeneration.Tools.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test.csproj
- test/TestApps/ClassLibrary1/ClassLibrary1.csproj
- test/TestApps/ClassLibrary2/ClassLibrary2.csproj
- test/TestApps/ModelTypesLocatorTestClassLibrary/ModelTypesLocatorTestClassLibrary.csproj
- test/TestApps/ModelTypesLocatorTestWebApp/ModelTypesLocatorTestWebApp.csproj
> Update to Newtonsoft.Json 10.0.1

- build/dependencies.props
- test/Shared/MsBuildProjectStrings.cs
> Update Roslyn dependency to 2.0

- test/E2E_Test/E2E_Test.csproj
- test/Microsoft.Extensions.ProjectModel.Tests/Microsoft.Extensions.ProjectModel.Tests.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/CodeGeneratorsLocatorTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.Test/Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/CommonUtilitiesTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test/TestCompilationService.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.Tools.Test/Microsoft.VisualStudio.Web.CodeGeneration.Tools.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test.csproj
- Required for tests to pass on Ubuntu with SDK 2.0.0-preview1-005783
> Convert tests to netcoreapp2.0

- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Microsoft.VisualStudio.Web.CodeGeneration.Tools.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/Microsoft.VisualStudio.Web.CodeGeneration.Utils.csproj
- src/Shared/DotNetDispatcher/DotnetToolDispatcher.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/PackageInstallerTests.cs
This PR removes all references to PlatformAbstractions.
Part of aspnet/PlatformAbstractions#50
> react to removal of PlatformAbstractions

- NuGetPackageVerifier.json
- build/dependencies.props
- src/Microsoft.VisualStudio.Web.CodeGeneration.Contracts/Microsoft.VisualStudio.Web.CodeGeneration.Contracts.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Microsoft.VisualStudio.Web.CodeGeneration.Tools.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/Microsoft.VisualStudio.Web.CodeGeneration.Utils.csproj
- test/E2E_Test/AreaScaffolderTests.cs
- test/E2E_Test/E2E_Test.csproj
- test/E2E_Test/MvcControllerTest.cs
- test/E2E_Test/SimulationModeTests.cs
- test/E2E_Test/ViewGeneratorTests.cs
- test/Microsoft.Extensions.ProjectModel.Tests/Microsoft.Extensions.ProjectModel.Tests.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.Test/Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Tools.Test/Microsoft.VisualStudio.Web.CodeGeneration.Tools.Test.csproj
- test/TestApps/ClassLibrary1/ClassLibrary1.csproj
- test/TestApps/ModelTypesLocatorTestClassLibrary/ModelTypesLocatorTestClassLibrary.csproj
- test/TestApps/ModelTypesLocatorTestWebApp/ModelTypesLocatorTestWebApp.csproj
- test/TestApps/ModelTypesLocatorTestWebApp/Program.cs
cc @mlorbetske 
E2E tests failing currently. 
Need to wait for new CLI to be available before merging this.
> Upgrade CodeGeneration.Tools package to netcoreapp2.0

- NuGet.config
> Remove additional feeds from NuGet.config

- test/E2E_Test/AreaScaffolderTests.cs
- test/E2E_Test/MvcControllerTest.cs
- test/E2E_Test/SimulationModeTests.cs
- test/E2E_Test/ViewGeneratorTests.cs
> Enabling E2E tests

- build/dependencies.props
> Update Msbuild dependency version to match CLI

- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.csproj
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.csproj
Fixes #477 
cc @Eilon @mikeharder @mlorbetske
> Fix package paths for OSX and Ubuntu.

- build/dependencies.props
- test/E2E_Test/E2E_Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Test.csproj
https://github.com/aspnet/Coherence/issues/175
> Remove unnecessary package references

- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/CodeGenerationEnvironmentHelper.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/Program.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/EntityFrameworkServices.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/Templates/DbContext/NewDbContextFactory.cshtml
> Fix EF based scaffolding

- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test/TestModels/TestModel.cs
> React to aspnet/EntityFramework/pull/8534

- test/E2E_Test/MvcControllerTest.cs
- test/E2E_Test/ViewGeneratorTests.cs
Fixes #491 
EF issue has been fixed:
https://github.com/aspnet/Scaffolding/issues/491#issuecomment-303442439
Tested this locally with volatile feed.
> Re-enable EF based tests.

- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/FileSystemChangeTracker.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/Microsoft.VisualStudio.Web.CodeGeneration.Core.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/SimulationModeFileSystem.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/Microsoft.VisualStudio.Web.CodeGeneration.Design.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/ServiceProvider.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/ReflectedTypesProvider.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Templating/Microsoft.VisualStudio.Web.CodeGeneration.Templating.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Microsoft.VisualStudio.Web.CodeGeneration.Tools.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/DotNet/DefaultAssemblyLoadContext.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/Microsoft.VisualStudio.Web.CodeGeneration.Utils.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration/Microsoft.VisualStudio.Web.CodeGeneration.csproj
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/CodeGeneratorsLocatorTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.Test/ProjectReferenceInformationProviderTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.Sources.Test/CommonUtilitiesTests.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test/TestCompilationService.cs
- test/Shared/MsBuildProjectStrings.cs
Need to react to https://github.com/aspnet/Microsoft.Data.Sqlite/commit/69bbe2215963a6ec7d4885af9a88fcd341008c76
cc @mlorbetske, @Eilon
> Bump target framework version to net461

- build/common.props
- build/dependencies.props
- src/Microsoft.VisualStudio.Web.CodeGeneration.Contracts/Microsoft.VisualStudio.Web.CodeGeneration.Contracts.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/FileSystemChangeTracker.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/Microsoft.VisualStudio.Web.CodeGeneration.Core.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Core/SimulationModeFileSystem.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/Microsoft.VisualStudio.Web.CodeGeneration.Design.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/ReflectedTypesProvider.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild/Target/build/Microsoft.VisualStudio.Web.CodeGeneration.Tools.targets
- src/Microsoft.VisualStudio.Web.CodeGeneration.Templating/Microsoft.VisualStudio.Web.CodeGeneration.Templating.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Tools/Microsoft.VisualStudio.Web.CodeGeneration.Tools.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/DotNet/DefaultAssemblyLoadContext.cs
- src/Microsoft.VisualStudio.Web.CodeGeneration.Utils/Microsoft.VisualStudio.Web.CodeGeneration.Utils.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration/Microsoft.VisualStudio.Web.CodeGeneration.csproj
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.csproj
- test/TestApps/ClassLibrary1/ClassLibrary1.csproj
- test/TestApps/ClassLibrary2/ClassLibrary2.csproj
- test/TestApps/ModelTypesLocatorTestClassLibrary/ModelTypesLocatorTestClassLibrary.csproj
> Migrate to netstandard2.0

- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ViewGenerator/Delete.cshtml
- test/E2E_Test/Compiler/Resources/CarViews/Delete.cshtml
- test/E2E_Test/Compiler/Resources/ProductViews/Delete.cshtml
Fixes issue reported on [developer community](https://developercommunity.visualstudio.com/content/problem/32217/scaffolding-of-controller-delete-view-identity-for.html)
> Generate hidden input inside <Form> on delete page.

- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/IPropertyExtensions.cs
- https://github.com/aspnet/EntityFramework/pull/8682
> React to rename of PropertyValueBehavior.UseValue to PropertySaveBehavior.Save

- build/dependencies.props
> Pin MSBuild version to 188

- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/MessageStrings.Designer.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/MessageStrings.resx
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/View/ViewGenerator.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/View/ViewScaffolderBase.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/View/ViewTemplate.cs
> Add templatename validation to view generator.

- src/Microsoft.VisualStudio.Web.CodeGeneration.Templating/TypeUtilities.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
- test/E2E_Test/Compiler/Resources/CarsController.txt
- test/E2E_Test/Compiler/Resources/CarsWithViewController.txt
- test/Microsoft.VisualStudio.Web.CodeGeneration.Templating.Test/TypeUtilitiesTest.cs
- test/Shared/MsBuildProjectStrings.cs
> Fix issue with string Ids

- test/Shared/MsBuildProjectSetupHelper.cs
- test/Shared/MsBuildProjectStrings.cs
> Use Nuget.config from repo root for E2E tests.

- src/Microsoft.Extensions.ProjectModel.MsBuild.Sources/MsBuildProjectContextBuilder.cs
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.Test/SimulationModeFileSystemTests.cs
> Replace GetTempFileName => GetTempPath+GetRandomFileName

- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/ParameterDefinitions/razorpage.json
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/RazorPage/RazorPageGeneratorModel.cs
This makes the `razorpage` generator show up when running `dotnet aspnet-codegenerator -h`
```
λ dotnet aspnet-codegenerator razorpage -h                                                                                                                                                       
Usage: aspnet-codegenerator [arguments] [options]                                                                                                                                                
Arguments:                                                                                                                                                                                       
generator  Name of the generator. Check available generators below. …
```
> Add ParameterDefinition file for Razor Page generator.

- test/E2E_Test/E2ETestBase.cs
Normalize line endings for actual contents as well as expected contents.
> Fix E2E test verification.

- test/Shared/MsBuildProjectStrings.cs
> Update ApplicationInsights to latest

- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/EntityFrameworkServices.cs
> Switch to using DbContextActivator

- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/Program.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/MessageStrings.Designer.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/MessageStrings.resx
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/RazorPage/EFModelBasedRazorPageScaffolder.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/RazorPage/EmptyRazorPageScaffolder.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/RazorPage/RazorPageGenerator.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/RazorPage/RazorPageGeneratorModel.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/RazorPage/RazorPageGeneratorTemplateModel.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/RazorPage/RazorPageScaffolderBase.cs
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/RazorPageGenerator/Create.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/RazorPageGenerator/Delete.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/RazorPageGenerator/Details.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/RazorPageGenerator/Edit.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/RazorPageGenerator/Empty.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/RazorPageGenerator/List.cshtml
When generating all pages, the templateName is "All". Initial code had danticipated it being null.
> Fixed logic for which Razor scaffolder gets invoked.

- test/Ext.ProjectModel.Tests/Ext.ProjectModel.Tests.csproj
> Remove unneeded Newtonsoft reference

- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/RazorPageGenerator/EditPageModel.cshtml
- test/E2E_Test/Compiler/Resources/RazorPages/Crud/EditCs.txt
Fixes #587 
cc @mlorbetske @Eilon
> Handle DbUpdateConcurrencyException in Edit Razor Page

- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/Microsoft.VisualStudio.Web.CodeGeneration.Design.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest.csproj
- test/Shared/MsBuildProjectStrings.cs
- version.props
cc @Eilon @mlorbetske 
Created against the right branch.
> Prepare for 1.0.2 version

- NuGet.config
- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/Microsoft.VisualStudio.Web.CodeGeneration.Design.csproj
- src/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.csproj
- test/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest/Microsoft.VisualStudio.Web.CodeGeneration.Core.FunctionalTest.csproj
- test/Shared/MsBuildProjectStrings.cs
- version.props
Need to update the `RuntimeFrameworkVersion` to the correct version.
> Branching rel for 1.0.2

- test/Shared/MsBuildProjectStrings.cs
- test/TestApps/ModelTypesLocatorTestWebApp/ModelTypesLocatorTestWebApp.csproj
> Update versions for the patch

- test/Shared/MsBuildProjectSetupHelper.cs
- test/Shared/MsBuildProjectStrings.cs
Not the best fix but this will fix the tests.
> Patch test fixes

- build/dependencies.props
- korebuild-lock.txt
- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/Microsoft.VisualStudio.Web.CodeGeneration.Design.csproj
Resolves https://github.com/aspnet/Scaffolding/issues/645
> [2.0.x] Remove Microsoft.NETCore.App from .Design nuspec

- src/Microsoft.VisualStudio.Web.CodeGeneration.Design/Microsoft.VisualStudio.Web.CodeGeneration.Design.csproj
This fixes the issue with the architecture mismatch. 
cc @mlorbetske @natemcmaster @rynowak
> Fix package structure for CodeGeneration.Design

- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/RazorPageGenerator/CreatePageModel.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/RazorPageGenerator/DeletePageModel.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/RazorPageGenerator/DetailsPageModel.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/RazorPageGenerator/EditPageModel.cshtml
- src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Templates/RazorPageGenerator/ListPageModel.cshtml
Fixes #633 
cc @Eilon @mlorbetske
> Use entitysetvariable in razorpages

- test/VS.Web.CG.EFCore.Test/TestModels/TestModel.cs
Preempts build break from https://github.com/aspnet/EntityFrameworkCore/pull/10604
> Better fix for getting standalone SQL Server convention set

- src/VS.Web.CG.Mvc/Templates/Identity/ScaffoldingReadme.txt
Proposed README updates for the Identity scaffolder.
> Identity scaffolder README updates

- build/dependencies.props
- src/VS.Web.CG.Templating/RazorTemplating.cs
- src/VS.Web.CG.Templating/TemplateRazorProjectItem.cs
> Move to RazorProjectEngine.

- NuGetPackageVerifier.json
- build/dependencies.props
- src/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
This should unblock Update Universe.
> React to new dependencies

- NuGetPackageVerifier.json
Just an FYI, pushing this to unblock the CI.
> Update Universe failure

- build/dependencies.props
- src/PackGlobalTool.targets
- src/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.nuspec
Related aspnet/dotnettools/issues/400
cc @mlorbetske
> Remove MS.NETCore.Platforms dependency from global tool.

- src/VS.Web.CG.Mvc/Templates/Startup/ReadMe.cshtml
- test/E2E_Test/Compiler/Resources/ReadMe/Readme.txt
> Readme fix route to routes  issue 718

- src/VS.Web.CG.Mvc/Common/RequiredFileEntity.cs
- src/VS.Web.CG.Mvc/RazorPage/EFModelBasedRazorPageScaffolder.cs
- src/VS.Web.CG.Mvc/RazorPage/RazorPageScaffolderBase.cs
Fixes #721 
Checks for an existing _ValidationScriptsPartial in the Pages/Shared/ directory in addition to checking in Pages/
> Razor validation scripts partial smarter conditional add

- src/VS.Web.CG.Mvc/Templates/Identity/IdentityHostingStartup.cshtml
> Change add identity to add default identity

- src/VS.Web.CG.Mvc/Identity/IdentityGenerator.cs
- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorFile.cs
- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorFilesConfig.cs
- src/VS.Web.CG.Mvc/Identity/identitygeneratorfilesconfig.json
> _LoginPartial is looked for in multiple places, not generated if exists

- src/VS.Web.CG.Msbuild/Target/build/Microsoft.VisualStudio.Web.CodeGeneration.Tools.targets
This is a follow up fix to #757 
cc @vijayrkn @seancpeters @muratg
> Change the location of codegeneration msbuild task dll from netcoreapp2.0 to netcoreapp2.1

- src/VS.Web.CG.Mvc/Templates/Identity/ScaffoldingReadme.cshtml
Fixes #764 
cc @vijayrkn @mkArtakMSFT @javiercn
> Add instructions for ef migrations to readme.

- src/VS.Web.CG.Design/Program.cs
- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
- src/VS.Web.CG.Mvc/Templates/Identity/Data/ApplicationDbContext.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/IdentityHostingStartup.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Account.ConfirmEmail.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Account.ExternalLogin.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Account.ForgotPassword.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Account.Login.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Account.LoginWith2fa.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Account.LoginWithRecoveryCode.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Account.Logout.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Account.Register.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Account.ResetPassword.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Manage/Account.Manage.ChangePassword.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Manage/Account.Manage.DeletePersonalData.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Manage/Account.Manage.Disable2fa.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Manage/Account.Manage.DownloadPersonalData.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Manage/Account.Manage.EnableAuthenticator.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Manage/Account.Manage.ExternalLogins.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Manage/Account.Manage.GenerateRecoveryCodes.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Manage/Account.Manage.Index.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Manage/Account.Manage.PersonalData.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Manage/Account.Manage.ResetAuthenticator.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Manage/Account.Manage.SetPassword.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Manage/Account.Manage.ShowRecoveryCodes.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Manage/Account.Manage.TwoFactorAuthentication.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/_ViewImports.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/ScaffoldingReadme.cshtml
Are these changes expected to be brought back to dev?
> Merge release/2.1

- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Account.ConfirmEmail.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Account.ExternalLogin.cs.cshtml
> AllowAnonymous for external login providers and confirm email

- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Create.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Edit.cshtml
The model propery was missing by generating a crud razorpage wich has a boolean
> fix bug by missing model propperty for checkbox in generatod razor pages

- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorFilesConfig.cs
- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
- test/VS.Web.CG.Mvc.Test/IdentityGeneratorTemplateModelBuilderTests.cs
This PR targets release/2.1 and replaces #787 which was targeted against the dev branch.
This also incorporates the suggestion from @prafullbhosale to strip multiple lead slashes if needed.
> Fixes the tilde directory problem with existing layout files

- src/VS.Web.CG.Mvc/Templates/Identity/Pages/_Layout.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Pages/_ValidationScriptsPartial.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/_ValidationScriptsPartial.cshtml
- src/VS.Web.CG.Mvc/Templates/ViewGenerator/_ValidationScriptsPartial.cshtml
- test/E2E_Test/Compiler/Resources/SharedViews/_ValidationScriptsPartial.cshtml
- test/VS.Web.CG.Mvc.Test/CdnScriptTagTests.cs
Resolves https://github.com/aspnet/Scaffolding/issues/794
> Update CDN to pull jQuery to 3.3 and update SRI hashes

- src/VS.Web.CG.Mvc/MessageStrings.Designer.cs
- src/VS.Web.CG.Mvc/MessageStrings.resx
> Typo fix: s/Pazor/Razor/

- src/VS.Web.CG.Mvc/Templates/Identity/Pages/Error.cs.cshtml
Same as https://github.com/aspnet/templating/commit/e403187be35a25560692aaa7ded495e26bb3ad90
> Apply attribute to page model rather than handler

- Directory.Build.targets
- NuGetPackageVerifier.json
- build/dependencies.props
- build/repo.props
- src/VS.Web.CG.Design/VS.Web.CG.Design.csproj
- src/VS.Web.CG.Design/VS.Web.CG.Design.nuspec
- src/VS.Web.CG.Msbuild/Target/build/Microsoft.VisualStudio.Web.CodeGeneration.Tools.targets
- src/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
- test/Directory.Build.props
- test/Directory.Build.targets
- test/E2E_Test/E2E_Test.csproj
- test/Shared/MsBuildProjectSetupHelper.cs
- test/Shared/MsBuildProjectStrings.cs.in
- test/TestApps/ModelTypesLocatorTestWebApp/ModelTypesLocatorTestWebApp.csproj
- test/VS.Web.CG.Core.Test/CodeGeneratorsLocatorTests.cs
- test/VS.Web.CG.Sources.Test/CommonUtilitiesTests.cs
- test/VS.Web.CG.Templating.Test/TestCompilationService.cs
- test/VS.Web.CG.Tools.Test/VS.Web.CG.Tools.Test.csproj
Part of https://github.com/aspnet/Universe/issues/1243.
> Update TFM to netcoreapp3.0

- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Create.cshtml
> remove superfluous paren from razor create view

- ISSUE_TEMPLATE
The motivation for this is easier tracking of scaffolding issues, funneling VS users to the developer community. I considered adding something about keeping issues with scaffolded content here, and putting functional issues on developer community. But the line between the two is a bit grey, and would probably just confuse most users.
This is just a draft, so any suggestions / broad changes are welcome.
> [WIP] - First draft of an issue template for this repo

- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorCommandLineModel.cs
> adding the missing shoft version of the listfiles option for identity scaffolding

- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorFilesConfig.cs
- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
Also prevents Identity scaffolding from creating an empty Services folder.
> Fix identity scaffolding so it only generates the chosen pages, instead of all pages

- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorCommandLineModel.cs
- src/VS.Web.CG.Mvc/ParameterDefinitions/identity.json
> Correct referenced option name "listFiles" in the identity generator's "files" option description

- src/VS.Web.CG.Mvc/Identity/bootstrap3_identitygeneratorfilesconfig.json
- src/VS.Web.CG.Mvc/Identity/bootstrap4_identitygeneratorfilesconfig.json
> Add missing Identity template ShowRecoveryCodes in config.

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ConfirmEmail.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ExternalLogin.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ForgotPassword.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ForgotPasswordConfirmation.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Login.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.LoginWith2fa.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.LoginWithRecoveryCode.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Register.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ResetPassword.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ResetPasswordConfirmation.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.Disable2fa.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage._Layout.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap4/Create.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap4/Delete.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap4/Details.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap4/Edit.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap4/Empty.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap4/List.cshtml
- src/VS.Web.CG.Mvc/Templates/ViewGenerator/Bootstrap4/Create.cshtml
- src/VS.Web.CG.Mvc/Templates/ViewGenerator/Bootstrap4/Delete.cshtml
- src/VS.Web.CG.Mvc/Templates/ViewGenerator/Bootstrap4/Details.cshtml
- src/VS.Web.CG.Mvc/Templates/ViewGenerator/Bootstrap4/Edit.cshtml
- src/VS.Web.CG.Mvc/Templates/ViewGenerator/Bootstrap4/Empty.cshtml
- src/VS.Web.CG.Mvc/Templates/ViewGenerator/Bootstrap4/List.cshtml
To match aspnet/Identity#1966 and aspnet/Templating#742.
> Titles in h1 instead of h2

- Directory.Build.props
- src/VS.Web.CG.Design/VS.Web.CG.Design.csproj
- src/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
Fix the file paths for code signing. cref https://github.com/aspnet/BuildTools/pull/766
> Fix microbuild signing configuration

- global.json
- korebuild-lock.txt
- src/VS.Web.CG.Mvc/VS.Web.CG.Mvc.csproj
React to https://github.com/aspnet/BuildTools/pull/788
Resolves https://github.com/aspnet/AspNetCore-Internal/issues/1181
FYI @Eilon
> Update code signing config to exclude .ttf and .js files

- build/dependencies.props
- version.props
Fixes per @natemcmaster suggestions
> Second fix for 2.2.1-servicing release

- src/VS.Web.CG.Mvc/Identity/bootstrap4_identitygeneratorfilesconfig.json
The entries removed herein correspond to the files removed in #950
> Removing entries for deleted files from the identity bootstrap4 config

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.Logout.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Logout.cs.cshtml
Fixes https://github.com/aspnet/AspNetCore/issues/4003
> Fix issue with logout

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Manage/Account.Manage.DeletePersonalData.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.DeletePersonalData.cs.cshtml
This was fixed upstream in https://github.com/aspnet/AspNetCore/commit/3624da47ae932d00b157be854593763375df76d9 and https://github.com/aspnet/AspNetCore/commit/01c1f7b187cacccb4fc5323a2543e99f61074ed5 but not in this repo.
> Fix spelling of deleting in Identity UI

- build/dependencies.props
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/_ViewImports.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/_ViewImports.cshtml
- src/VS.Web.CG.Templating/RazorTemplateBase.cs
- src/VS.Web.CG.Templating/VS.Web.CG.Templating.csproj
The generated output from some of the pages is not correct. This is due to 2 reasons:
- Errors in razor processing, per this bug: https://github.com/aspnet/AspNetCore/issues/10811
- Changes to the Identity API surface, particularlt IHostingEnvironment no longer being supported.
> Updating packages to 3.0.0-preview6 versions. Fixes for razor processing

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/_Layout.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/ScaffoldingReadme.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/SupportPages._ViewImports.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/SupportPages._ViewStart.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/_LoginPartial.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/_Layout.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/ScaffoldingReadme.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/SupportPages._ViewImports.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/SupportPages._ViewStart.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/_LoginPartial.cshtml
Fixes for https://github.com/aspnet/AspNetCore/issues/11880
> Identity content fixes

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Manage/Account.Manage.EnableAuthenticator.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.EnableAuthenticator.cshtml
Per MS style guide:
Avoid please except in situations where the customer is asked to do something inconvenient or the application or site is to blame for the situation.
Identical change in https://github.com/aspnet/AspNetCore/pull/11971
> Remove please from QR template

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/_Layout.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/_Layout.cshtml
Fixes https://github.com/aspnet/AspNetCore/issues/12676#event-2517102498
> Fix obsolete IHostingEnvironment reference

- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap4/Create.cshtml
> Remove extra paren

- build/dependencies.props
- build/sources.props
Updating the Scaffolding dependencies to Preview 9 packages
> Updating to Preview 9 packages

- build/dependencies.props
updating more packages to 3.0.0
> updating other preview packages to 3.0.0

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/_Layout.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/_Layout.cshtml
Fixes https://github.com/aspnet/AspNetCore/issues/14064
> Work around razor bug in layout

- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/_Layout.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/_Layout.cshtml
@vijayrkn it looks like there might also need to be corresponding changes in https://github.com/aspnet/Scaffolding/blob/167a8b5c626db13896e1e4fad65b5695be37da20/src/VS.Web.CG.Mvc/Identity/IdentityGeneratorFilesConfig.cs#L284
Fixes https://github.com/aspnet/AspNetCore/issues/13699
> Remove cookie consent and cdn from script tags

- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/_Layout.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/_Layout.cshtml
> Identity UI fixes

- build/dependencies.props
- build/sources.props
- version.props
- had to update Microsoft.CodeAnalysis.CSharp.Workspaces to 3.4.0-beta2 as that dependency was required.
> props updates for 3.1.0

- azure-pipelines.yml
adding build for internal branches and any prs.
> azure-pipeline update

- Aracde Migration.txt
- Directory.Build.targets
- README.md
- eng/Build.props
- eng/Signing.props
- eng/Versions.props
- test/TestApps/ClassLibrary1/ClassLibrary1.csproj
- test/TestApps/ClassLibrary2/ClassLibrary2.csproj
- test/TestApps/ModelTypesLocatorTestClassLibrary/ModelTypesLocatorTestClassLibrary.csproj
- test/TestApps/ModelTypesLocatorTestWebApp/ModelTypesLocatorTestWebApp.csproj
- Not packing some test apps.
- more info and formatting in readme.
- added an arcade migration txt file but TODO
> small changes in packing, readme.

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.Login.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.Login.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Login.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Login.cshtml
Scaffolding side matching fixes to https://github.com/aspnet/AspNetCore/pull/14901
> 3.1 cleanup resend email

- src/dotnet-aspnet-codegenerator/Resources.resx
Per https://github.com/aspnet/Scaffolding/pull/1109#commitcomment-35701958
> @Rick-Anderson - Can you please cherry-pick this change to master as well?
> Cherry Resources.resx

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/_Layout.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/_Layout.cshtml
Cherry pick of fix to 3.1 for https://github.com/aspnet/AspNetCore-ManualTests/issues/37
> Cherry pick line cleanup to 3.1

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.Login.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Login.cs.cshtml
Update Account.Login.cs.cshtml
cc @vijayrkn
> Cherry-pick from #1110 from Rick-Anderson/patch-3

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/ScaffoldingReadme.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/ScaffoldingReadme.cshtml
Improve readme for no-auth scenario
Fixes https://github.com/aspnet/AspNetCore/issues/16802
> Update scaffolding readme

- src/VS.Web.CG.Mvc/ParameterDefinitions/identity.json
Fixes https://github.com/aspnet/Scaffolding/issues/985
> Update description for the Identity scaffolder

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.ExternalLogin.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ExternalLogin.cs.cshtml
Fixes https://github.com/aspnet/AspNetCore-ManualTests/issues/44
This probably should also go into 3.1
> Scaffolding - Fix account confirmation for social logins 

- NuGet.config
- eng/Versions.props
This reverts commit bfc83f026d0b6f4d734fa0ebbf93d786c16dbda4.
> Revert "update 3.1 packages to preview3"

- NuGet.config
- eng/Versions.props
> Update 3.1 to GA

- src/VS.Web.CG.Mvc/Templates/Startup/ReadMe.cshtml
Change "may required" to "may require"
> Fix typo in scaffolding Readme

- src/VS.Web.CG.Mvc/Templates/ControllerGenerator/ApiControllerWithActions.cshtml
It should use controller name instead of fixed string "ApiWithActions"
> Fix ApiControllerWithActions Delete API comment

- src/VS.Web.CG.Mvc/Templates/ControllerGenerator/ApiControllerWithContext.cshtml
Fixes https://github.com/aspnet/Scaffolding/issues/983
Addresses the concern in docs at https://github.com/aspnet/AspNetCore.Docs/issues/14914.
/cc: @vijayrkn
> Return HTTP 204 from web API Delete action

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Manage/Account.Manage.ExternalLogins.cs.cshtml
think you missed this line Hao.
> removed invalid code

- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap3/Create.cshtml
was not removed for the bootstrap3 template.
> extra parenthesis removed

- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap3/Create.cshtml
The other fix was already in master.
> Bootstrap 3 template fix

- src/VS.Web.CG.Mvc/ParameterDefinitions/controller.json
- src/VS.Web.CG.Mvc/ParameterDefinitions/razorpage.json
- src/VS.Web.CG.Mvc/ParameterDefinitions/view.json
for razorpage, view , and controller.
> Add sqlite flag for "generator" -h

- src/VS.Web.CG.Mvc/Identity/bootstrap3_identitygeneratorfilesconfig.json
- src/VS.Web.CG.Mvc/Identity/bootstrap4_identitygeneratorfilesconfig.json
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.Login.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.ResendEmailConfirmation.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.ResendEmailConfirmation.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Login.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ResendEmailConfirmation.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ResendEmailConfirmation.cshtml
@deepchoudhery @vijayrkn I added two new files and updated the json file but I don't see them showing up in the dialog, did I miss updating something?
> Add new resend email confirmation

- global_install.cmd
- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorFilesConfig.cs
changed readme as not a template. added global_install to help debug(windows).
> Fixed identity readme

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.ExternalLogin.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ExternalLogin.cs.cshtml
This brings over the change from https://github.com/dotnet/aspnetcore/pull/18296.
> Set AuthenticationMethod for first Identity external login

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.ExternalLogin.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ExternalLogin.cs.cshtml
> Always send email for Identity's ExternalLogin

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.ResendEmailConfirmation.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ResendEmailConfirmation.cs.cshtml
@deepchoudhery this should fix the compilation issues, thanks!
> Fix missing input

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.RegisterConfirmation.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.ResendEmailConfirmation.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.RegisterConfirmation.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ResendEmailConfirmation.cs.cshtml
Fixes https://github.com/dotnet/aspnetcore/issues/20016
> Add missing usings to a few pages

- src/VS.Web.CG.Mvc/Templates/ControllerGenerator/ApiControllerWithContext.cshtml
- src/VS.Web.CG.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap3/CreatePageModel.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap4/CreatePageModel.cshtml
- src/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap4/EditPageModel.cshtml
- test/E2E_Test/Compiler/Resources/CarsController.txt
- test/E2E_Test/Compiler/Resources/CarsControllerWithDAL.txt
- test/E2E_Test/Compiler/Resources/CarsWithViewController.txt
- test/E2E_Test/Compiler/Resources/ProductsController.txt
> updating overposting url API template

- azure-pipelines.yml
> azure pipeline fix

- azure-pipelines.yml
- src/VS.Web.CG.Design/VS.Web.CG.Design.nuspec
- src/VS.Web.CG.EFCore/VS.Web.CG.EFCore.csproj
moved repo from github.com/aspnet/scaffolding to github.com/dotnet/scaffolding. updating repo apt.
> changing aspnet/scaffolding to dotnet/scaffolding

- NuGet.config
- eng/Versions.props
- global_install.cmd
removing unnecessary RestoreSources in Versions.props.
> Versions.props cleanup

- NuGet.config
- eng/Versions.props
- global_install.cmd
* Versions.props cleanup
* nuget.config cleanup
* updating CommandLineUtils.Sources package
* nit fix : indentation
> Versions.props cleanup (#1309)

- src/VS.Web.CG.Mvc/Templates/Startup/ReadMe.cshtml
I've change the template generated in ScaffoldingReadMe.txt to the new approach
> changed the readme generated by adding an area

- eng/Versions.props
> 3.1.3 version upgrade

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.Login.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Login.cs.cshtml
Missed the login.cs.cshtml fixes in the port of https://github.com/dotnet/aspnetcore/pull/7002
> Port missing fix to scaffolding

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.ResendEmailConfirmation.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ResendEmailConfirmation.cs.cshtml
Fixes https://github.com/dotnet/aspnetcore/issues/21827
> Fix incorrect abstract class

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.Logout.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Logout.cshtml
Port https://github.com/dotnet/aspnetcore/pull/22444/files
> Show logout button if logged in on logout

- eng/Versions.props
- global_install.cmd
Changes for 5.0-Preview 6 sdk.
> updated Versions.props with preview 6 packages.

- src/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs
- src/VS.Web.CG.EFCore/MessageStrings.Designer.cs
- src/VS.Web.CG.EFCore/MessageStrings.resx
- src/VS.Web.CG.Mvc/Common/EFValidationUtil.cs
- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
Removed due to it blocking the scenario on VS. VS should take care of this dependency and CLI users should refer to the official tutorial if needed. 
Check might be added back after the dependency changes on the VS side and if we feel there is a need for it.
> removed sqlite dependency check

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.Email.cs.cshtml
Fixes https://github.com/dotnet/aspnetcore/issues/23438
cc @blowdart
> Add missing encoding

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.PersonalData.cshtml
Set delete account button as a secondary action instead of a primary action.
This avoids having two primary buttons. Also delete your account is probably not what you want to do.
Cross-reference:
https://github.com/dotnet/aspnetcore/pull/24002
> Change btn class for delete button

- eng/Versions.props
Updating packages to 5.0.0-Preview 7. Did not update Microsoft.CodeAnalysis.Razor due to a version conflict with Microsoft.CodeAnalysis.CSharp.
> updating Version.props to 5.0.0-Preview7

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.Login.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.Register.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Login.cs.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Register.cs.cshtml
Parallel to https://github.com/dotnet/aspnetcore/pull/24202
> Use Compount Assignment to respect IDE0054

- eng/Versions.props
- global_install.cmd
- src/VS.Web.CG.Msbuild/ProjectContextWriter.cs
- src/VS.Web.CG.Msbuild/Properties/AssemblyInfo.cs
- src/VS.Web.CG.Msbuild/Target/build/Microsoft.VisualStudio.Web.CodeGeneration.Tools.targets
- src/VS.Web.CG.Msbuild/VS.Web.CG.Msbuild.csproj
- src/VS.Web.CG.Mvc/Identity/bootstrap3_identitygeneratorfilesconfig.json
- src/VS.Web.CG.Mvc/Identity/bootstrap4_identitygeneratorfilesconfig.json
- src/VS.Web.CG.Mvc/VS.Web.CG.Mvc.csproj
- src/dotnet-aspnet-codegenerator/Program.cs
- test/Directory.Build.props
- test/Shared/MSBuildProjectStrings.cs
- test/Shared/MsBuildProjectSetupHelper.cs
- test/Shared/TemporaryFileProvider.cs
- test/TestApps/ModelTypesLocatorTestWebApp/ModelTypesLocatorTestWebApp.csproj
- test/VS.Web.CG.Core.Test/CodeGeneratorsLocatorTests.cs
- test/VS.Web.CG.MSBuild.Test/ProjectContextWriterTests.cs
- test/VS.Web.CG.MSBuild.Test/TestBase.cs
- test/VS.Web.CG.MSBuild.Test/VS.Web.CG.MSBuild.Tests.csproj
- test/VS.Web.CG.Sources.Test/CommonUtilitiesTests.cs
- test/VS.Web.CG.Templating.Test/TestCompilationService.cs
- Uses project.assets.json to get project dependencies
- test fixes
- minor 3.1 identity fix
> 3.1.4 dependency fix

- azure-pipelines.yml
This reverts commit 4894dfcc8c5a10b86c503d581fed71259e0950d0.
> revert poli check on internal build for 3.1 releases

- NuGet.config
- eng/Versions.props
- src/VS.Web.CG.Core/DefaultCodeGeneratorAssemblyProvider.cs
- src/VS.Web.CG.Msbuild/ProjectContextWriter.cs
Early update for preview 8. Will have another one closer to the release.
> added feed, legacy support for dependencies

- src/VS.Web.CG.Mvc/ParameterDefinitions/identity.json
Would appreciate feedback @Rick-Anderson
> correcting identity help text

- src/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs
- src/VS.Web.CG.EFCore/MessageStrings.Designer.cs
- src/VS.Web.CG.EFCore/MessageStrings.resx
- src/VS.Web.CG.Mvc/Common/EFValidationUtil.cs
- src/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
* removing sqlite package check and exception.
* removed resource string
> removed sqlite dependency check (#1360)

- src/Shared/General/Messaging/ProjectInformationMessageHandler.cs
- src/VS.Web.CG.Design/ScaffoldingClient.cs
- src/VS.Web.CG.Utils/CommonUtilities.cs
- src/VS.Web.CG.Utils/DotNet/ResolvedReferenceExtensions.cs
helps unblock arcade changes coming in. Will open a ticket to track the issue and fix soon after.
> Suppress CA2200

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ForgotPassword.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Login.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Register.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ResendEmailConfirmation.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ResetPassword.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.ChangePassword.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.DeletePersonalData.cshtml
- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.Email.cshtml
Port https://github.com/dotnet/aspnetcore/commit/408b1ac44359b37b70fa3e2bbe9575fca7726ccd#diff-21991eaa64fb721f8b1c147a93e41db18770b15bda51482c5c99745e7d850f0e and https://github.com/dotnet/aspnetcore/commit/f67413e072764e0b0d989fe74080959419c5feee#diff-21991eaa64fb721f8b1c147a93e41db18770b15bda51482c5c99745e7d850f0e
> Accessibility and autocomplete UI updates

- src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.ConfirmEmail.cshtml
Port of https://github.com/dotnet/aspnetcore/pull/25486/files
> Add status message to ConfirmEmail

- NuGet.config
- eng/Versions.props
- global.json
- src/VS.Web.CG.Contracts/VS.Web.CG.Contracts.csproj
- src/VS.Web.CG.Core/VS.Web.CG.Core.csproj
- src/VS.Web.CG.Design/VS.Web.CG.Design.csproj
- src/VS.Web.CG.EFCore/VS.Web.CG.EFCore.csproj
- src/VS.Web.CG.Msbuild/VS.Web.CG.Msbuild.csproj
- src/VS.Web.CG.Mvc/VS.Web.CG.Mvc.csproj
- src/VS.Web.CG.Templating/VS.Web.CG.Templating.csproj
- src/VS.Web.CG.Utils/VS.Web.CG.Utils.csproj
- src/VS.Web.CG/VS.Web.CG.csproj
- src/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
- test/Directory.Build.props
- test/E2E_Test/E2E_Test.Tests.csproj
- test/TestApps/ClassLibrary1/ClassLibrary1.csproj
- test/TestApps/ClassLibrary2/ClassLibrary2.csproj
- test/TestApps/ModelTypesLocatorTestClassLibrary/ModelTypesLocatorTestClassLibrary.csproj
- test/TestApps/ModelTypesLocatorTestWebApp/ModelTypesLocatorTestWebApp.csproj
- test/TestApps/PreviousPackage/PreviousPackage.csproj
- test/TestApps/StablePackage/StablePackage.csproj
- test/VS.Web.CG.Tools.Test/VS.Web.CG.Tools.Tests.csproj
- tools/VS.Web.CG.Design-anycpu/VS.Web.CG.Design-anycpu.csproj
- tools/VS.Web.CG.Design-arm/VS.Web.CG.Design-arm.csproj
- tools/VS.Web.CG.Design-arm64/VS.Web.CG.Design-arm64.csproj
> initial 6.0.0 update.

- azure-pipelines.yml
azure pipeline trigger for internal builds for the main branch
> adding pipeline trigger for main

- eng/Versions.props
- global.json
- global_install.cmd
- src/VS.Web.CG.Contracts/VS.Web.CG.Contracts.csproj
- src/VS.Web.CG.Core/VS.Web.CG.Core.csproj
- src/VS.Web.CG.Design/VS.Web.CG.Design.csproj
- src/VS.Web.CG.EFCore/VS.Web.CG.EFCore.csproj
- src/VS.Web.CG.Msbuild/VS.Web.CG.Msbuild.csproj
- src/VS.Web.CG.Mvc/VS.Web.CG.Mvc.csproj
- src/VS.Web.CG.Templating/VS.Web.CG.Templating.csproj
- src/VS.Web.CG.Utils/VS.Web.CG.Utils.csproj
- src/VS.Web.CG/VS.Web.CG.csproj
- src/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
- test/Directory.Build.props
- test/E2E_Test/E2E_Test.Tests.csproj
- test/TestApps/ClassLibrary1/ClassLibrary1.csproj
- test/TestApps/ClassLibrary2/ClassLibrary2.csproj
- test/TestApps/ModelTypesLocatorTestClassLibrary/ModelTypesLocatorTestClassLibrary.csproj
- test/TestApps/ModelTypesLocatorTestWebApp/ModelTypesLocatorTestWebApp.csproj
- test/TestApps/PreviousPackage/PreviousPackage.csproj
- test/TestApps/StablePackage/StablePackage.csproj
- test/VS.Web.CG.Tools.Test/VS.Web.CG.Tools.Tests.csproj
- tools/VS.Web.CG.Design-anycpu/VS.Web.CG.Design-anycpu.csproj
- tools/VS.Web.CG.Design-arm/VS.Web.CG.Design-arm.csproj
- tools/VS.Web.CG.Design-arm64/VS.Web.CG.Design-arm64.csproj
- added System.Collections.Immutable, System.ComponentModel.Annotations (dotnet/runtime) versions to avoid conflict.
- reverted project tfms to net5.0 for now.
> reverting to 5.0 sdk, 5.0 tfm until 6.0 stablizes

- src/VS.Web.CG.Msbuild/ProjectContextWriter.cs
- test/VS.Web.CG.MSBuild.Test/ProjectContextWriterTests.cs
> added lower case check for package paths (#1493)

- azure-pipelines.yml
- eng/Publishing.props
for enabling internal pipelines.
> added Publishing.props to update to V3 publish

- NuGet.config
- eng/Versions.props
- global_install.cmd
- global_install.sh
- test/TestApps/ModelTypesLocatorTestWebApp/ModelTypesLocatorTestWebApp.csproj
- updated versions.
- fix tests in ModelTypesLocatorTestWebApp. EFCore test helpers have had breaking changes. Using the older packages for test currently but will fix for next preview. Issue here - #1519
> updated versions for 6.0-preview2

- eng/Versions.props
> updated 6.0-preview2 package versions

- CODE-OF-CONDUCT.md
- README.md
> Updating the readme

- eng/Versions.props
- test/Scaffolding/VS.Web.CG.EFCore.Test/TestModels/TestModel.cs
- updated Version.props
- patched #1519 for now with a cast.
> added cast for test. updated Version.props

- src/MsIdentityScaffolding/README.md
- tools/dotnet-msidentity/README.md
updated dotnet-msidentity readme with install commands for the pre release version of the tool.
> update readme with install command

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/MsAADTool.cs
- Only the first 50 (sorted by creation time) AAD apps and Service Principals were being returned in the --list-* commands.
- Fixed to return all available apps and service principals.
> finding all aad apps through NextPageRequest on GraphServiceClient

- eng/Versions.MSIdentity.props
> updated dotnet-msidentity to 1.0.0-preview2

- tools/dotnet-msidentity/README.md
Updating the readme. I have some other changes in mind that I'd like to make next week. After that I'll ask Jean-Marc to take a look.
> updating msidentity readme

- test/Scaffolding/TestApps/PreviousPackage/Nuget.config
Should fix Nuget Security Analysis error
> removed unneccessary Nuget.config with multiple feeds

- eng/Versions.props
Updating .NET 6 Preview 7 packages for dotnet-aspnet-codegenerator
> updated CodeAnalysis version to 4.0.0-3.final

- global.json
Fixes issues in macOS (command line tool and VS Mac) and linux environments
> revert 6.0-rc1 sdk back to 6.0 Preview 7

- eng/Versions.props
> Updated Versions.props for initial rc1

- eng/Versions.props
package versions updated for 6.0-rc1 release.
> Update package versions in Versions.props

- azure-pipelines.yml
Tracking issue: https://github.com/dotnet/core-eng/issues/14276
> Switch to 1ES Servicing pools in release/6.0-rc1

- eng/Versions.props
Versions.props update. Will have another update on the next release .NET build
> initial Versions.props update for 6.0-rc2

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapi.json
Adds Scopes attribute when Calls Microsoft Graph or Calls a downstream API option is selected
Adds necessary using statements
Adds code for OnGet method
> Update Web API code modifier config

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapi.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapp.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/CodeChange/CodeChangeHelper.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/DocumentBuilder.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
- fixes duplicate `services.AddAuthorization` block being added.
- fixes WeatherForecastController.cs code changes for minimal app scenarios.
> code change fixes for dotnet-msidentity scenarios

- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/DocumentBuilder.cs
> attribute spacing fix cherry pick

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Microsoft.DotNet.MSIdentity.csproj
- added MSBuildLocator.RegisterDefaults call to load Microsoft.Build assemblies
> fix for MsIdentity by adding Microsoft.Build assembly using Microsoft.Build.Locator

- src/Scaffolding/VS.Web.CG.Mvc/RazorPage/RazorPageGeneratorTemplateModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/RazorPage/RazorPageWithContextTemplateModel.cs
Add `NullableEnabled` to `RazorPageGeneratorTemplateModel`
Fixes #1754
There are no tests for `RazorPages`.
> Add NullableEnabled to RazorPageGeneratorTemplateModel

- tools/dotnet-aspnet-codegenerator/ScaffoldingServer.cs
> ScaffoldingServer: do not dispose of null members

- eng/Versions.props
Updated Version.props. Will update dependencies and project tfms when the alpha packages stabilize.
> only changed version to 7.0, no package/dependecy updates

- src/Scaffolding/VS.Web.CG.Core/CodeGeneratorActionsService.cs
1. Trace reading a template file by CodeGeneratorActionsService.
2. Add a static logger.
Tracing messages do not require tests.
> CodeGeneratorActionsService: trace template

- NuGet.config
- eng/Versions.props
- scripts/install-aspnet-codegenerator.cmd
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Microsoft.DotNet.MSIdentity.csproj
- src/Scaffolding/VS.Web.CG.Mvc/Identity/identityMinimalHostingChanges.json
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/MessageStrings.Designer.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Microsoft.DotNet.Scaffolding.Shared.csproj
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectModelHelper.cs
- tools/dotnet-msidentity/dotnet-msidentity.csproj
- initial .NET 7 Preview 1 update for dotnet-aspnet-codegenerator. 
- minor fix for Identity scaffolding (indenting in Program.cs)
> initial 7.0-preview1 + minor indent fix

- src/Scaffolding/VS.Web.CG.EFCore/DbContextEditorServices.cs
- to avoid potential null reference warning.
- in Program.cs for the `builder.Configuration.GetConnectionString("DbContext")` call.
***before***
```
builder.Services.AddDbContext<DbContext>(options =>
options.UseSqlServer(builder.Configuration.GetConnectionString("DbContext")
```
***after***
```
builder.Services.AddDbContext<DbContext>(options =>
options.UseSqlServer(builder.Configuration.GetConnectionString("DbContext") ?? throw new InvalidOperationException("Connection string 'DbContext' not found.")));
```
> adding InvalidIOperationException if Configuration.GetConnectionString

- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGenerator.cs
EF usings were being added even in non-EF scenarios, minor fix.
> only adding Ef usings when DbContextNamespace is present

- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorFilesConfig.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
> Cherry-picking #1866

- eng/Versions.MSIdentity.props
> bumping msidentity version to 1.0.3

- azure-pipelines.yml
- global.json
- test/Directory.Build.props
- test/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity.Tests/Microsoft.DotNet.MSIdentity.Tests.csproj
- test/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity.UnitTests.Tests/Microsoft.DotNet.MSIdentity.UnitTests.Tests.csproj
- test/Scaffolding/E2E_Test/E2E_Test.Tests.csproj
- test/Scaffolding/VS.Web.CG.Tools.Test/VS.Web.CG.Tools.Tests.csproj
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/Microsoft.DotNet.Scaffolding.Shared.Tests.csproj
bumped to 7.0.0 preview 3 sdk.
> bumped sdk version in global.json

- eng/Versions.MSIdentity.props
> bump dotnet-msidentity version

- src/Scaffolding/VS.Web.CG.EFCore/DbContextEditorServices.cs
- src/Scaffolding/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs
- src/Scaffolding/VS.Web.CG.EFCore/IDbContextEditorServices.cs
- test/Scaffolding/VS.Web.CG.EFCore.Test/DbContextEditorServicesTests.cs
- test/Scaffolding/VS.Web.CG.EFCore.Test/compiler/resources/DbContextNullable_After.txt
- test/Scaffolding/VS.Web.CG.EFCore.Test/compiler/resources/DbContext_Before.txt
if nullable is enabled for existing db contexts. Fixes warnings when nullable is enabled for projects.
> adding nullable entity sets

- src/Scaffolding/VS.Web.CG.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
not using hardcoded 'Movie', using the correct entity set variable.
PS : Was causing issues in the MVC Scaffolding w/ View and EF.
> using correct entityset variable instead.

- src/Scaffolding/VS.Web.CG.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
> add missing bracket

- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApi.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiNoClass.cshtml
Summary of the changes
- Added `@:.WithTags(nameof(@modelName))` to the four minimalapi endpoint scaffolders when OpenAPI option is selected
Fixes #1886 - implementation as discussed in issue
https://github.com/dotnet/aspnetcore/wiki/Engineering-guidelines
> Add tags to minimalapi endpoints templates

- eng/Versions.props
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/Scaffolding/VS.Web.CG.EFCore/DbContextEditorServices.cs
- src/Scaffolding/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs
- src/Scaffolding/VS.Web.CG.EFCore/IDbContextEditorServices.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/identityMinimalHostingChanges.json
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/CodeChange/CodeChangeHelper.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/DocumentBuilder.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
- test/Scaffolding/VS.Web.CG.EFCore.Test/DbContextEditorServicesTests.cs
- test/Scaffolding/VS.Web.CG.EFCore.Test/EntityFrameworkServicesTests.cs
- test/Scaffolding/VS.Web.CG.Mvc.Test/IdentityGeneratorTests.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/DocumentBuilderTestBase.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/DocumentBuilderTests.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/weo444pm.j3w~
Cherry-picks from main, bumped up version.
> 6.0 servicing

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/AzureAdProperties.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorwasm_client.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/AppSettingsModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- test/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity.UnitTests.Tests/AppProvisioningToolTests.cs
Refactoring appsettings modification logic, behind the scenes fix so functionality should not be affected
> Refactor appsettings.json modification logic

- eng/Versions.MSIdentity.props
- eng/Versions.props
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/AzureAdProperties.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorserver.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorwasm_client.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_minimal_api.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapi.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapp.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/AppSettingsModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/IdentityHostingStartup.cshtml
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/CodeChange/CodeSnippet.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/DocumentBuilder.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/MsBuild/MsBuildProjectContextBuilder.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectContextHelper.cs
- test/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity.UnitTests.Tests/AppProvisioningToolTests.cs
Servicing for : 
- dotnet-aspnet-codegenerator --> v6.0.6
- dotnet-msidentity --> v1.0.5
Cherry-picks:
- #1901
- #1903
- #1905
- #1907
- #1909
> Servicing for release/6.0

- src/Scaffolding/VS.Web.CG.Design/VS.Web.CG.Design.csproj
for issues with win-arm scenarios.
tested x64 scenarios on win, macOS, macOS M1, Ubuntu --> looks good.
tested arm scenarios on win-arm --> looks good.
These are majority of the scenarios and machines available to me, I'll fix for other platforms as the need arises.
> not packaging other runtimes in CG.Design

- eng/Versions.MSIdentity.props
> bump msidentity version: (#1920)

- Directory.Build.props
- eng/Versions.props
> forcing version for System.Configuration.ConfigurationManager (#1924)

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/AzureAdProperties.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
> Fix default scopes

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/AzureAdProperties.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorwasm.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/AppSettingsModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
Cherry picking Bug fixes for Identity 1.0.5
> Dev/zahalzel/105 fix on rel 6.0

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorwasm_hosted.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapi.json
Adds the code updates to Program.cs for Blazor Hosted scenario when either or both of the options checkboxes are checked in VS.
> Update code modifierconfigs for Blazor Hosted Calls Graph, Calls Downstream API

- eng/Versions.props
- src/Scaffolding/VS.Web.CG.Design/VS.Web.CG.Design.csproj
- src/Scaffolding/VS.Web.CG.EFCore/Templates/DbContext/NewLocalDbContext.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/identityMinimalHostingChanges.json
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGeneratorCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/ModelMetadataUtilities.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/DocumentBuilder.cs
Cherry-picks from main:
- not packaging other runtimes in CG.Design (#1912 )
- added support for sqlite for minimal api scaffolding. (#1915 )
- fix nullable warnings for new db context template. (#1916 )
- fixed identity Program.cs changes (#1940 )
> 6.0.7 servicing

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/ProjectDescriptions/dotnet_webapp.json
Cherry-pick webforms fix onto release/6.0
> Cherry-pick webforms fix onto release/6.0

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/ProjectDescriptions/dotnet_webapp.json
Fix for this bug: 
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1543938/
To test, from Visual Studio
1. File > New project > ASP.NET Web Application (.NET Framework) > Web Forms, select 'Microsoft identity platform' > Create
2. After Dependency configuration progress panel appearing > Next > Select Tenant :WTETestAd05(WTETestAd05.onmicrosoft.com), select an existing or create a new Owned applications > Next > Next > Finish
After click finish, there are some error appear
> Update code modifier config for WebForms projects

- tools/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
- tools/dotnet-msidentity/dotnet-msidentity.csproj
- tools/dotnet-scaffold/dotnet-scaffold.csproj
> bumping up NuGet.Packaging to fix vulnerability. (#1947)

- Directory.Build.props
- eng/Versions.props
- test/Directory.Build.props
- tools/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
- tools/dotnet-msidentity/dotnet-msidentity.csproj
- tools/dotnet-scaffold/dotnet-scaffold.csproj
> fix comp governance issue 

- eng/Versions.props
bumping from 7.0-preview to 7.0-preview6
> bumping up version to 7.0-preview6

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorwasm_hosted.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapi.json
Adds code when "calls graph" or "downstream API" is selected for blazor wasm hosted
> Update configs (#1939) [code modifications for checkboxes for BlazorWasm Hosted]

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeWriter.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ConsoleLogger.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/IConsoleLogger.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/JsonResponse.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
Adds "Output" property to JsonResponse, and refactors some of the console logging logic.
> Updates for console logging

- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.PersonalData.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Account.ExternalLogin.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Account.ForgotPassword.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Account.Login.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Account.LoginWith2fa.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Account.LoginWithRecoveryCode.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Account.Register.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Account.ResendEmailConfirmation.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Account.ResetPassword.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Manage/Account.Manage.ChangePassword.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Manage/Account.Manage.DeletePersonalData.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Manage/Account.Manage.Email.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Manage/Account.Manage.EnableAuthenticator.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Manage/Account.Manage.Index.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Manage/Account.Manage.SetPassword.cshtml
UI changes from [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/tree/main/src/Identity/UI/src).
> UI changes for identity for .NET 7

- eng/Versions.MSIdentity.props
- eng/Versions.props
For new .NET 7 preview packages for dotnet-aspnet-codegenerator and new 2.0.0-Preview.x packages for dotnet-msidentity.
> bumped both msidentity and aspnet-codegenerator

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/AzureAdProperties.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeWriter.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/AppSettingsModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/ProjectDescriptions/ProjectTypes.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/ProvisioningToolOptions.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ConsoleLogger.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/IConsoleLogger.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/JsonResponse.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
- test/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity.UnitTests.Tests/AppProvisioningToolTests.cs
- test/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity.UnitTests.Tests/MicrosoftIdentityPlatformApplicationManagerTests.cs
For: 
- dotnet-aspnet-codegenerator v6.0.8
- dotnet-msidentity v1.0.7
> 6.0.8 cherry picks

- src/Scaffolding/VS.Web.CG.Mvc/Identity/identityMinimalHostingChanges.json
Changes for scaffolding templates parity with aspnetcore templates https://github.com/dotnet/aspnetcore/pull/42802
- removed all references where CodeBlock.Block was adding app.UseAuthentication
- will be carried over from main to 7.0.0-rc1 branch
- only doing dotnet-aspnet-codegenerator changes for now. 
- dotnet-msidentity changes will follow soon, need a bigger rework.
> removed identity config changes adding or checking for app.UseAuthentication

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
Fixing a string format bug, wrong number of parameters
> Fix string bug

- test/Scaffolding/Shared/MSBuildProjectStrings.cs
- test/Scaffolding/Shared/MsBuildProjectSetupHelper.cs
- test/Scaffolding/VS.Web.CG.MSBuild.Test/ProjectContextWriterTests.cs
Test for scenario where models/context files were not being detected in a referenced library.
> adding TestProjectContextWithReferencedModel test

- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
for Minimal Endpoints EF scenarios:
- missing db.Update(MODEL_CLASS) from MapPut extension.
- addresses #1964
> added db.Update(Model) to MapPut

- eng/Versions.MSIdentity.props
- eng/Versions.props
- src/Scaffolding/VS.Web.CG/VS.Web.CG.csproj
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Microsoft.DotNet.Scaffolding.Shared.csproj
update package versions to rtm to get ready for GA release.
- not setting specific version for System.Collections.Immutable.
> update .NET 7.0 Versions.props

- eng/Versions.props
- test/Scaffolding/Shared/MSBuildProjectStrings.cs
- test/Scaffolding/Shared/MsBuildProjectSetupHelper.cs
- upgrade projects used by `Microsoft.VisualStudio.Web.CodeGeneration.MSBuild.ProjectContextWriterTests` in `Microsoft.VisualStudio.Web.CodeGeneration.MsBuildProjectStrings`
> upgrade sample unit test projects for msbuild tests.

- eng/Version.Details.xml
- eng/Versions.props
added darc dependencies
- waiting for versions to populate before rearranging Versions.props dependencies.
- will be porting to release/6.0 and release/7.0
> added darc aspnetcore, efcore, and runtime deps

- azure-pipelines.yml
- increase builds timeouts from 60 to 120 minutes
- change Windows images for builds
> pipeline builds changes

- azure-pipelines.yml
increase timeoutInMinutes from 120 to 180 for Windows_NT job.
> increase windows build time.

- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
Similar to #2038, fixing #1964 for .NET 6 scenarios.
> edit map put endpoints net6

- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGenerator.cs
added an additional `if` statement.
> adding HttpResults package indepedently

- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApi.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiNoClass.cshtml
Addressing #2074
- flipping the results type in the if statement to fix the template.
> flipping the results type in template

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
Adds newline for the output resulting from modifying code files
> Fix newline

- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectModelHelper.cs
updating the backup dictionary for net8.0 scenarios.
> add net8.0 to ShortTfmDictionary

- .editorconfig
- set `dotnet_sort_system_directives_first` to true
> .editorconfig edit

- scripts/install-aspnet-codegenerator.cmd
- scripts/install-aspnet-codegenerator.sh
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorTemplateModelBuilder.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/EFValidationUtil.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/SharedConstants.cs
> minimal api templates update (#2269)

- eng/Versions.props
remove unused lines in Versions.props for release/6.0
> clean version props

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/ProvisioningToolOptions.cs
- src/Scaffolding/VS.Web.CG.Design/Program.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectContextExtensions.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectContextHelper.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectModelHelper.cs
- test/Scaffolding/VS.Web.CG.MSBuild.Test/ProjectContextWriterTests.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/DocumentBuilderTestBase.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/ProjectModifierHelperTests.cs
> cherry picking #2061

- NuGet.config
- build/sources.props
- scripts/install-aspnet-codegenerator.sh
fixing NuGet.config and build/sources.props
> update 2.1 feeds

- src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap5/Pages/Account/Manage/Account.Manage.DownloadPersonalData.cs.cshtml
minor fix to `src\Scaffolding\VS.Web.CG.Mvc\Templates\Identity\Bootstrap5\Pages\Account\Manage\Account.Manage.DownloadPersonalData.cs.cshtml`
- changed IHeaderDictionary.Add to IHeaderDictionary.TryAdd
> fix to Account.Manage.DownloadPersonalData.cs

- eng/Versions.MSIdentity.props
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeFiles/WebApp/_LoginPartial.cshtml.txt
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapp.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapp_mvc.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/ProjectDescriptions/ProjectTypes.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/ProjectDescriptions/dotnet_webapp_mvc.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.Designer.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.resx
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/CodeChange/Method.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/DocumentBuilder.cs
* Add web app MVC code modifier
* MVC code modifier updates
* remove debugger
* Revert tests
* Bump version to 2.0.2
> Add web app MVC code modifier (#2314)

- scripts/install-msidentity.cmd
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Microsoft.DotNet.MSIdentity.csproj
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Microsoft.DotNet.Scaffolding.Shared.csproj
- tools/dotnet-msidentity/dotnet-msidentity.csproj
Change for msidentity tool to multi-target (net6, net7, net8)
> Target net6, net7, and net8

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapp_mvc.json
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
Cherry-pick for fixing code modifier for the MVC Web App scenario
> MVC code modifier fix

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/DeveloperCredentials/DeveloperCredentialsReader.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/DeveloperCredentials/MsalTokenCredential.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.Designer.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.resx
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/GraphObjectRetriever.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/MsAADTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/ProvisioningToolOptions.cs
- tools/dotnet-msidentity/Program.cs
- tools/dotnet-msidentity/ProvisioningToolOptionsBinder.cs
- tools/dotnet-scaffold/Program.cs
Adds an optional "Instance" input parameter, so that we can use the tool on other clouds besides the Azure Public cloud, such as the government cloud, the China cloud, etc.
> Add input parameter for Instance

- Directory.Build.props
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Microsoft.DotNet.Scaffolding.Shared.csproj
- test/Scaffolding/Shared/MSBuildProjectStrings.cs
- test/Scaffolding/VS.Web.CG.MSBuild.Test/VS.Web.CG.MSBuild.Tests.csproj
- tools/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
> 6.0.14 servicing

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/ProjectDescription/ProjectDescriptionReader.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/ProjectDescriptions/dotnet_webapp.json
* Fix string for default Project Description
* Add back check for Startup.cs, for .NET Framework projects
> Fix string for default Project Description (#2373)

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/ApplicationParameters.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/AzureAdProperties.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorserver.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorwasm.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapp.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/ProjectModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.Designer.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.resx
- Adds support for CIAM tenants
- CIAM info: https://learn.microsoft.com/en-us/azure/active-directory/external-identities/customers/overview-customers-ciam
- Minor code modifier config refactors
> CIAM updates

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/AzureAdProperties.cs
- tools/dotnet-msidentity/README.md
- tools/dotnet-msidentity/dotnet-msidentity.csproj
- Adds NuGet readme 
- Fix for Blazor WASM CIAM scenario (modify Authority parameter)
> Add path to NuGet readme, add fix for blazor CIAM

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/AzureAdProperties.cs
- tools/dotnet-msidentity/README.md
- tools/dotnet-msidentity/dotnet-msidentity.csproj
* Add path to NuGet readme, add fix for blazor CIAM
* Update readme formatting
* Update readme
* Update dotnet-msidentity.csproj
> Add path to NuGet readme, add fix for blazor CIAM (#2469)

- eng/Versions.MSIdentity.props
- scripts/install-msidentity.cmd
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/AzureAdProperties.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
Some minor CIAM fixes, and bumping up tool version
> Update version to 2.0.5

- eng/Versions.MSIdentity.props
- scripts/install-msidentity.cmd
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/AzureAdProperties.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
* Fixes for CIAM
* Bump up version
> Update version to 2.0.5 (#2476)

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/AzureAdProperties.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorserver.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_blazorwasm_hosted.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_minimal_api.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapi.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapp.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeModifierConfigs/cm_dotnet_webapp_mvc.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/AppSettingsModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/ProjectDescriptions/dotnet_blazor_server.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/ProjectDescriptions/dotnet_blazorwasm.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/ProjectDescriptions/dotnet_web.json
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.Designer.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.resx
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/MsAADTool.cs
- tools/dotnet-msidentity/Program.cs
- tools/dotnet-scaffold/Program.cs
> Ciam changes on release7

- eng/Versions.props
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/ApplicationParameters.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/AuthenticationParameters/AzureAdProperties.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/AppSettingsModifier.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/MsAADTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/ProvisioningToolOptions.cs
Updates for government cloud endpoints, requires using graph.microsoft.us for Microsoft Graph endpoint, and login.microsoftonline.us for the cloud Instance
> Updates for government cloud

- eng/Versions.MSIdentity.props
- scripts/install-msidentity.cmd
Updating dotnet msidentity tool version
> Set MsIdentity version to 2.0.6

- eng/Versions.MSIdentity.props
- scripts/install-msidentity.cmd
> Update msidentity version to 2.0.6

- eng/Versions.props
- global.json
- src/Scaffolding/VS.Web.CG.EFCore/IPropertyExtensions.cs
- src/Scaffolding/VS.Web.CG.EFCore/NavigationMetadata.cs
- test/Directory.Build.props
- test/Directory.Build.targets
- test/Scaffolding/E2E_Test/E2E_Test.Tests.csproj
current changes from release/8.0-preview7
added follow changes
- updated sdk for build to 8.0-preview7
- removed unnecessary xunit references.
> updates packages to .NET 8 P7

- eng/Versions.props
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
- Cherry-picking #2517 
- updated version to 7.0.10
> fix cosmosdb templates for endpoints scaffolding (cherry-pick)

- eng/Signing.props
- eng/Versions.MSIdentity.props
- eng/Versions.props
- scripts/install-msidentity.cmd
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/DeveloperCredentials/MsalTokenCredential.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/ResourceAndScope.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/TenantInformation.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/TokenCredentialAuthenticationProvider.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/AppProvisioningTool.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/GraphObjectRetriever.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Tool/MsAADTool.cs
- test/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity.UnitTests.Tests/MicrosoftIdentityPlatformApplicationManagerTests.cs
- test/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity.UnitTests.Tests/MsAADToolTests.cs
* Changes for updating MS Graph SDK and CIAM functionality
> Cherry-pick to release/7.0: Update Microsoft Graph SDK version (#2511)

- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
> fixed endpoints templates for ef scenarios

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
For some tenants, the owner is automaticaly added to the app registration, so we want to continue and not throw an error
> Add try/catch for adding owner to app registration

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
Surrounding the call to update the owner of the app registration with a try/catch, in case the owner has already been set
> Add try/catch (#2522)

- eng/Versions.MSIdentity.props
- scripts/install-msidentity.cmd
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.Designer.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.resx
Removes Azure AD references for the Microsoft Entra ID rebranding
> Remove Azure AD string references 

- NuGet.config
- eng/Version.Details.xml
- eng/Versions.props
- global.json
updating package versions in Versions.props
> 8.0.0-rc2 update

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.Designer.cs
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Properties/Resources.resx
Fixes downstream API scenario, and updates strings for removing AAD references
> Downstream api fix on release7

- azure-pipelines.yml
removing DotNet-Blob-Feed to fix build pipelines.
> removed DotNet-Blob-Feed from yaml

- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.tt
Addressing following issues:
- Edit page had incorrect class for input
- added `Enhance` to all EditForms
- added `NavigationManager.NavigateTo("notfound")` to navigate to 404 when apt.
> T4 template changes for blazor crud

- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.tt
- fix missing/invalid DbContext namespace in scaffolded .razor pages.
- fix missing/invalid Model namespace in scaffolder .razor pages.
- fix missing NavigationManager statement in Details.tt(razor)
> fix blazor CRUD template issues.

- src/Scaffolding/VS.Web.CG.Mvc/Blazor/BlazorModel.cs
> add support for addtional input tags for blazor CRUD scaffolding

- eng/Versions.props
- global.json
updated package version dependencies for .NET 9 Preview 1
> updated Versions.props

- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/CodeReaderWriter/CodeWriter.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/identityMinimalHostingChanges.json
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectModelHelper.cs
> add net9.0 tfm support + minor identity change.

- scripts/install-aspnet-codegenerator.cmd
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityHelper.cs
- test/Scaffolding/VS.Web.CG.Mvc.Test/IdentityHelperTests.cs
getting class name without a namespace was faulty, fixed.
> fix getting user class name.

- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityHelper.cs
- test/Scaffolding/VS.Web.CG.Mvc.Test/IdentityHelperTests.cs
cherry-picking from release/8.0
> fix getting user class name. (#2655)

- eng/Versions.props
> bump a couple dependencies for ComponentGovernance

- azure-pipelines-pr.yml
- azure-pipelines.yml
Migrate internal pipeline to MicroBuild template
- Cherry-picking from main.
> update pipelines (MicroBuild templates) for release/8.0

- azure-pipelines-pr.yml
- azure-pipelines.yml
Migrate internal pipeline to MicroBuild template
- Cherry-picking from main.
> update pipelines (MicroBuild templates) for release/9.0-preview2

- azure-pipelines-pr.yml
- azure-pipelines.yml
- global.json
- src/Scaffolding/VS.Web.CG.Utils/VS.Web.CG.Utils.csproj
- test/Scaffolding/Ext.ProjectModel.Tests/Ext.ProjectModel.Tests.csproj
- test/Scaffolding/Shared/MSBuildProjectStrings.cs
- test/Scaffolding/VS.Web.CG.EFCore.Test/VS.Web.CG.EFCore.Tests.csproj
- test/Scaffolding/VS.Web.CG.MSBuild.Test/VS.Web.CG.MSBuild.Tests.csproj
- test/Scaffolding/VS.Web.CG.Mvc.Test/VS.Web.CG.Mvc.Tests.csproj
- test/Scaffolding/VS.Web.CG.Sources.Test/VS.Web.CG.Sources.Tests.csproj
Migrate internal pipeline to MicroBuild template
- Cherry-picking from main.
> update pipelines (MicroBuild templates) for release/6.0

- azure-pipelines-pr.yml
- azure-pipelines.yml
- eng/common/templates-official/variables/pool-providers.yml
Migrate internal pipeline to MicroBuild template
- Cherry-picking from main.
> update pipelines (MicroBuild templates) for release/7.0

- eng/Version.Details.xml
- eng/common/SetupNugetSources.ps1
- eng/common/build.ps1
- eng/common/build.sh
- eng/common/native/init-compiler.sh
- eng/common/templates-official/job/job.yml
- eng/common/templates-official/job/publish-build-assets.yml
- eng/common/templates-official/job/source-index-stage1.yml
- eng/common/templates-official/steps/send-to-helix.yml
- eng/common/templates-official/steps/source-build.yml
- eng/common/templates/job/job.yml
- eng/common/tools.ps1
- global.json
cherry-picked #2658. #2669, #2670, #2681, #2683, #2688
> cherry picking arcade changes

- eng/Versions.props
- scripts/install-aspnet-codegenerator.cmd
- src/Scaffolding/VS.Web.CG.Mvc/BlazorIdentity/BlazorIdentityGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/BlazorIdentity/BlazorIdentityHelper.cs
- src/Scaffolding/VS.Web.CG.Mvc/BlazorIdentity/blazorIdentityChanges.json
fixing following scenarios:
- correct code injection in non top-level statement project.
- move other code injection to the json config model for correct insertion.
> fix blazor identity bugs

- azure-pipelines.yml
These images are no longer available in the build pools
> Remove -pt images which are no longer available

- src/Shared/Microsoft.DotNet.Scaffolding.Helpers/General/DotnetCommands.cs
I don't think we can assume that the output in the failure case is on stderr - I think it can (will?) be on stdout. So we should write out both to get the full picture of what's going on in the failure case.
> Tweak AddPackage output

- tools/dotnet-scaffold/Flow/Steps/ParameterDiscovery.cs
The primary purpose of this PR is to change the display of the project picker so that it shows the relative path to the project instead of the full path. At least for demo purposes I think this is cleaner. We can discuss how we want this all displayed long-term later.
Before:
After:
Along the way I also changed out the use of the Tuple to a concrete class, which makes the code a little easier to reason with. We'll have more changes here in the future so I'm not sure that class is permanent but I think it makes this more readable in the interim.
> Relative path for project selection

- eng/Versions.Scaffold.AspNet.props
- eng/Versions.Scaffold.Aspire.props
add preview numbers for the 1st party dotnet-scaffold tools
> add preview numbers

- eng/Versions.props
package versions in Versions.props were incorrect.
> correct package versions

- azure-pipelines-pr.yml
remove missing template `/eng/common/templates/variables/pool-providers.yml`
> edit azure pipelines pr.yml

- src/Shared/Microsoft.DotNet.Scaffolding.Helpers/Roslyn/ProjectModifier.cs
- tools/dotnet-scaffold-aspire/Commands/CachingCommand.cs
- tools/dotnet-scaffold-aspire/Commands/CodeModificationConfigs/Caching/redis-webapp-oc.json
- tools/dotnet-scaffold-aspire/Helpers/PackageConstants.cs
- tools/dotnet-scaffold-aspire/dotnet-scaffold-aspire.csproj
making code modifications for `caching --type redis-with-output-caching`
- making relevant `Program.cs` changes.
- added `redis-webapp-oc.json`
> redis-with-output-caching code modifications work now.

- eng/Version.Details.xml
- eng/common/core-templates/job/source-build.yml
- eng/common/core-templates/jobs/source-build.yml
- eng/common/core-templates/steps/enable-internal-runtimes.yml
- eng/common/core-templates/steps/enable-internal-sources.yml
- eng/common/core-templates/steps/source-build.yml
- eng/common/cross/armv6/sources.list.bookworm
- eng/common/cross/build-rootfs.sh
- eng/common/templates-official/steps/enable-internal-runtimes.yml
- eng/common/templates/steps/enable-internal-runtimes.yml
- global.json
> update .NET 9 Preview 5 branch

- eng/Versions.props
preview version in Versions.props
> bump preview version to 6.

- Directory.Build.props
- NOTICE.txt
Just created one file for the root of the project. Also they seem to be the same for all branches since it's based on the pipeline itself. 
- will just backport it to all GA branches after merge.
> added NOTICE.txt file to project root

- eng/Versions.props
- src/Scaffolding/VS.Web.CG.EFCore/DbContextEditorServices.cs
- src/Scaffolding/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs
- src/Scaffolding/VS.Web.CG.EFCore/EntityFrameworkServices.cs
- src/Scaffolding/VS.Web.CG.EFCore/IEntityFrameworkService.cs
- src/Scaffolding/VS.Web.CG.Mvc/Blazor/BlazorWebCRUDGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Blazor/blazorWebCrudChanges.json
- src/Scaffolding/VS.Web.CG.Mvc/ModelMetadataUtilities.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.tt
- test/Scaffolding/VS.Web.CG.Mvc.Test/BlazorWebCRUDGeneratorTests.cs
- test/Scaffolding/VS.Web.CG.Mvc.Test/ModelMetadataUtilitiesTest.cs
cherry-picking #2835 to release/8.0
> added code changes in json config and using IDbContextFactory now (cherry-pick)

- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/Blazor/BlazorCrud/BlazorCrudHelper.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/CodeModificationConfigs/blazorWebCrudChanges.json
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Create.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Create.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Delete.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Delete.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Details.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Details.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Edit.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Edit.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Index.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Index.tt
changes from #2835 but for `dotnet-scaffold-aspnet`
> update code modifier config and T4 templates

- eng/Versions.props
Quick PR to bump the version to 9.0-preview7 in main to differentiate from the release/9.0-preview6 branch builds
> Bump preview version to 7 in main

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Helpers/Steps/AddTextTemplatingStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/API/MinimalApi/MinimalApiCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/Blazor/BlazorCrud/BlazorCrudCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Commands/Blazor/BlazorCrud/BlazorCrudHelper.cs
adding `AddTextTemplatingStep` 
- inherits from `ScaffoldStep` 
- switched to using this for all commands that installed packages
> adding 'AddTextTemplatingStep'

- src/Scaffolding/VS.Web.CG.Core/VS.Web.CG.Core.csproj
- src/Scaffolding/VS.Web.CG.EFCore/VS.Web.CG.EFCore.csproj
- src/Scaffolding/VS.Web.CG.Mvc/VS.Web.CG.Mvc.csproj
- src/Scaffolding/VS.Web.CG.Templating/VS.Web.CG.Templating.csproj
- src/Scaffolding/VS.Web.CG.Utils/VS.Web.CG.Utils.csproj
- src/Scaffolding/VS.Web.CG/VS.Web.CG.csproj
> add PackageReadmeFile to scaffolding projects

- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Index.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Index.tt
> creating and disposing DbContext correctly in Index.razor now

- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Create.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Create.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Delete.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Delete.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Details.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Details.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Edit.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Edit.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Index.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorCrud/Index.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/MinimalApi/MinimalApi.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/MinimalApi/MinimalApi.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/MinimalApi/MinimalApiEf.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/MinimalApi/MinimalApiEf.tt
> minor fixes for minimalapi and blazor-crud T4 templates

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/CodeModificationStep.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Internal/GlobalToolFileFinder.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspire/Extensions/CachingScaffolderBuilderExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspire/Extensions/DatabaseScaffolderBuilderExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspire/Extensions/StorageScaffolderBuilderExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspire/Helpers/ValidationHelper.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspire/ScaffoldSteps/AddAspireCodeChangeStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Extensions/BlazorCrudScaffolderBuilderExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Extensions/MinimalApiScaffolderBuilderExtensions.cs
small fixes from picking the wrong parameter options values to calling into null refs fixed.
> minor fixes across the aspire scaffolders

- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.tt
cherry-picking #2919 for release/8.0 (had to fix merge conflicts)
> T4 template fixes release/8.0

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/CodeModificationStep.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/Microsoft.DotNet.Scaffolding.CodeModification.csproj
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/README.md
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Microsoft.DotNet.Scaffolding.Core.csproj
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/README.md
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn/Microsoft.DotNet.Scaffolding.Roslyn.csproj
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn/README.md
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.TextTemplating/Microsoft.DotNet.Scaffolding.TextTemplating.csproj
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.TextTemplating/README.md
- src/dotnet-scaffolding/dotnet-scaffold-aspire/README.md
- src/dotnet-scaffolding/dotnet-scaffold-aspire/dotnet-scaffold-aspire.csproj
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Common/PackageConstants.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/README.md
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/AreaScaffolderStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/DotnetNewScaffolderStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/EmptyControllerScaffolderStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/dotnet-scaffold-aspnet.csproj
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CategoryDiscovery.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CommandDiscovery.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/ParameterDiscovery.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/StartupFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/README.md
- src/dotnet-scaffolding/dotnet-scaffold/dotnet-scaffold.csproj
- added `README.md`'s for all dotnet-scaffolding projects
- changed some logged strings based on feedback.
> adding readmes and some string changes

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/CodeModificationStep.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/Microsoft.DotNet.Scaffolding.CodeModification.csproj
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/README.md
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Microsoft.DotNet.Scaffolding.Core.csproj
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/README.md
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn/Microsoft.DotNet.Scaffolding.Roslyn.csproj
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn/README.md
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.TextTemplating/Microsoft.DotNet.Scaffolding.TextTemplating.csproj
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.TextTemplating/README.md
- src/dotnet-scaffolding/dotnet-scaffold-aspire/README.md
- src/dotnet-scaffolding/dotnet-scaffold-aspire/dotnet-scaffold-aspire.csproj
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Common/PackageConstants.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/README.md
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/AreaScaffolderStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/DotnetNewScaffolderStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/EmptyControllerScaffolderStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/dotnet-scaffold-aspnet.csproj
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CategoryDiscovery.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CommandDiscovery.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/ParameterDiscovery.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/StartupFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/README.md
- src/dotnet-scaffolding/dotnet-scaffold/dotnet-scaffold.csproj
> adding readmes and some string changes (cherry-pick)

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/CodeModification/DocumentBuilder.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/CodeModification/ProjectModifier.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/CodeModificationStep.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/Constants.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/Helpers/ProjectModifierHelper.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Scaffolders/Scaffolder.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.TextTemplating/TextTemplatingEngineHost.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspire/Program.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspire/ScaffoldSteps/AddAspireCodeChangeStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Program.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateBlazorCrudStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateMinimalApiStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/AppBuilder/ScaffoldCommandApp.cs
- src/dotnet-scaffolding/dotnet-scaffold/Command/BaseCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold/Command/ScaffoldCommand.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/FlowExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CommandExecuteFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/StartupFlowStep.cs
- adding 'UseTopLevelStatements' code change option in `CodeModificationStep` correctly now
- not adding 'IsMinimalApp' code change option, was not being used.
- minor edits otherwise mostly.
> cleanup most of the TODOs in dotnet-scaffolding

- src/Scaffolding/VS.Web.CG.Mvc/BlazorIdentity/BlazorIdentityCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/Identity/IdentityGeneratorCommandLineModel.cs
- src/Scaffolding/VS.Web.CG.Mvc/ParameterDefinitions/blazor-identity.json
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Delete.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Details.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.cs
- src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Index.tt
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap4/CreatePageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap4/EditPageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/CreatePageModel.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/RazorPageGenerator/Bootstrap5/EditPageModel.cshtml
cherry-picking
* blazor-crud scaffolder minor fixes
* PR comment fixes 1
* changing heading sequence
* minor fix
> blazor-crud scaffolder minor fixes (#2938)

- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/EfController/ApiEfController.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/EfController/ApiEfController.tt
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/EfController/MvcEfController.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/EfController/MvcEfController.tt
fix apicontroller-crud and mvccontroller-crud templates for `dotnet-scaffold-aspnet`
> fixing ef crud controller templates

- eng/Versions.props
revert from 8.0.9 --> 8.0.8 since there is no 8.0.9 servicing.
> revert Versions.props

- scripts/install-scaffold-all.cmd
- src/dotnet-scaffolding/Directory.Build.props
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/Microsoft.DotNet.Scaffolding.CodeModification.csproj
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Microsoft.DotNet.Scaffolding.Core.csproj
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Internal/Microsoft.DotNet.Scaffolding.Internal.csproj
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn/Microsoft.DotNet.Scaffolding.Roslyn.csproj
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.TextTemplating/Microsoft.DotNet.Scaffolding.TextTemplating.csproj
- src/dotnet-scaffolding/dotnet-scaffold-aspire/dotnet-scaffold-aspire.csproj
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/dotnet-scaffold-aspnet.csproj
- src/dotnet-scaffolding/dotnet-scaffold/dotnet-scaffold.csproj
building both net9.0 and net8.0 for projects in `src\dotnet-scaffolding`
> targeting both net8.0 and net9.0 for src\dotnet-scaffolding

- Directory.Build.props
- eng/Versions.props
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Microsoft.DotNet.Scaffolding.Shared.csproj
- test/Scaffolding/VS.Web.CG.MSBuild.Test/VS.Web.CG.MSBuild.Tests.csproj
> Update transitive dependency for release/6.0

- Directory.Build.props
- eng/Versions.props
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Microsoft.DotNet.Scaffolding.Shared.csproj
- test/Scaffolding/VS.Web.CG.EFCore.Test/VS.Web.CG.EFCore.Tests.csproj
- test/Scaffolding/VS.Web.CG.MSBuild.Test/VS.Web.CG.MSBuild.Tests.csproj
- test/Scaffolding/VS.Web.CG.Mvc.Test/VS.Web.CG.Mvc.Tests.csproj
- test/Scaffolding/VS.Web.CG.Sources.Test/VS.Web.CG.Sources.Tests.csproj
> Update transitive dependency for release/8.0

- eng/Versions.props
- scripts/install-aspnet-codegenerator.cmd
- src/Scaffolding/VS.Web.CG.Mvc/BlazorIdentity/BlazorIdentityGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/BlazorIdentity/blazorIdentityChanges.json
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs
cherry-picking #2997
- some more additional fixes, mostly missing logic as the branches were inconsistent.
> minor Blazor Identity fixes

- NuGet.config
- eng/Version.Details.xml
- eng/Versions.props
Reverts dotnet/Scaffolding#3020
> Revert "[release/6.0] Update dependencies from dotnet/runtime"

- src/Scaffolding/VS.Web.CG.Mvc/BlazorIdentity/BlazorIdentityGenerator.cs
- `ConnectionStringsWriter.AddConnectionString`: Corrected the connection string name to use the `dbContextModel.DbContextName` instead of the hard-coded `DefaultConnection` string.
- try to find an existing `ApplicationUser` (should exist on blazor identity individual auth apps) before using the default `IdentityUser` (shipped with `Microsoft.AspNetCore.Identity`
> finding existing default ApplicationUser, also adding correct connection string.

- eng/Versions.props
> bump up versions

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Builder/ScaffoldBuilder.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/CommandLine/CommandLineExtensions.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/ComponentModel/CommandInfo.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Scaffolders/IScaffolder.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Core/Scaffolders/Scaffolder.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Extensions/BlazorCrudScaffolderBuilderExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Extensions/EfControllerScaffolderBuilderExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Extensions/MinimalApiScaffolderBuilderExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Extensions/RazorPagesScaffolderBuilderExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Program.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/FlowContextProperties.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/FlowExtensions.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CategoryDiscovery.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CategoryPickerFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CommandDiscovery.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/CommandExecuteFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Telemetry/CommandExecuteTelemetryEvent.cs
cherry-picking #3035 and #3040
> cherry picks for release/9.0

- src/dotnet-scaffolding/dotnet-scaffold/AppBuilder/ScaffoldCommandAppBuilder.cs
- src/dotnet-scaffolding/dotnet-scaffold/Flow/Steps/StartupFlowStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Helpers/CliHelpers.cs
- src/dotnet-scaffolding/dotnet-scaffold/Helpers/ToolHelper.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/FirstPartyComponentInitializer.cs
if prerelease, install prerelease first party-packages. If GA/release packages, install GA/release first party packages.
- checking for prerelease using the keywords often used for preview .NET packages.
> check dotnet-scaffold version, account for prerelease

- eng/Versions.DotNetScaffold.props
> update branding for dotnet-scaffold

- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/MinimalApiGenerator.cs
- src/Scaffolding/VS.Web.CG.Mvc/Minimal Api/minimalApiChanges.json
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEf.cshtml
- src/Scaffolding/VS.Web.CG.Mvc/Templates/MinimalApi/MinimalApiEfNoClass.cshtml
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/CodeModificationConfigs/minimalApiChanges.json
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateMinimalApiStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/MinimalApi/MinimalApiEf.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/MinimalApi/MinimalApiEf.tt
changes for .NET 9 api endpoints (minimal api) scenario : 
- removed Swashbuckle.AspNetCore dependency
- update Program.cs code modifications
- remove additional Open API, and Typed Result code modifications in the endpoints file (default changes are good)
> minimal api changes for .NET 9

- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateBlazorCrudStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateEfControllerStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateMinimalApiStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateRazorPagesStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateViewsStep.cs
> fix telemetry event names for 'Validation' methods

- test/legacy-scaffolding-tests.playlist
adding test playlists for easier testing. will add one for dotnet-scaffolding once more test projects are up.
> added 'legacy-scaffolding-tests' playlist

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Internal/Services/FileSystem.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Internal/Services/FirstTimeUseNoticeSentinel.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Internal/Services/IFileSystem.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/AddFileStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/AreaScaffolderStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/DotnetNewScaffolderStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/EmptyControllerScaffolderStep.cs
- src/dotnet-scaffolding/dotnet-scaffold/Services/ToolManifestService.cs
added `IFileSystem.CreateDirectoryIfNotExists`
> added to Microsoft.DotNet.Scaffolding.Internal.Services.IFileSystem

- eng/Versions.props
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Microsoft.DotNet.MSIdentity.csproj
- src/MSIdentityScaffolding/dotnet-msidentity/dotnet-msidentity.csproj
- src/Scaffolding/VS.Web.CG.Core/VS.Web.CG.Core.csproj
- src/Scaffolding/VS.Web.CG.Design-anycpu/VS.Web.CG.Design-anycpu.csproj
- src/Scaffolding/VS.Web.CG.Design-arm64/VS.Web.CG.Design-arm64.csproj
- src/Scaffolding/VS.Web.CG.Design/VS.Web.CG.Design.csproj
- src/Scaffolding/VS.Web.CG.EFCore/VS.Web.CG.EFCore.csproj
- src/Scaffolding/VS.Web.CG.Msbuild/Target/build/Microsoft.VisualStudio.Web.CodeGeneration.Tools.targets
- src/Scaffolding/VS.Web.CG.Msbuild/VS.Web.CG.Msbuild.csproj
- src/Scaffolding/VS.Web.CG.Mvc/VS.Web.CG.Mvc.csproj
- src/Scaffolding/VS.Web.CG.Templating/VS.Web.CG.Templating.csproj
- src/Scaffolding/VS.Web.CG.Utils/VS.Web.CG.Utils.csproj
- src/Scaffolding/VS.Web.CG/VS.Web.CG.csproj
- src/Scaffolding/dotnet-aspnet-codegenerator/TargetInstaller.cs
- src/Scaffolding/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/ProjectModel/ProjectModelHelper.cs
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.CodeModification/Helpers/ProjectModelHelper.cs
- test/Scaffolding/TestApps/ModelTypesLocatorTestClassLibrary/ModelTypesLocatorTestClassLibrary.csproj
- test/Scaffolding/TestApps/ModelTypesLocatorTestWebApp/ModelTypesLocatorTestWebApp.csproj
update to `net9.0` tfm for projects, package versions to GA/latest.
> update to newest GA versions.

- src/Shared/Microsoft.DotNet.Scaffolding.Shared/CodeModifier/ProjectExtensions.cs
- src/Shared/Microsoft.DotNet.Scaffolding.Shared/General/StringUtil.cs
- test/Shared/Microsoft.DotNet.Scaffolding.Shared.Tests/StringUtilTests.cs
> fix StringUtil.ToPath and some null checks (#3118)

- eng/Versions.DotNetScaffold.props
- scripts/install-scaffold-all.cmd
- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Roslyn/Services/MSBuildProjectService.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/ScaffoldSteps/ValidateIdentityStep.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorIdentity/Shared/AccountLayout.cs
- src/dotnet-scaffolding/dotnet-scaffold-aspnet/Templates/BlazorIdentity/Shared/AccountLayout.tt
> cherry-picking #3113

- src/dotnet-scaffolding/Microsoft.DotNet.Scaffolding.Internal/Telemetry/TelemetryConstants.cs
updating AppInsights instrumentation key
> update instrumentation key

- eng/Versions.props
- src/Scaffolding/VS.Web.CG.EFCore/VS.Web.CG.EFCore.csproj
> change EFCore.Design dependency to include assets (#3137)

- Directory.Packages.props
- eng/Versions.props
- src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/Microsoft.DotNet.MSIdentity.csproj
Updates System.Text.Json Package version
> Update System.Text.Json Package version

- NuGet.config
- eng/Versions.DotNetScaffold.props
- eng/Versions.props
- src/Scaffolding/Directory.Build.props
- src/Scaffolding/VS.Web.CG.Core/VS.Web.CG.Core.csproj
- src/Scaffolding/VS.Web.CG.Design-anycpu/VS.Web.CG.Design-anycpu.csproj
- src/Scaffolding/VS.Web.CG.Design-arm64/VS.Web.CG.Design-arm64.csproj
- src/Scaffolding/VS.Web.CG.Design/VS.Web.CG.Design.csproj
- src/Scaffolding/VS.Web.CG.EFCore/VS.Web.CG.EFCore.csproj
- src/Scaffolding/VS.Web.CG.Msbuild/VS.Web.CG.Msbuild.csproj
- src/Scaffolding/VS.Web.CG.Mvc/VS.Web.CG.Mvc.csproj
- src/Scaffolding/VS.Web.CG.Templating/VS.Web.CG.Templating.csproj
- src/Scaffolding/VS.Web.CG.Utils/VS.Web.CG.Utils.csproj
- src/Scaffolding/VS.Web.CG/VS.Web.CG.csproj
- src/Scaffolding/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj
- src/dotnet-scaffolding/Directory.Build.props
- src/dotnet-scaffolding/Directory.Packages.props
- test/Directory.Build.props
- test/Scaffolding/TestApps/ModelTypesLocatorTestClassLibrary/ModelTypesLocatorTestClassLibrary.csproj
- test/Scaffolding/TestApps/ModelTypesLocatorTestWebApp/ModelTypesLocatorTestWebApp.csproj
- test/Scaffolding/TestApps/ModelTypesLocatorTestWebApp/Models/CarContext.cs
Updates scaffolding to net10, using latest public preview 6 packages
> Update for 10.0.0-preview.6

- src/dotnet-scaffolding/dotnet-scaffold/AppBuilder/ScaffoldCommandAppBuilder.cs
> bump backupDotNetScaffoldVersion to 10.0.0

- Getting-Started.md
Editing to make it a little more straight forward.
> Simplify the Getting-Started.md
